### ISSUE TITLE
[1.19.2] Seamless loading screen incompatibility.

### ISSUE THREAD

**Issue by murao-kun** [FiniteReality/embeddium#10]
Both mods simply do not work together and this issue describe it entirely with possible fix on embeddium side.
https://github.com/Minenash/Seamless-Loading-Screen/issues/77

**Comment by embeddedt** [comment]
Thanks, I've applied a fix which will be in the next release.

**Comment by embeddedt** [comment]
Should be fixed in 0.1.2.
