### ISSUE TITLE
[1.16.5] Fast Graphics breaks the rendering of Blossoming Apple Leaves from Terra Incognita: The Unknown Land mod

### ISSUE THREAD

**Issue by Kasualix** [FiniteReality/embeddium#101]
# Fast
![image](https://github.com/embeddedt/embeddium/assets/110756250/dca3c6a9-ae31-472f-abd0-1ebb2ed7096b)
![image](https://github.com/embeddedt/embeddium/assets/110756250/03959cf9-06bb-4632-a6f7-9e9b3bc64f31)
____
# Fancy
![image](https://github.com/embeddedt/embeddium/assets/110756250/f4a72441-d6fd-445d-b4d3-2b20cb1ee563)
![image](https://github.com/embeddedt/embeddium/assets/110756250/aee49948-76ef-4239-814f-39468cc0e6a2)

**Comment by Kasualix** [comment]
Note: Leaves Quality setting is not related to this issue

**Comment by Kasualix** [comment]
The rendering of Cherry Leaves from Fruit Trees mod is also broken by this.
![image](https://github.com/embeddedt/embeddium/assets/110756250/0a61323c-9497-48f2-b5aa-5c087a471517)
![image](https://github.com/embeddedt/embeddium/assets/110756250/ed289b4b-8eb5-4a8d-aa5f-8b399b585a7f)

**Comment by embeddedt** [comment]
The issue with Terra Incognita seems to occur in vanilla too, so it is likely a bug in that mod.

The issue with Cherry Leaves only occurs with Embeddium Extras installed. I cannot reproduce it with just Embeddium. I suspect [your mixin](https://github.com/MCTeamPotato/EmbeddiumExtras/blob/1165/src/main/java/com/teampotato/embeddiumextras/mixins/performance/RenderTypeLookupMixin.java) and [theirs](https://github.com/Snownee/FruitTrees/blob/1.16/src/main/java/snownee/fruits/mixin/MixinRenderTypeLookup.java) conflict.
