### ISSUE TITLE
[1.20.1] Unable to disable fog in Better End & Better Nether.

### ISSUE THREAD

**Issue by VOLKOUL** [FiniteReality/embeddium#102]
This might not be on your end, rather a Connector thing, but since Embeddium focuses on compatibility I feel like this report fits here. Tbh I don't remember if Embeddium has a fog slider by default, I have Rubidium Extra installed and that's the mod that enables per-dimension fog sliders. Imma head over there and leave a report too.

**Comment by Kasualix** [comment]
https://github.com/dima-dencep/rubidium-extra/issues/48#issuecomment-1684942782

**Comment by embeddedt** [comment]
I believe that's a Rubidium Extra feature, yeah.
