### ISSUE TITLE
not working on newer forge versions

### ISSUE THREAD

**Issue by pvzfan1** [FiniteReality/embeddium#104]
theres been an issue with the original rubidium where it doesnt work on 1.19.2's & 1.20.1's newer forge versions (atleast on weaker pcs) and i suspect theres a similar issue here
it sometimes works fine, but the other half of the time it freezes during loading and forces you to close minecraft, its kind of a specific issue but i hope it gets fixed soon

it also gives this exit code when it crashes -805306369

**Comment by embeddedt** [comment]
This sounds like it is likely a GPU driver issue. Please ensure your graphics drivers are [up to date](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility), and if that doesn't work, try using Prism Launcher.
