### ISSUE TITLE
Weird Crash with building chunk meshes

### ISSUE THREAD

**Issue by TqLxQuanZ** [FiniteReality/embeddium#106]
It seems like only happen when mrcrayfish furniture is installed, but it is quite random and rare in certain circumstances.
Removing embeddium solves the issue.
[crash-2023-11-18_00.34.26-client.txt](https://github.com/embeddedt/embeddium/files/13394448/crash-2023-11-18_00.34.26-client.txt)

**Comment by embeddedt** [comment]
This looks like a thread safety bug in MrCrayfish's Furniture Mod and should be reported to them. They should use a `ConcurrentHashMap` instead.
