### ISSUE TITLE
Strange biomedata crash (?) mentioning sodium

### ISSUE THREAD

**Issue by thelegitdolt** [FiniteReality/embeddium#107]
Happened while I was exploring the world, just flying randomly in creative

https://gist.github.com/thelegitdolt/07af8c360a1c14832711a8d1a2f198ef

**Comment by embeddedt** [comment]
Your Embeddium version is very outdated; please update it. I believe it will fix the issue.

**Comment by thelegitdolt** [comment]
Sorry!!

**Comment by embeddedt** [comment]
No problem.
