### ISSUE TITLE
Embeddium not working with dropz or rayon 

### ISSUE THREAD

**Issue by hegegege** [FiniteReality/embeddium#108]
dropz is not working with Embeddium everytime i break a object it just flyes in the air

![Capturar](https://github.com/embeddedt/embeddium/assets/104654822/d9fc5d15-28e3-42fe-a30b-2b56b58594be)
![image](https://github.com/embeddedt/embeddium/assets/104654822/12856001-9f49-446e-b29a-663cdaa7e2a3)

**Comment by embeddedt** [comment]
You are using Rubidium & Oculus, not Embeddium.

**Comment by hegegege** [comment]
> You are using Rubidium & Oculus, not Embeddium.

oh sorry i read it wrong

**Comment by embeddedt** [comment]
On Fabric, Dropz has not been updated to work with Sodium in a long time, so this is probably just the same issue but on Forge.
