### ISSUE TITLE
[1.20.1] Incompat with Chunk Animator

### ISSUE THREAD

**Issue by Cixon** [FiniteReality/embeddium#11]
[crash-2023-09-04_18.47.43-client.txt](https://github.com/embeddedt/embeddium/files/12517249/crash-2023-09-04_18.47.43-client.txt)

log:

[latest.log](https://github.com/embeddedt/embeddium/files/12517250/latest.log)

**Comment by embeddedt** [comment]
Unfortunately this one is not really possible to fix - the mod uses a [mixin](https://github.com/Harleyoc1/ChunkAnimator/blob/1.20/src/main/java/lumien/chunkanimator/mixin/LevelRendererMixin.java) that relies on implementation details of the vanilla world renderer, which Sodium has to replace to achieve increased performance. They would need to write a custom mixin specifically targeting the Embeddium world renderer instead.

**Comment by embeddedt** [comment]
One option might be to see if the author of [Chunks fade in](https://modrinth.com/mod/chunks-fade-in) is interested in porting to Forge (or having someone else do such a port) as that mod appears to work with Sodium, and the same logic would most likely work with Embeddium.

**Comment by Cixon** [comment]
> Unfortunately this one is not really possible to fix - the mod uses a [mixin](https://github.com/Harleyoc1/ChunkAnimator/blob/1.20/src/main/java/lumien/chunkanimator/mixin/LevelRendererMixin.java) that relies on implementation details of the vanilla world renderer, which Sodium has to replace to achieve increased performance. They would need to write a custom mixin specifically targeting the Embeddium world renderer instead.

Gotcha. Thanks for being informative - may wait a around for your fork to get a bit more recognition before I submit a request to ChunkAnimator dev. I know chunk fade in exists but it's not exactly the same, sadly.
