### ISSUE TITLE
NeoForge fixes bug MC-193656, but Embeddium breaks the fix

### ISSUE THREAD

**Issue by Lolothepro** [FiniteReality/embeddium#110]
NeoForge:

https://github.com/embeddedt/embeddium/assets/68275908/4fb3ef59-b968-40e3-a513-28c069594abf

NeoForge + Embeddium:

https://github.com/embeddedt/embeddium/assets/68275908/bbf48e85-3cb8-4373-bc64-cf21edcb4bcb

Note: If possible, the fix should be ported to Sodium

**Comment by embeddedt** [comment]
This seems to occur in a standalone Fabric instance with just Sodium, and I believe Sodium replaces the code path that NeoForge patched. So this should be reported upstream first, and the fix can be ported to Embeddium afterwards.

**Comment by Lolothepro** [comment]
> This seems to occur in a standalone Fabric instance with just Sodium, and I believe Sodium replaces the code path that NeoForge patched. So this should be reported upstream first, and the fix can be ported to Embeddium afterwards.

I don't know if it's a good idea to open a compatibility/bugfix request between Fabric API and Sodium, since they aren't very compatible.
