### ISSUE TITLE
Panda's Extra Details causes crash in 0.2.10+

### ISSUE THREAD

**Issue by kaairu** [FiniteReality/embeddium#111]
forge: 47.2.1
1.20.1
embeddium-0.2.10

crash-report
https://mclo.gs/Gl8BQWt
log
https://mclo.gs/RO2jbYc

**Comment by embeddedt** [comment]
This crash appears to be caused by Panda's Extra Details modifying Embeddium internals, and should be reported to them. When mods invasively modify Embeddium in this manner, they are likely to break with updates.

**Comment by Groupix05** [comment]
Had the same problem, everything was working in 0.2.9.
Can confirm its pandas Extra Details that cause the crash.
