### ISSUE TITLE
[1.20.1 Forge] 0.2.10 startup crash, might not be from embeddium itself

### ISSUE THREAD

**Issue by PlayfulPiano** [FiniteReality/embeddium#112]
[crash-2023-11-23_20.42.10-client.txt](https://github.com/embeddedt/embeddium/files/13454376/crash-2023-11-23_20.42.10-client.txt)
looking at the crash it might be modernfix or embeddium plus related, so I did post an issue in the latter's repo (https://github.com/SrRapero720/EmbeddiumPlus/issues/2), but it doesn't seem to be a consistent crash.

last 3 times i've opened mc with the new version, only once did it crash.

**Comment by embeddedt** [comment]
It is a Forge bug, unrelated to any installed mods.
