### ISSUE TITLE
Strange flickerings of the sky in no-shaders AE2 spatial storage dimension

### ISSUE THREAD

**Issue by atealein** [FiniteReality/embeddium#115]
Hey,

I am playing FTB Genesis (1.19.2 MC) on a MacBook Pro (early 2015) without shaders and I am having very strange flickerings of lights in the "sky" that surrounds the space of my spatial cell. They are very quick when I turn my view and switch a lot, so it is very disorienting and honestly, even though I have no issues with epilepsia or anything like that, it is starting to make me dizzy.

I am not sure what extra information I should supply - the modpack uses 0.2.9+mc1.19.2 Embeddium.
Attaching a screenshot of a moment when i caught few of them. 
![2023-11-24_20 52 29](https://github.com/embeddedt/embeddium/assets/25322782/7f801e6f-d949-41a1-97ac-fa4253a6f3c2)

**Comment by embeddedt** [comment]
Are you able to reproduce this in a standalone instance with just Embeddium + AE2, when in the spatial storage dimension?

**Comment by atealein** [comment]
Yep, used a different launcher, installed just AE2 (version appliedenergistics2-forge-12.9.8 ) and embeddium 0.2.9+mc1.19.2. Made a spatial cell and went into the spatial dimension with it (didn't want to risk just teleporting, because when you make a full room it makes invisible walls, which might be the issue here, I don't know). Have the same issue. Adding few more screenshots. 

Notice that some of these are taken from exact same position - the flickering is happening and moving/appearing/disappearing even if I am standing completely still or even if I am in esc-menu. 

![2023-11-24_23 09 21](https://github.com/embeddedt/embeddium/assets/25322782/b1739466-7af6-4d6c-b404-4518a0f891a6)
![2023-11-24_23 09 43](https://github.com/embeddedt/embeddium/assets/25322782/f91db33b-7fbd-46f1-ab36-b23846f3081e)
![2023-11-24_23 09 44](https://github.com/embeddedt/embeddium/assets/25322782/46d8f5c3-fb5c-4735-bd24-1234a872fa10)
![2023-11-24_23 09 45](https://github.com/embeddedt/embeddium/assets/25322782/3a83da5d-78d4-4f95-bed1-2d51036df036)

**Comment by atealein** [comment]
Hey devs, sorry for the bother. I thought this was embeddium issue because of the Genesis devs suggested it might be this, but now that I had this testing world, I tested to remove embeddium and just with AE2 I still have the issue. So it isn't your mod, I'll go write on the AE2 github instead ;) Cheers!
