### ISSUE TITLE
Interpolated textures are not handled correctly

### ISSUE THREAD

**Issue by robertmaxton42** [FiniteReality/embeddium#118]
While I think Embeddium is handling Reactive's crucible fine (I haven't tested it enough without Embeddium to be sure, but at least the color blending seems to mostly work), the litmus paper results in a flickering item that is usually invisible except for a rectangle in the corner. Possibly related to https://github.com/hjake123/reactive/issues/4?

Can replicate with just Embeddium, Reactive and JEI.

**Comment by embeddedt** [comment]
It is a Sodium bug, which will be fixed in the next Embeddium release and will also be fixed upstream in https://github.com/CaffeineMC/sodium-fabric/pull/2185 if/when it's merged.

**Comment by embeddedt** [comment]
Sorry for the long wait, this should be fixed in 0.2.12.
