### ISSUE TITLE
[Enhancement] Methane adaptation for embeddium

### ISSUE THREAD

**Issue by Cixon** [FiniteReality/embeddium#12]
Though there's not currently any distinct differences from this fork to the OG; I'd like to place my two-cents.
I recently came across this mod that I'd love to see integrated into embeddium's renderer or maybe even a separate mod?
_(I don't know how these things work, not a programmer, lol)_

Anywho, the original mod creator doesn't appear to be interested in porting to forge but project is open-source and MIT, we'll see what the future holds or not?

Can't wait to see what you have planned for embeddium!
**Mod:** https://legacy.curseforge.com/minecraft/mc-mods/methane

**Comment by ghost** [comment]
Doesn't Methane straight up remove lighting? Incorporating something like this into a mod which focuses on compatibility is pretty pointless in my opinion.

**Comment by Cixon** [comment]
as a optional toggle, no. it’d be worth adding for those with poor systems that need more options for performance; not sure what embeddedt has planned but it’d be nice to see more options - even a way to change rendering API from openGL to [vulkan](https://www.curseforge.com/minecraft/mc-mods/vulkanmod) or something would be nice.

**Comment by embeddedt** [comment]
I'm happy to work with someone to implement hooks for a Methane port, but it's out of scope for Embeddium itself since disabling lighting requires changes to more than just the world renderer.

**Comment by Cixon** [comment]
gotcha. thanks for being open-minded!
