### ISSUE TITLE
Bug with rendering moving textures of blocks on Eureka-Valkyrien skies ships

### ISSUE THREAD

**Issue by vlad1m** [FiniteReality/embeddium#120]
Blocks like the globe from ,,supplementaries,, or the helm from ,,eureka ships,, have missing textures when the ship is assembled 
Minecraft 1.19.2
Embeddium 0.2.11

**Comment by embeddedt** [comment]
I believe Valkyrien Skies uses fairly invasive mixins to Embeddium, so I think this should be reported to them and they can reach out if it really is an issue in Embeddium.
