### ISSUE TITLE
Game crashes while using Cloth Config API

### ISSUE THREAD

**Issue by iPolarShadow** [FiniteReality/embeddium#122]
Hi, I was creating a modpack with embedium and when I was adding mods that need Cloth Config API the game crashed with error code 1.

**Comment by embeddedt** [comment]
Please send the `latest.log` file. This sounds likely to be a missing dependency error and not an issue with Embeddium.

**Comment by iPolarShadow** [comment]
You are right, it is a problem with the dependencies of another mod, not with embedium.
