### ISSUE TITLE
[Crash client] java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by DevDyna** [FiniteReality/embeddium#123]
After placed a shaft on top of a huge diesel engine from [create:diesel generator](https://legacy.curseforge.com/minecraft/mc-mods/create-diesel-generators) send on crash
[crash-2023-11-27_12.54.07-client.txt](https://github.com/embeddedt/embeddium/files/13473858/crash-2023-11-27_12.54.07-client.txt)

**Comment by embeddedt** [comment]
This crash is caused by another mod unsafely manipulating client block entities on the wrong thread, not Embeddium. Sound Physics is known to do this, so I would suggest removing it and seeing if the issue persists.

**Comment by DevDyna** [comment]
> This crash is caused by another mod unsafely manipulating client block entities on the wrong thread, not Embeddium. Sound Physics is known to do this, so I would suggest removing it and seeing if the issue persists.

i only see now , sorry for the issue
