### ISSUE TITLE
Array Index Out Of Bounds Exception crashes 

### ISSUE THREAD

**Issue by Syndrick** [FiniteReality/embeddium#125]
I am still getting Array Index Out Of Bounds Exception crashes very frequently while away from my base

**Comment by embeddedt** [comment]
Please provide the `latest.log` file where the crash occurs.

**Comment by Syndrick** [comment]
I'm sorry, I am unable to replicate it. if it starts happening again, I'll make sure to grab the latest log and post it either here or a new issue post if this one gets closed. Just so I know, would I upload the whole file, or just copy and paste what the file says?

**Comment by embeddedt** [comment]
If you can reproduce it again, make a new issue and just upload the whole file, please.
