### ISSUE TITLE
JVM terminates with EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by Zarvera** [FiniteReality/embeddium#127]
### Bug Description

Now, this was tormenting me for a while. I'm still not completely sure if it's really Embeddium, i'll report back if i'll encounter it without Embeddium enabled.
Anyway, tl;dr is that i've cobbled myself a pack on 1.20.1 which i couldn't play for more than a few minutes before it would terminate with no crash log but "hs_err_pid[number]" in the packs root folder instead. 
These logs are more or less same, with
>EXCEPTION_ACCESS_VIOLATION (0xc0000005)
and
>Problematic frame:
>C  [jemalloc.dll+0x1c706]
Now, as far as i understood this could be anything from gpu drivers acting up to faulty RAM sticks to dying motherboard.
What confuses me is that frequency of these JVM crashes changes with mods present - after i edited the pack the first time (and tested a few culprits like patches\tweaks\memory leak fix mods etc) crashes slowed down to maybe once in a hour or two. After i finalized the pack by removing and adding a few miniscule mods JVM started crashing in under a minute, it's practically unplayable.
Until it hit me yesterday that all the logs complain about rendering specifically, so first thing i tried was disable Embeddium, and yeah, played this instance without any crash for hours. 
Playing without Embeddium is suffering, so i hope i can be fixed somehow. All the mods are as up-to-date as possible via Modrinth.
The hs_err_pid logs are seemingly the same so i'll only add two for now.
I fear the worst judging by how there's practically nothing on the internet or here about this sort of issue.

### Reproduction Steps

I'm not sure how would one reproduce it outside maybe recreating the pack.
Or me checking if i can minimise the pack while still retaining the problem

### Log File

[hs_err_pid16812.log](https://github.com/embeddedt/embeddium/files/13535957/hs_err_pid16812.log)
[hs_err_pid12896.log](https://github.com/embeddedt/embeddium/files/13535959/hs_err_pid12896.log)

**Comment by embeddedt** [comment]
Unfortunately, this type of error usually indicates an issue with graphics drivers or system configuration, neither of which Embeddium can fix easily. I would suggest updating your GPU drivers, and also checking whether any of the info on Sodium's [graphics compatibility](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility) page applies to you.

**Comment by Zarvera** [comment]
Already cleaned drivers with DDU and reinstalled, didn't help much.
I'm on Forge so Sodium is out of the equation as it's a Fabric mod. 
So does it basically means that Embeddium isn't working on NVIDIA cards? The only solution i see on that page is running through Prism. I'll try that. 
Thanks!

**Comment by embeddedt** [comment]
> So does it basically means that Embeddium isn't working on NVIDIA cards?

No, for the vast majority of users it works (as otherwise I would have a storm of issue reports). However the drivers are known to have been buggy and caused random issues in the past.

**Comment by Zarvera** [comment]
You are right.
Anyway, Prism instantly soiled the bed with the same error.
Guess my only option is to reinstall drivers again, they ain't reinstalling themselves.
