### ISSUE TITLE
[NeoForge 1.20.2] Crash when creating/ joining a world

### ISSUE THREAD

**Issue by TH3N3WN00B** [FiniteReality/embeddium#129]
### Bug Description

Game crashes when creating and joining a world

### Reproduction Steps

Create a new instance of neoforge 1.20.2 - 20.2.86, add embeddium 0.2.10 and ferritecore 6.0.2, create a world

### Log File

Latest log: https://mclo.gs/ERRkanH

Latest Crash report (from the same log as above): https://mclo.gs/jL1vLT2

**Comment by embeddedt** [comment]
This is caused by breaking changes in NeoForge and will be fixed with the next release.

**Comment by embeddedt** [comment]
Fixed in 0.2.12.
