### ISSUE TITLE
embeddium+rubidium extra has erro

### ISSUE THREAD

**Issue by QiHuang02** [FiniteReality/embeddium#13]
Minecraft 1.20.1

Noeforge 47.1.76

[crash-2023-09-05_19.21.57-client.txt](https://github.com/embeddedt/embeddium/files/12522885/crash-2023-09-05_19.21.57-client.txt)
[debug.log](https://github.com/embeddedt/embeddium/files/12522892/debug.log)
[latest.log](https://github.com/embeddedt/embeddium/files/12522893/latest.log)

**Comment by embeddedt** [comment]
This is caused by Rubidium Extra mixing into Sodium internals that were refactored in 0.5.1/0.5.2. This doesn't look trivial to work around from my end, so that mod will need to be updated.
