### ISSUE TITLE
Immersive Portals Incompatibility [1.16.5]

### ISSUE THREAD

**Issue by EdoEquin0x** [FiniteReality/embeddium#132]
### Bug Description

The biomes near the players are invisible
![2023-12-07_14 00 42](https://github.com/embeddedt/embeddium/assets/69121197/1f85848d-2b3f-4aa2-b8f8-faa96fde41f2)

### Reproduction Steps

Install Embeddium and Immersive Portal

### Log File

None, it happens in game

**Comment by embeddedt** [comment]
I looked into this a while ago and it's not possible to fix - Immersive Portals heavily modifies the vanilla renderer to achieve its effect, and those patches don't apply to Sodium/Embeddium's replacement renderer. That old version of Immersive Portals doesn't have any Sodium integration.
