### ISSUE TITLE
[1.20.1] Compasses/clocks are functional in EMI

### ISSUE THREAD

**Issue by BookerCatch** [FiniteReality/embeddium#134]
### Bug Description

Item textures that dynamically change in the inventory (clock, compass) are being rendered in EMI's stack list. This includes similar items from other mods, like Supplementaries' altimeter or Cold Sweat's thermometer. The issue is only present when EMI & Embeddium/Rubidium are loaded together. JEI + Embeddium/Rubidium does not have this issue. Please see issue post on EMI's repo.

https://github.com/emilyploszaj/emi/issues/359

### Reproduction Steps

Load EMI & Embeddium together.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13601605/latest.log)

**Comment by embeddedt** [comment]
Interesting. Seems to be a problem with Sodium too. https://github.com/CaffeineMC/sodium-fabric/issues/2199

**Comment by embeddedt** [comment]
After further analysis & confirmation it appears to be an EMI issue - the reason it is not visible without Embeddium is because it uses different code for vanilla.
