### ISSUE TITLE
[1.16.5] Graphics/Leaves Quality settings

### ISSUE THREAD

**Issue by 2929762171** [FiniteReality/embeddium#135]
### Bug Description

Rendering changes only occur after the Graphics setting is changed.
Only change the Leaves Quality is no working.
![image](https://github.com/embeddedt/embeddium/assets/98941945/60ccaa23-d7f9-4b6b-966e-67085378739d)
![image](https://github.com/embeddedt/embeddium/assets/98941945/b9a4aa38-2862-4ed6-8482-c7cf0bb179aa)
![image](https://github.com/embeddedt/embeddium/assets/98941945/51542b10-74b7-493f-b082-caf0441dce3f)
![image](https://github.com/embeddedt/embeddium/assets/98941945/f4fb3349-437c-4771-9f99-24b106362c9c)

### Reproduction Steps

 Change Leaves Quality when Graphics is "Fast"

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13629622/latest.log)

**Comment by embeddedt** [comment]
Please test if this can be reproduced without addons.

**Comment by embeddedt** [comment]
It seems to work fine with just Embeddium for me.

![2023-12-10_19 02 17](https://github.com/embeddedt/embeddium/assets/42941056/6ce18305-24f3-4231-a391-1e957ae08054)
![2023-12-10_19 02 40](https://github.com/embeddedt/embeddium/assets/42941056/618e0735-f5c4-4ea6-b32d-6220539c38f4)

**Comment by 2929762171** [comment]
Well, embeddiumextras did this...
