### ISSUE TITLE
water in 1.16.5 has a blending bug

### ISSUE THREAD

**Issue by ghost** [FiniteReality/embeddium#136]
### Bug Description

water in 1.16.5 has a blending bug wich makes the water that isn't the base color have a grid-like patern all over it
![image](https://github.com/embeddedt/embeddium/assets/143887850/ff7c7cc3-63fe-4ff0-8635-47f4fbb55f2a)

### Reproduction Steps

just use latest embeddium (0.2.12) and go to a biome like the lukewarm ocean, warm ocean, or swamp

### Log File

none

**Comment by embeddedt** [comment]
Thanks, fixed in 0.2.13.
