### ISSUE TITLE
1.19.2 Mod Causes geckolib mobs's head to shake violently.

### ISSUE THREAD

**Issue by DelphiDv** [FiniteReality/embeddium#137]
### Bug Description

minecraft: 1.19.2
forge: 43.3.0
embeddium: 0.2.12
geckolib: 3.1.40(latest on curseforge)

When this mod is installed some mobs from mods relying on geckolibs have their head semi randomly shake violently.
It is very noticable with Gnumus froms Gnumus Settlement and Drones from enemy expansion, but is also happening to some others.

https://github.com/embeddedt/embeddium/assets/28810353/92f182ed-0828-4a26-a7f2-4556d95c6023

### Reproduction Steps

- Have both mods at once.
- hit or collide with an entity or just let it wander and see its head turn around incredibly fast in all direction.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13630545/latest.log)

**Comment by embeddedt** [comment]
I'm not able to reproduce this with just Embeddium and the two mods mentioned. I tried hitting a Drone and watching it for a while; never saw the head shake as shown in the video.

**Comment by DelphiDv** [comment]
Weird, are we using the same versions of everrthing? Could it be a driver thing? i didnt look into this because im not using a nvdia card/drivers.

**Comment by DelphiDv** [comment]
So managed to fix it, the new mod update + a driver update together seemed to have fixed it.

The mod update seem to have reduced it and the driver update completly fixed it.
