### ISSUE TITLE
embeddium-0.2.13+mc1.20.1 won't start

### ISSUE THREAD

**Issue by smertVkedax** [FiniteReality/embeddium#138]
### Bug Description

The first launch fails and crashes when creating a world. embeddium-0.2.13+mc1.20.1 error. 

### Reproduction Steps

Minecraft constantly crashes with new versions of the mod. On version embeddium-0.2.10+mc1.20.1 it works like a Swiss watch. But as soon as you update, the game immediately stops working. Help solve the problem! Your description does not support CaffeineMC. Could this be due to mods created using CaffeineMC?

### Log File

[crash-2023-12-11_23.37.58-client.txt](https://github.com/embeddedt/embeddium/files/13640807/crash-2023-12-11_23.37.58-client.txt)

**Comment by embeddedt** [comment]
As mentioned at the top of the crash report...

> RivaTuner Statistics Server (RTSS) is not compatible with Sodium [Embeddium], see this issue for more details: https://github.com/CaffeineMC/sodium-fabric/issues/2048

**Comment by smertVkedax** [comment]
Thank you
