### ISSUE TITLE
[1.20.1] Embeddium 0.2.13 failing to allow launch

### ISSUE THREAD

**Issue by BluSodah** [FiniteReality/embeddium#139]
### Bug Description

I have no idea what may be effecting it. The private modpack works without embeddium (and oculus because they are a pair), but as soon as i added the 0.2.13 it wont even get through the first part of the load. It only returns with a error code: 1. No crash report since the game never loaded.

I was using 0.2.8 embeddium before i tried to update. I know i'm a few updates behind, but its client side and thus wasnt important to me being able to join the smp. 

### Reproduction Steps

Honestly, if its a conflict with one of the mods that it didn't have an issue with in the older version, it will take me forever, thus its my own fault and you can ignore. 

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13641932/latest.log)

**Comment by embeddedt** [comment]
You have Rubidium installed at the same time; remove it.
