### ISSUE TITLE
[1.20.1 ONLY] Flywheel backend is currently non-functional

### ISSUE THREAD

**Issue by hjro1** [FiniteReality/embeddium#14]
the cogwheels from create are invisible when i use this mod, im using the lastest version of minecraft, forge and create

**Comment by embeddedt** [comment]
Confirmed. It looks like Flywheel [requires updates](https://github.com/Jozufozu/Flywheel/pull/200) to work with Sodium 0.5.2. Running `/flywheel backend off` appears to work around this for now; you may experience slightly degraded performance around Create contraptions.

**Comment by embeddedt** [comment]
This is fixed as of Create 0.5.1.e. Anyone who used the workaround above should run `/flywheel backend instancing` (or, if that does not work, `/flywheel backend batching`) after updating to disable it and restore full performance.

**Comment by vgrynch** [comment]
This is still not completely fixed for DYnamic lights. Dynamic lights do not even light up the stationary cogwheels, still have to use /flywheel backend off :(

**Comment by embeddedt** [comment]
To some degree I believe Flywheel controls its own lighting. So I'm not sure that can be fixed from my end alone.
