### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null

### ISSUE THREAD

**Issue by SilentStormLE** [FiniteReality/embeddium#141]
### Bug Description

Randomly my game just crashes and I saw one other person with the same issue with sound physics but I doubt its the same issue as its crashed always while rendering a specific block so I'm hoping someone knows what's going on. I have tried removing sound physics in the past however it didn't fix it because it crashed with the same report so I just put it back in.

### Reproduction Steps

I don't know specifically what causes it to crash however if I were to guess I would assume it has to do with the block it was rendering due to the fact that it always crashes while rendering it.

### Log File

[crash-2023-12-13_14.01.44-client.txt](https://github.com/embeddedt/embeddium/files/13665343/crash-2023-12-13_14.01.44-client.txt)

**Comment by embeddedt** [comment]
I don't think this crash is Embeddium's fault; one of your mods is returning a null list of quads when it shouldn't be. The versions of Rechiseled, Fusion, and Embeddium you are using are quite old; I would suggest updating them as the issue has probably been fixed since then.

**Comment by SilentStormLE** [comment]
Okay thanks for your time, I'll try this to see it it helps although I have to keep Embeddium at that version because it causes a lot of problems otherwise.
