### ISSUE TITLE
Crash with flywheel

### ISSUE THREAD

**Issue by mxnmnm** [FiniteReality/embeddium#142]
### Bug Description

I crash when I explore the nether, I thought it was sound physics because of this issue: https://github.com/embeddedt/embeddium/issues/123 but after removing sound physics it randomly happened again. I honestly don't know how to narrow it down and reliably reproduce it so I can narrow down the mods. The server stays up but my client crashes and I can log back in without any issues. I hope this information helps. I made an issue with flywheel because the crash said this mod and flywheel were the most suspect https://github.com/Jozufozu/Flywheel/issues/216

### Reproduction Steps

1. Explore the nether in a brand new world
2. Randomly crash (idk how to reliably reproduce beyond exploring the nether in a fresh world)

### Log File

log: https://gist.github.com/mxnmnm/123896114b861eaa19ba80f6f25cda6a
crash: https://gist.github.com/mxnmnm/8afa3d72497ecafcdb411d6bd61a69f3

**Comment by embeddedt** [comment]
This crash is not Embeddium's fault; another mod is mutating the client world on a background thread when it shouldn't be (probably Entity Culling if I had to guess).
