### ISSUE TITLE
[1.19.2] Rendering issue with Chunk Sending (occurs with at least two different mods)

### ISSUE THREAD

**Issue by Nereithr** [FiniteReality/embeddium#144]
### Bug Description

**Update:** Narrowed down the list of mods, updated the repro.

To start this off, I'm not exactly sure if I should post this issue just here or also in the other mods' issue pages since this only occurs due to an extremely specific cross-mod interaction as far as I could repro. Standard stuff: Forge version is latest, Embeddium is latest, all mods mentioned in the bug report are on their latest version.

The Workshop mod includes tool racks on which items are rendered and can be moved between the slots. Expected behaviour is that this interaction is rendered properly at all times. What actually happens is that upon the initial world load, "phantom" items are rendered on the tool racks upon taking items from them and new items put onto the racks do not render. This behaviour persists until the chunk is either forcibly reloaded or updated by placing a block. [It's far easier to just showcase this using this Imgur video.](https://imgur.com/SJDBu0I)

After the chunk is reloaded by any means or a block is placed, the items finally start rendering properly. This persists between world loads (for these specific tool racks at least) and the issue only occurs again after fully restarting the game.

### Reproduction Steps

This issue only occurs due to a *very* specific cross-mod interaction. The absolute minimum list of mods I could get this to trigger with are:

- **Embeddium**
- **Chunk Sending mod**, [here is the Curseforge link](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric) to its description, it changes the chunk packet sending logic
  - Cupboard Utilities, a dependency
- **Pluto** or **Krypton Reforged**
- **Starlight**
- *Workshop for handsome adventurers* - the mod the rendering issue occurs with
- *Simple Drying Racks* - another mod where this rendering issue occurs

Removing **any** of the above (non-content) mods fixes the issue and the items are rendered properly.

Actual steps to repro in-game:
1. Create a world, place down a tool rack from the Workshop mod and/or a drying rack from Simple Drying Racks
2. Insert a supported tool or food item
3. Save the world and *fully exit the game*
4. Start the game, load the world
5. Attempt to interact with the racks by either taking or inserting the items
6. The tool rack won't be properly updated
7. Place a block nearby, presentation is updated
8. The issue will no longer occur (at least with this specific tool rack) until the game instance is fully restarted

In terms of settings, none of Embeddium's settings seem to impact the result whatsoever. Chunk sending's settings are default.

For the time being, I'm only opening this issue here since this pertains to rendering, but if necessary I can open it on other repos.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/1361238127/latest.log)

The log file includes mentions of other mods but they are all disabled apart from the mods mentioned in repro.

**Comment by embeddedt** [comment]
I tried following the reproduction steps but couldn't reproduce the issue. I suspect what is happening is that the network optimization mods change the timing of when the chunk update packet is sent from the integrated server to the client, and Embeddium's renderer is not properly notified that the block was updated. Not sure if I will be able to fix this without a reliable reproduction.

**Comment by embeddedt** [comment]
A code analysis suggests the optimizations in Chunk Sending & Pluto/Krypton might conflict. What happens when Pluto/Krypton are removed in the full modpack?

**Comment by Nereithr** [comment]
Just rechecked by removing Pluto - this fixes the issue (as stated in the OP). Removing Chunk Sending fixes it too, having both of these mods active at the same time does seem to be the culprit.

**Comment by embeddedt** [comment]
I've added a note on the new [unsupported mods](https://github.com/embeddedt/embeddium/wiki/Unsupported-mods#chunk-sending-when-installed-with-kryptonpluto) page that Chunk Sending & Pluto should not be used together due to implementing the same optimization.

**Comment by Krimatoria** [comment]
By the way, we played my new build of 200+ mods now with Pluto and threw it away. I can't say it's because of this mod. Since I haven't tested with Krypton Reforged yet. I've never flown with him before.

> Только что перепроверил, удалив Плутон - это устраняет проблему (как указано в ОП). Удаление Chunk Sending также исправляет проблему: похоже, что причиной тому является одновременное использование обоих этих модов.
