### ISSUE TITLE
[1.18.2 Forge] When using emddium 2.5+, some entity blocks become invisible on VS ship.

### ISSUE THREAD

**Issue by xiewuzhiying** [FiniteReality/embeddium#148]
### Bug Description

Mod List:

- Embeddium [0.2.13+mc1.18.2]

- kotlinforforge-3.12.0-all

- VS Eureka Mod [1.4.0-beta.1]

- Architectury [4.11.93]

- Valkyrien Skies 2 [2.1.1-beta.3+847537425c]

- Clockwork: Create x Valkyrien Skies [0.0.1-alpha+350ee73315]

- Create [0.5.1.e]

As the title. 

The left side of the picture is the rendering of the blocks in the world, and the right side of the picture is the rendering of the blocks on the ship.
![embeddium2.4](https://github.com/embeddedt/embeddium/assets/92735961/f5673243-7e7e-4aca-b0e0-a8652b41b0ef)
![embeddium2.5](https://github.com/embeddedt/embeddium/assets/92735961/ed8a8620-1e82-4017-a2dd-f1d851d681fc)
![embeddium2.13](https://github.com/embeddedt/embeddium/assets/92735961/38ed30d7-8136-4a1e-9554-b8c918bd11c9)

### Reproduction Steps

- Install and run Valkyrien Skies and Embeddium simultaneously.
- Create a new world.
- Prepare some structures and activate them as a VS ship.
- Observe the rendering of entity blocks on the ship.

### Log File

https://pastebin.com/rNaCMFTr

**Comment by embeddedt** [comment]
Please report this to Valkyrien Skies and mention that Embeddium 0.2.5+ does frustum culling on block entities. As far as I know, VS relies on custom integration to work, and it might need an update to function correctly with this change. If there is something I need to do from my end, I am happy to work with them.
