### ISSUE TITLE
[1.16.5] Incompatibility with Dynamic Tree

### ISSUE THREAD

**Issue by EdoEquin0x** [FiniteReality/embeddium#149]
### Bug Description

Weird rendering issue when breaking trees from Dynamic Tree. Also, the rendering issue persist after the tree is broken and spread to similar trees around

### Reproduction Steps

Install Embeddium with Dynamic Tree, Dynamic Tree + and/or other addons. Interestingly enough, the issue occur with Rubidium as well

### Log File

None, so I will provide screenshots instead
![2023-12-19_17 44 42](https://github.com/embeddedt/embeddium/assets/69121197/5fba33ab-1879-4923-83fa-588a4fb50d42)
![2023-12-19_17 44 23](https://github.com/embeddedt/embeddium/assets/69121197/0c63b214-f522-4c9d-bf8e-4ad31b2c8df1)
![2023-12-19_17 42 00](https://github.com/embeddedt/embeddium/assets/69121197/f8af41b6-f958-439d-8ed4-0e12251d6da0)

**Comment by embeddedt** [comment]
I can't reproduce this in a standalone instance with Embeddium & Dynamic Trees. Please provide specific steps to reproduce (ideally, a world seed, and what actions I should take after joining the world).

**Comment by EdoEquin0x** [comment]
For some reason I can't reproduce it in singleplayer either, the screens were taken on a server with Dynamic Tree and Dynamic Tree+ and a client with thoses two plus Embeddium

**Comment by EdoEquin0x** [comment]
![image](https://github.com/embeddedt/embeddium/assets/69121197/7903f1c1-ef31-4025-ac2f-1d8f1fa543b0)
![image](https://github.com/embeddedt/embeddium/assets/69121197/c5876a66-5fe7-4470-9b36-658761ac542c)
![image](https://github.com/embeddedt/embeddium/assets/69121197/3e5b489c-9b46-4f15-8ad1-c2141a796a4c)

If that can help, it's a bug that occur since a long time

**Comment by embeddedt** [comment]
I set up a server with those two mods but after breaking numerous trees & cacti, they have all rendered correctly.

**Comment by EdoEquin0x** [comment]
Very weird then

**Comment by embeddedt** [comment]
Indeed. Unfortunately it's unlikely I'll be able to do anything about it unless a way is found to reproduce it reliably, or unless a Dynamic Trees developer can offer insight into what the problem might be.

**Comment by EdoEquin0x** [comment]
https://github.com/spoorn/sodium-forge/issues/17 It was reported there as well and many times on discord but yeah, no solid explanation was given

**Comment by EdoEquin0x** [comment]
![image](https://github.com/embeddedt/embeddium/assets/69121197/ee2a3101-9305-4a8e-928c-0a1cdc324e51)
My bad, an explanation was given: If that can help, the mod author said that

**Comment by embeddedt** [comment]
Embeddium already includes many patches to work with custom Forge models (and many other mods' models work correctly), so the issue must be more nuanced than that.

**Comment by EdoEquin0x** [comment]
I don't know then. Maybe it's a client-side settings that does that ?

**Comment by embeddedt** [comment]
I can't think of any setting that would cause this behavior.

**Comment by EdoEquin0x** [comment]
I think is was an isolated issue, it doesn't happen anymore, my bad!
