### ISSUE TITLE
After updating 0.2.12 to version 1.20.1, Minecraft no longer opens for those who have Riva Turner installed

### ISSUE THREAD

**Issue by hurr1canee** [FiniteReality/embeddium#150]
### Bug Description

After updating 0.2.12 to version 1.20.1, Minecraft no longer opens for those who have Riva Turner installed

### Reproduction Steps

After updating 0.2.12 to version 1.20.1, Minecraft no longer opens for those who have Riva Turner installed

### Log File

![Screenshot_3](https://github.com/embeddedt/embeddium/assets/107153831/a8390ce7-8ab3-41c7-98f4-3419a7cf83c3)

**Comment by hurr1canee** [comment]
With version 0.2.10 I have no problem

**Comment by embeddedt** [comment]
This is intended. See https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible.

**Comment by avc1657** [comment]
I installed embeddium 0.3.4 and minecraft opened even with RTSS running. Has anything changed? Are they now compatible?

**Comment by embeddedt** [comment]
Newer versions of RTSS seem to be compatible, so Sodium/Embeddium attempt to detect the RTSS version and keep going if it's known to be okay.
