### ISSUE TITLE
Embeddium + Ocules cause glowing leaves

### ISSUE THREAD

**Issue by xam290** [FiniteReality/embeddium#154]
### Bug Description

Ocules 1.6.13
Embeddium 0.2.13
Neoforge 1.20.1 ~ 47.1.84
BSL shader

By using all those mods together, the game does replace all pixels that should be transparent with some kind of glowing pixels. This only accrues to leaves, as far as I know. If Embeddium is removed, all leave-related problems are gone as well. The shader works perfectly without Embeddium.

![Embeddium_report](https://github.com/embeddedt/embeddium/assets/83453030/6e3efa37-2a6c-45f7-948f-c24818d1f160)

### Reproduction Steps

Ocules 1.6.13
Embeddium 0.2.13
Neoforge 1.20.1 ~ 47.1.84
BSL shader

Join a survival creative world and place leaves. As soon as the BSL shader is enabled all transparent leave pixels are glowing.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13744796/latest.log)

**Comment by embeddedt** [comment]
Does the issue occur with Embeddium installed and Oculus uninstalled? If not, it should be reported on Oculus' end, as it modifies Embeddium internals.

**Comment by xam290** [comment]
It doesn't, as it only occurs if shaders are enabled.

**Comment by embeddedt** [comment]
Please report the issue on Oculus' repo then.
