### ISSUE TITLE
Ice in 1.16.5 has a render bug

### ISSUE THREAD

**Issue by GoldenTotem** [FiniteReality/embeddium#156]
### Bug Description

Minecraft 1.16.5  Forge 36.2.35  Embeddium 0.2.13

Ice in water looks stange at the chunk borders and other places.

Modded
![2023-12-24_23 56 33](https://github.com/embeddedt/embeddium/assets/70516358/42998fc6-c8ec-4e11-bc36-2383f39904f4)

Vanilla
![2023-12-24_23 57 25](https://github.com/embeddedt/embeddium/assets/70516358/03119c8d-aefa-4f2f-9b6a-6e46d5416614)

### Reproduction Steps

1. Create a superflat world, use  minecraft:bedrock,31*minecraft:white_wool,32*minecraft:water;minecraft:warm_ocean
2. Stand in water and run command /fill ~18 ~ ~18 ~-18 ~ ~-18 ice
3. Uninstall the mod and rejoin the same world, compare the 2 satuation.

### Log File

_

**Comment by embeddedt** [comment]
Enable translucency sorting in video settings.
