### ISSUE TITLE
[1.20.4] Game crashes with Embeddium-0.2.14,Neoforge-20.4.57-beta

### ISSUE THREAD

**Issue by Enderman112** [FiniteReality/embeddium#157]
### Bug Description

Game crashes after click start
![图片](https://github.com/embeddedt/embeddium/assets/75347659/f53bdd51-6c42-4c3e-bc2d-c7ca28c5f9b6)
Neoforge version:Neoforge-20.4.57-beta
Embeddium version:embeddium-0.2.14
![图片](https://github.com/embeddedt/embeddium/assets/75347659/f4e2488c-bb9d-46f4-b92e-aee659743b1f)

### Reproduction Steps

1.Click start
2.Game crashes

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13766542/latest.log)
[crash-2023-12-25_23.00.50-fml.txt](https://github.com/embeddedt/embeddium/files/13766544/crash-2023-12-25_23.00.50-fml.txt)

**Comment by embeddedt** [comment]
Thanks, fixed in 0.2.15.
