### ISSUE TITLE
Occasionally crashes with lucent

### ISSUE THREAD

**Issue by Aceplante** [FiniteReality/embeddium#159]
### Bug Description

Title. Do you have a suggestion for a dynamic lighting mod that works with your mod?

Forge 1.20.1

### Reproduction Steps

install both your mod and lucent,
play for a while

### Log File

N/A

**Comment by embeddedt** [comment]
Please provide a `latest.log` file that's associated with the crash, as requested in the template. Note, however, that Lucent tends to do its lighting stuff off-thread, which is likely to be unsafe and cause crashes with other mods, not just Embeddium.

> Do you have a suggestion for a dynamic lighting mod that works with your mod?

There should be several Rubidium/Embeddium addons that add dynamic lights if you search.

**Comment by Aceplante** [comment]
ended up using embeddium ++
