### ISSUE TITLE
Crash with rubidium-extra-0.5.0+mc1.20.1-build.98.jar

### ISSUE THREAD

**Issue by magcicada** [FiniteReality/embeddium#16]
Just crash with [Rubidium Extra](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra), it work with Rubidium well.
The crash only happen at version mc1.20.1, 1.19.2 and other version work well.
[crash-2023-09-05_23.10.04-client.txt](https://github.com/embeddedt/embeddium/files/12525436/crash-2023-09-05_23.10.04-client.txt)

**Comment by magcicada** [comment]
This issue also report to rubidium-extra:https://github.com/dima-dencep/rubidium-extra/issues/53

**Comment by embeddedt** [comment]
I cannot fix this on my end, as the mod uses mixins into Sodium/Embeddium internals.
