### ISSUE TITLE
Game crashed 

### ISSUE THREAD

**Issue by Ryuushen** [FiniteReality/embeddium#160]
### Bug Description

Forge  version: 40.2.14
Mod version: 0.2.16

### Reproduction Steps

Embedium, Modernfix, Visuality Reforged, Blueprint installed and crashed when it's raining near the lake

### Log File

[crash-2023-12-26_23.26.00-client.txt](https://github.com/embeddedt/embeddium/files/13776482/crash-2023-12-26_23.26.00-client.txt)

**Comment by embeddedt** [comment]
This crash looks likely to be caused by Visuality, not Embeddium; the crash isn't occuring within Embeddium code. I'd suggest reporting this on their end.
