### ISSUE TITLE
Incompatible with [EMF] Entity Model Features

### ISSUE THREAD

**Issue by Busyfox123** [FiniteReality/embeddium#161]
### Bug Description

Minecraft version：1.20.1
forge:47.2.0
[1.20.1] Embeddium 0.2.16
EMF] Entity Model Features[Forge 1.20.1] 1.1.0
Tested in environments with only Embeddium, EMF, and Oculus
![2023-12-27_22 37 27](https://github.com/embeddedt/embeddium/assets/117924192/0a528407-7519-4200-86b7-df8701f75b64)

![2023-12-27_22 37 43](https://github.com/embeddedt/embeddium/assets/117924192/b67ea3af-0c8e-4887-b9c4-106c25574bc6)

### Reproduction Steps

Wearing armor from other mods while using [EMF] Entity Model Features can cause a significant decrease in frame rate
Embeddium
When using a third person perspective or looking at other players, if the opponent is wearing armor, the frame rate will significantly decrease
Deleting Embeddium will not cause this issue
When the shader is not loaded, the frame rate will also be significantly reduced

### Log File

![2023-12-26_23 55 29](https://github.com/embeddedt/embeddium/assets/117924192/50239b38-8199-422c-8664-e00de5812f5b)
![2023-12-26_23 55 45](https://github.com/embeddedt/embeddium/assets/117924192/ea5d3e0d-a1b9-423d-b9b2-4df048914cc6)

**Comment by embeddedt** [comment]
Please provide more information.

* What resource pack/mod are you using for the armor models in the screenshot?
* Please run a client-side Spark profile when the lag is occuring, by installing the Spark mod, and running the command `/sparkc profiler start`, waiting 15 seconds, then running `/sparkc profiler stop`. Please provide the URL you get in a response to this issue.

**Comment by Busyfox123** [comment]
mod:
Obscure API 
Aquamirae 6 API15 (1.20.1)
twilightforest-1.20.1-4.3.1893-universal

spark:
https://spark.lucko.me/Lb3B3zs2qX

**Comment by embeddedt** [comment]
Based on the Spark profile, it looks like the lag is coming from EMF's code. I would suggest reporting this to them and showing them the same link.

**Comment by embeddedt** [comment]
Allegedly this is fixed in EMF 1.2.1, please open an issue on their end if it still lags.
