### ISSUE TITLE
Nvidium/Acedium Rendering Issue 

### ISSUE THREAD

**Issue by bubin7766** [FiniteReality/embeddium#163]
### Bug Description

Tested with:
Prism Launcher 8.0
Minecraft 1.20.1
NeoForge 47.1.84
Sinytra Connector Beta 31
Connector Extras 1.80
Forgified Fabric API 0.90.7+1.10.3
Embeddium-0.2.13+mc1.20.1

Modified `fabric_loader_dependencies.json` in config folder containing
```
{
    "version": 1,
    "overrides": {
      "optigui": {
        "-depends": {
            "fabricloader": "IGNORED"
        }        
      },
      "nvidium": {
        "-depends":{
            "sodium": "IGNORED"
        }
      }
    }
  }
```
So i have been trying to get Nvidium to work on forge and found success earlier this week when coming across Sinytra.
The problem I encountered came when Embeddium had an update and broke rendering when Nvidium is installed.
![uhoh](https://github.com/embeddedt/embeddium/assets/42780000/50b69a31-8265-4728-a939-cbe7ef93c65d)
As you can see the world rendering broke in a way I'm not sure where the fault lies.

### Reproduction Steps

To reproduce the bug simply download the mods I tested with above and update only embeddium to reproduce the issue.
This can also be replicated with the forge port called [Acedium](https://github.com/ferriarnus/acedium/releases/tag/v0.2.4-1.20.1) and embeddium for simplicity.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13790475/latest.log)

**Comment by embeddedt** [comment]
This is a known issue and cannot be fixed on Embeddium's end; you will need to wait for Nvidium or Acedium to update (the Nvidium dev was notified of the issue).

**Comment by bubin7766** [comment]
I see, so i guess it is something on their end that can't be solved from your side of things?
If so then i guess my only option is to wait and see if they'll patch it or I stick with 0.2.13 of embeddium :/
