### ISSUE TITLE
Crash with Valkyrien Skies 1.20.1

### ISSUE THREAD

**Issue by goodfaithgaming** [FiniteReality/embeddium#164]
### Bug Description

With Valkyrien Skies 2.3.0 (Still in beta,) and Embeddium 0.2.16, (latest version of both) the game freezes up during loading, then crashes.

### Reproduction Steps

Install Valkyrien Skies 2.3.0, and Embeddium, then start Minecraft.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13798285/latest.log)
[mods.zip](https://github.com/embeddedt/embeddium/files/13798288/mods.zip)

**Comment by embeddedt** [comment]
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/580#issuecomment-1732582873
