### ISSUE TITLE
INCOMPATIBILITY: Nevermore

### ISSUE THREAD

**Issue by Busybody64** [FiniteReality/embeddium#166]
### Bug Description

https://modrinth.com/datapack/nevermore/

This datapack's resource pack doesn't render stuff right with embeddium. 

VERSION USED: 1.20.1

### Reproduction Steps

Just... Run the resource and data packs?

### Log File

There's no log files about this.

**Comment by embeddedt** [comment]
Sodium & Embeddium do not support resource packs or mods that modify Minecraft's terrain shaders, which is what Nevermore does. See https://github.com/CaffeineMC/sodium-fabric/issues/1569 and https://github.com/CaffeineMC/sodium-fabric/issues/2126 for more information.

**Comment by Busybody64** [comment]
Well, THAT sucks.
