### ISSUE TITLE
I can't disable chunk rendering by config file and because of this I can't use the nocubes mod

### ISSUE THREAD

**Issue by biaks** [FiniteReality/embeddium#168]
### Bug Description

The Nocube mod uses its renderer to make the Minecraft world without cubes. One solution would be to disable rendering from embeddium.

I'm trying to set parameter in the embeddium-mixins.properties file (previously it worked with rubidium for 1.19).
mixin.features.chunk_rendering=false
but nothing happens and the error remains.

Here is a link to the corresponding thread in the nocubes repository:
https://github.com/Cadiboo/NoCubes/issues/88

### Reproduction Steps

use nocubes and embeddium mod together with forge, put string "mixin.features.chunk_rendering=false" to embeddium-mixins.properties and try to start the game.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13851403/latest.log)

**Comment by embeddedt** [comment]
This is intended. Embeddium does not allow disabling `mixin.features.chunk_rendering` as that nullifies most of the performance improvement from the mod. You should just remove Embeddium if a mod does not support this feature.
