### ISSUE TITLE
Incompatible with TexTrue's Rubidium Options

### ISSUE THREAD

**Issue by EvanHsieh0415** [FiniteReality/embeddium#17]
Logs: https://mclo.gs/Xu9JRKD

The game crashes when I click on "Video Settings".

**Comment by embeddedt** [comment]
Same problem as #15 - mod relies on Rubidium internals.

**Comment by TexBlock** [comment]
OK, I'll make an [Embeddium-compatible branch (TexTrue's Embeddium Options)](https://github.com/ThinkingStudios/textrues-embeddium-options) later and release it as another mod!
