### ISSUE TITLE
[Question]: How can I make my mod compatible with Embedium so that animated sprites work?

### ISSUE THREAD

**Issue by 19PHOBOSS98** [FiniteReality/embeddium#170]
Hello. My mod renders blocks in a custom `World` as "Mirages". Everything works fine with Vanilla MC but when I run Embedium, blocks with animated sprite textures stop animating. They only start animating when I put down an actual block in the main world. Say I have a campfire in my Mirage. The flame only starts animating when I put a "real" campfire block in the main world.
 
I've traced the issue to this mixin:

https://github.com/embeddedt/embeddium/blob/0cb242b4b7f205c65e74c5b7eabdab8587ab25ca/src/main/java/me/jellysquid/mods/sodium/mixin/features/texture_tracking/MixinSpriteAnimation.java#L46

It seems that Embedium only checks blocks that are in the loaded chunks in the main world.
is there a way for me to passively `setActive(...)` the blocks from my custom `World`? maybe an API or something?
help would be much appreciated

**Comment by embeddedt** [comment]
We discussed this on Discord and a fix has been implemented on Embeddium's side in 0.2.18.

**Comment by 19PHOBOSS98** [comment]
thanks again!
