### ISSUE TITLE
[1.16.5] Ice showing wierdly when underwater, but not if the block is on a chunk border

### ISSUE THREAD

**Issue by MundM2007** [FiniteReality/embeddium#173]
### Bug Description

Ice doesn't render correctly when underwater, but only if the water isn't rendered through a chunk border (see screenshot)
![image](https://github.com/embeddedt/embeddium/assets/85188362/1bcf14ae-1191-4d9d-b156-e78d5d777c0c)

### Reproduction Steps

- create a new instance with forge 36.2.41 and install embeddium on 0.2.17
- start the game and enter a world
- find a frozen ocean and see the ice

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13892004/latest.log)

**Comment by embeddedt** [comment]
Enable translucency sorting in video settings.

**Comment by MundM2007** [comment]
Ok will do that, but what's the reason it isn't enabled by default?

**Comment by embeddedt** [comment]
It may reduce FPS or cause stutter.
