### ISSUE TITLE
(1.19.2 ?) Supplementaries' Colored Blackboard incompatibility 

### ISSUE THREAD

**Issue by Thresh90** [FiniteReality/embeddium#174]
### Bug Description

Testing for a server and fount out for whatever reason, the colored pixels on a blackboard do not render when Embedium is enabled.

### Reproduction Steps

1. Run both Supplementaries and Embedium (With Colored Blackboard's config set to true)
2. Place a blackboard down and try to use various colored dyes
3. Get disappointed since they don't work :(

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13925347/latest.log)

**Comment by embeddedt** [comment]
Fixed in 0.2.18
