### ISSUE TITLE
Weird shading in Little Tiles Blocks when Embeddium is installed

### ISSUE THREAD

**Issue by kazumadh** [FiniteReality/embeddium#175]
I installed Embbedium 0.2.18 MC 1.20.1, along with Little Tiles and Creative Core (latest version & no other mods installed). These pictures below show how Little Tiles blocks are shaded with/without Embeddium:
With Embeddium installed:
![2024-01-17_16 51 37](https://github.com/embeddedt/embeddium/assets/140326816/0f71a511-19ef-49be-9846-635c502b116f)
Without Embeddium installed:
![2024-01-17_16 54 39](https://github.com/embeddedt/embeddium/assets/140326816/a88603cc-3fa1-4a13-b5e4-bbd24c68dfa1)
I don't know whether this is Little Tiles's issue or Embeddium's issue. I've told Little Tiles's author to contact you if necessary.

**Comment by embeddedt** [comment]
This issue needs to be fixed on LittleTiles' end as it injects custom patches into Embeddium. I believe it is solved in the latest update.
