### ISSUE TITLE
Incompatible with Valkyrien Skies

### ISSUE THREAD

**Issue by Camawama** [FiniteReality/embeddium#179]
### Bug Description

I have just sat back and patiently waited hoping that maybe compatibility would be added between these two mods but alas, nothing has happened. I wanted to make a report for this but it seems someone else already has so I will link their report.

### Reproduction Steps

Have both mods installed
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/687

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14002298/latest.log)

**Comment by embeddedt** [comment]
Unfortunately, I cannot fix this on my end, as Valkyrien Skies is the one mixing into Sodium/Embeddium internals.

**Comment by Camawama** [comment]
https://github.com/embeddedt/embeddium/issues/189
