### ISSUE TITLE
[1.20.1] Crash while rendering any model data from @Hostile Neural Networks in JEI or in inventory.

### ISSUE THREAD

**Issue by Gbergz** [FiniteReality/embeddium#18]
`("GhostVertexBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter")`

### Versions:
MC: 1.20.1
Forge(not Neo): 47.1.3
Hostile Neural Networks: 5.1.3 | https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks/files/4711380
Placebo: 8.3.7
Embeddium: 0.1.2
JEI: 15.2.0.27
EMI: 1.0.19 (happens without too, just JEI.)

### Crash Reports
**Link with EMI:** https://gist.githubusercontent.com/Gbergz/b74cbe71a550ee87d9971a2db281dfa6/raw/c365dcc299b373197222bf974ac2d5709a3ed3f9/gistfile1.txt
**With just JEI:** https://gist.githubusercontent.com/Gbergz/41dafd9bdd1b28f49c943e8938059e3e/raw/a435640e185ce449eccd0c189b163f0aa0a1c8e0/gistfile1.txt

**Crash Report when right clicking an entity to build a data model:**
https://gist.githubusercontent.com/Gbergz/91d4a26cc9df89753aa53955d89b9ec9/raw/dd0de620d8a3781baf935535fd0aebe70f6ce6b4/gistfile1.txt

### Other info:
Rendering any data module in JEI / EMI from the Hostile Neural Networks results in a crash.

### Other:
Report originally reported here: (Which was for Rubidium initially.)
`https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/35`

**Comment by embeddedt** [comment]
None of the crash reports you attached mention Embeddium; are you sure you're using the correct instance? Your reports mention Rubidium 0.6. I looked at the code and Embeddium should already have the patch not to crash here.

**Comment by Gbergz** [comment]
Yes, I am using embeddium. It reports as Rubidium 0.7 ingame though.

**Comment by Gbergz** [comment]
Right, forgot to include the new crash report. It's the same though.
https://gist.githubusercontent.com/Gbergz/6742f540bcd4857733c0faaa761b6054/raw/bcdcd9a2eeb27ced3f6f9f2f3af9cc1ea8626d9d/gistfile1.txt

**Comment by Gbergz** [comment]
That's the wrong one. Damnit.

**Comment by Gbergz** [comment]
https://gist.githubusercontent.com/Gbergz/3c87628e7143993d5e686acff7d1886b/raw/18f96141249c7b9511898c12fa06cb811c080959/gistfile1.txt

THere.!

**Comment by embeddedt** [comment]
Thanks, I see the issue and pushed a fix, will get a release up on CF soon. In the meantime you can get the fixed version from https://github.com/embeddedt/embeddium/actions/runs/6101566847

**Comment by embeddedt** [comment]
Fixed in 0.1.3.

**Comment by Gbergz** [comment]
Works.
Thank you!
