### ISSUE TITLE
game crashes with this mod on neoforge 20.4.129+

### ISSUE THREAD

**Issue by nickademas** [FiniteReality/embeddium#181]
### Reproduction Steps

download neoforge 20.4.129 or newer and embeddium and launch the game 

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14070709/latest.log)

**Comment by embeddedt** [comment]
Known issue, it is caused by breaking changes in NeoForge. For now you can use the beta build: https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.4%2Fneoforge/Embeddium.zip

**Comment by embeddedt** [comment]
Fixed in 0.3.0
