### ISSUE TITLE
[1.20.1]Game crashes with Embeddium-0.2.18,Forge_47.2.20

### ISSUE THREAD

**Issue by Tangbelief** [FiniteReality/embeddium#182]
### Bug Description

Game crashes after click start.
Forge version:Forge_47.2.20
Embeddium version:embeddium-0.2.18
![QQ截图20240127172021](https://github.com/embeddedt/embeddium/assets/102590499/735e3dff-3322-4832-a57e-1c514f6abcab)

### Reproduction Steps

1.Click start
2.Game crashes

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14071819/latest.log)
[crash-2024-01-27_17.19.04-client.txt](https://github.com/embeddedt/embeddium/files/14071820/crash-2024-01-27_17.19.04-client.txt)

**Comment by embeddedt** [comment]
You probably have MSI Afterburner or similar software installed. It includes something called RivaTuner Statistics Server, which is [not compatible with Sodium](https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible).
