### ISSUE TITLE
Chunks not loading

### ISSUE THREAD

**Issue by JART0N** [FiniteReality/embeddium#183]
### Bug Description

When Better Chunk Loading is installed, the chunks load slower and slower until they stop loading at all.

### Reproduction Steps

Install Embeddium along side better chunk loading, the glitch will take place

### Log File

Problem does not create crash.

**Comment by embeddedt** [comment]
This does not sound like an Embeddium bug. Chunks will render slower if the game needs more time to generate them first.

**Comment by ItsRileyNJ** [comment]
Happening to me as well. Also getting error code 1 with Embeddium installed but both issues stop when I take it out.

**Comment by DigitalWendigo** [comment]
If you have a mod called Better Chunk Loading, try running a new world without it and only embeddium installed. 
Recently discovered it is incompatible with Embeddium in some way, that outright breaks chunk loading.

**Comment by JART0N** [comment]
That helps a lot, THANKS

**Comment by embeddedt** [comment]
A note has been added to the compatibility page that having Better Chunk Loading installed may cause chunks to not load.
