### ISSUE TITLE
Compatibility with Conquest Resource Pack

### ISSUE THREAD

**Issue by Aabaddon** [FiniteReality/embeddium#185]
### Request Description

it is impossible to use one of the best resource packs with embeddium installed, it makes the whole game crash as soon as i load the world

im trying to use Conquest 1.20.1

**Comment by embeddedt** [comment]
If you are referring to https://conquestreforged.com/conquest-pack, it works fine in a standalone instance with Embeddium for me.

**Comment by Aabaddon** [comment]
im referring to https://www.curseforge.com/minecraft/texture-packs/conquest_ not the 1.18 modpack but the texture pack for 1.20.1

**Comment by embeddedt** [comment]
It is the same thing, the file sizes & names are identical.

**Comment by Aabaddon** [comment]
yeh but it just works without embeddium and not with it for some reason... atleast for me, maybe is an incompatibility that happens when combined with other mods i dont know, ill check

**Comment by Aabaddon** [comment]
seems like it was a problem with having clouds on, when turning them off it works with embeddium too, sorry
