### ISSUE TITLE
not a valid file

### ISSUE THREAD

**Issue by mmmthepotatogod** [FiniteReality/embeddium#186]
### Bug Description

launched the latest version of the mod, [1.20.4] Embeddium 0.3.0 with some other mods. it did not go smoothly at all.

### Reproduction Steps

use the following mods:
appleskin
freecam
cloth config
collective
fullbrightnesstoggle
immediatly fast
jade
jei
mousetweaks
redirector
shulker tooltips
xaeros worldmap + minimap

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14111807/latest.log)

**Comment by embeddedt** [comment]
Embeddium versions for 1.20.4 and newer are only targeting NeoForge, not Minecraft Forge.

**Comment by mmmthepotatogod** [comment]
Got it, my bad 😅
