### ISSUE TITLE
crash lastest version 1.20.1

### ISSUE THREAD

**Issue by Aabaddon** [FiniteReality/embeddium#188]
### Bug Description

lastest version crashes... idk with what

[crash-2024-01-31_18.57.43-client.txt](https://github.com/embeddedt/embeddium/files/14118693/crash-2024-01-31_18.57.43-client.txt)

### Reproduction Steps

try to use lastest embeddium

### Log File

the log is up there

**Comment by embeddedt** [comment]
Because Oculus depends on Embeddium internals, it needs an update to work with Embeddium 0.3, this is not a bug on our end. Remove Oculus or downgrade to 0.2.18 for the time being.

**Comment by 0Navis0** [comment]
This issue has already been reported to Occulus, but they blame Embeddium for it.
https://github.com/Asek3/Oculus/issues/539

**Comment by Aabaddon** [comment]
> Because Oculus depends on Embeddium internals, it needs an update to work with Embeddium 0.3, this is not a bug on our end. Remove Oculus or downgrade to 0.2.18 for the time being.

yeh, oculus says this error is on your side :/
