### ISSUE TITLE
1.20.1 Valkyrien skies, and Clockwork do not work with embeddium 

### ISSUE THREAD

**Issue by jojofenin99** [FiniteReality/embeddium#189]
### Bug Description

The game says some injection fails in the logs after crashing

### Reproduction Steps

get Valkyrien skies , create, clockwork, and kotlin, with Architectury

### Log File

[2024-01-31-2.log](https://github.com/embeddedt/embeddium/files/14119421/2024-01-31-2.log)
[crash-2024-01-31_21.09.25-client.txt](https://github.com/embeddedt/embeddium/files/14119423/crash-2024-01-31_21.09.25-client.txt)

**Comment by embeddedt** [comment]
Valkyrien Skies injects into Embeddium internals, they need to fix this on their end.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/687
