### ISSUE TITLE
Using embeddium can lead to errors in the bushy leaves texture of stay true resourcepack

### ISSUE THREAD

**Issue by Kyuringo** [FiniteReality/embeddium#190]
### Reproduction Steps

![image](https://github.com/embeddedt/embeddium/assets/98072867/abe02149-6d95-4981-8764-65fff85f668c)
when using rubidium it's correct

### Log File

[2024-02-01-1.log.gz](https://github.com/embeddedt/embeddium/files/14126525/2024-02-01-1.log.gz)

**Comment by Kyuringo** [comment]
my version is 1.18.2

**Comment by embeddedt** [comment]
Please fill out the issue template properly. Have you tried to reproduce this with minimal mods? What are the steps to reproduce?

**Comment by Kyuringo** [comment]
> Please fill out the issue template properly. Have you tried to reproduce this with minimal mods? What are the steps to reproduce?

I only used embeddium, but it still works like this.

**Comment by embeddedt** [comment]
Happens in vanilla as well for me when using Fast graphics. Fancy works fine though. Stay True's FAQ mentions that you should use Fancy for leaves to look correct.

![image](https://github.com/embeddedt/embeddium/assets/42941056/162f585a-6842-42ad-86db-e00dcfd9e75a)

**Comment by embeddedt** [comment]
Closing as I don't think this is a bug in Embeddium.
