### ISSUE TITLE
Problems rendering Psychedelicraft visual effects

### ISSUE THREAD

**Issue by AuxCat** [FiniteReality/embeddium#191]
### Bug Description

When running Psychedelicraft with Forgified Fabric API and Connector alongside Embeddium, some of the visual effects fail to render. This is noticable especially when eating the Magic Mushrooms. The ground warping effects seem to be affected the most, and sometimes the screen will lock in place or go black for a few seconds.. I tried installing Lazurite, but it didn't seem to make a difference. Without Embeddium, the effects work just fine.  This has also been reported as an issue for Psychedelicraft with Sodium running on Fabric (non-Forge).

Without Embeddium
![2024-02-02_00 44 51](https://github.com/embeddedt/embeddium/assets/158538836/cd283dce-6be3-484f-a99e-8fe85ca9e954)

With Embeddium
![2024-02-02_01 02 25](https://github.com/embeddedt/embeddium/assets/158538836/cdde7eaa-93b5-4ed2-9983-9401a03010c7)

### Reproduction Steps

1. Install Psychedelicraft, along with the required Forgified Fabric and Sinytra Connector. Leave out Embeddium.
2. Eat some Magic Mushrooms and observe the effects.
3. Install Embeddium and eat some mushrooms again.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14137855/latest.log)

**Comment by embeddedt** [comment]
Embeddium doesn't officially support Connector - the vast majority of mods work, but two modloaders is a lot of work for one developer. This will probably need to be fixed on Psychedelicraft's end, especially if it also occurs with Sodium.
