### ISSUE TITLE
Quark Conflicting w/ Embeddium 1.20.1

### ISSUE THREAD

**Issue by CodeGiver01** [FiniteReality/embeddium#194]
### Bug Description

Quark is crashing on Forge 1.20.1 with Zeta on my modpack on ATLauncher.
Notable mods include Sinytra Connector w/ Forgified Fabric, Modernfix, Embeddium w/ Lazurite, Dynamic Lights Reforged.

### Reproduction Steps

1. Install Embeddium w/ Addons and Quark w/ Zeta.
2. Start the game and create a world.
3. Once the world finishes creating at 100%, the game crashes.

### Log File

Log: https://paste.ee/p/0VxpF
[latest.log](https://github.com/embeddedt/embeddium/files/14143807/latest.log)

**Comment by embeddedt** [comment]
Some addons (e.g. Rubidium Extra) need to be updated to support Embeddium 0.3.

**Comment by CodeGiver01** [comment]
good to know
