### ISSUE TITLE
0.3.1 broke compatibility with bendy-lib

### ISSUE THREAD

**Issue by NeuTraLZero** [FiniteReality/embeddium#196]
### Bug Description

Entity rendering optimization port broke limb bending features with bendy-lib. When playing emotes from Emotecraft, the limbs will not visually bend

This is what it should looks like (Embeddium 0.3.0):
![image](https://github.com/embeddedt/embeddium/assets/43245485/3bc420de-659c-47f3-af44-2103908d8f86)

And this is what it looks like after (Embeddium 0.3.1):
![image](https://github.com/embeddedt/embeddium/assets/43245485/a739d471-5cd4-4013-b874-02dec08b993f)

### Reproduction Steps

1. Install mods on Forge 1.20.1: Embeddium 0.3.1, playerAnimator 1.0.2-rc1, bendy-lib 4.0.0
2. Find and download any Emotecraft emote that bends the limbs from https://emotes.kosmx.dev/e
3. Play the emote in-game

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14151239/latest.log)

**Comment by embeddedt** [comment]
I've disabled the problematic optimization for now if bendy-lib is installed, the [beta](https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip) should work around the issue till I release 0.3.2.

**Comment by Dd00nn** [comment]
same problem on 0.3.7

**Comment by Sgujenka** [comment]
0.3.12 still have this problem
