### ISSUE TITLE
not able to render clips with replay mod in forge(sinytra connector) because embeddium not having "FREX flawless frames API" 

### ISSUE THREAD

**Issue by Molonalte** [FiniteReality/embeddium#197]
### Bug Description

I can't render clips in replay mod using forge with sinytra and embeddium because replay mod says that embeddium doesn't have FREX flawless frames api, do you know a way to resolve this? Thanks in advance, stay safe!

### Reproduction Steps

![embeddium with replay mod](https://github.com/embeddedt/embeddium/assets/91741863/598799e0-0c9e-4e1c-943d-b9c1e3300518)

### Log File

there is no log just im unable to press render in replay mod editor

**Comment by Molonalte** [comment]
By the way all latest versions of mods in 1.20.1 and sorry for the trouble :(, hope you can tell me something about it.

**Comment by embeddedt** [comment]
As mentioned on the [compatibility page](https://github.com/embeddedt/embeddium/wiki/Compatibility#fabric-mods-sinytra-connector) Embeddium does not officially support running alongside Fabric mods (even though many work) as it is not identical to Sodium internally.

**Comment by Molonalte** [comment]
Well thanks I guess
