### ISSUE TITLE
1.20.1 Vivecraft incompatibility

### ISSUE THREAD

**Issue by Daldwin** [FiniteReality/embeddium#198]
### Bug Description

Game crashes on launch when Vivecraft 1.1.5 and Embeddium 0.3.1 are used together on minecraft 1.20.1 with forge 47.2.0 .
(crash doesn't happen with rubiddium)

### Reproduction Steps

install minecraft 1.20.1
install forge 47.2.0
install vivecraft 1.1.5
install embeddium 0.3.1
launch minecraft

### Log File

[crash-2024-02-06_13.32.07-client.txt](https://github.com/embeddedt/embeddium/files/14179552/crash-2024-02-06_13.32.07-client.txt)
[debug.log](https://github.com/embeddedt/embeddium/files/14179553/debug.log)
[latest.log](https://github.com/embeddedt/embeddium/files/14179554/latest.log)

**Comment by embeddedt** [comment]
ViveCraft is accessing internal Sodium classes [here](https://github.com/Vivecraft/VivecraftMod/blob/471f2151e904d629c22b144cbaa4925ea0bad75b/common/src/main/java/org/vivecraft/mod_compat_vr/sodium/SodiumHelper.java#L41-L70); this needs to be fixed on their end.
