### ISSUE TITLE
crashes when used with physics mod pro

### ISSUE THREAD

**Issue by gitguette** [FiniteReality/embeddium#20]
after joining a world or server with the physics mod, the game crashes.
log: [https://mclo.gs/MuZRYqG](https://mclo.gs/MuZRYqG)

**Comment by embeddedt** [comment]
The mod is calling an internal Sodium API; I think it will need to be updated on their end. I could fix this specific issue from my end but given the amount of custom rendering Physics Mod does, it's likely other changes might be required as well.

**Comment by ColonelGerdauf** [comment]
I wonder if this is a matter of mismatching Sodium version support between Embeddium and Rubidium.
