### ISSUE TITLE
incompatible with customizable player models.

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [FiniteReality/embeddium#202]
### Bug Description

"Embeddium made a breaking change into skull rendering, downgrade to 0.3.0" -quote from other page

### Reproduction Steps

use embeddium with customizable player models, crash upon joining a world.

### Log File

https://github.com/tom5454/CustomPlayerModels/issues/560 contains log

**Comment by tom5454** [comment]
Fixed in latest CPM.
