### ISSUE TITLE
Possible incompatibility with Better FPS Render Distance. + Feature Suggestion. 1.19.2

### ISSUE THREAD

**Issue by DigitalWendigo** [FiniteReality/embeddium#203]
### Bug Description

Firstly, the bug. 
There seems to be some kind of incompatibility between Better FPS Render Distance(https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance), and Embeddium, with the likelyhood of Pluto and Canary also being involved. 
When using all together, quick ascending and decending in an area will eventually render some chunks seethrough, as if they are no longer loading. Breaking or placing a block in the affected seethrough area will fix the issue. Removing Better FPS Render Distance fixes the issue entirely. 
Screenshots:
![2024-02-11_15 09 13](https://github.com/embeddedt/embeddium/assets/103202053/f7a502b5-4cc1-49a8-bac9-fe1aa03d8d9d)
 (This is almost similar to the issue #183, #144 and #193, which was also caused by a mod by the same mod author as Better FPS Render Distance.)

Second, the suggestion. 
The aforementioned mod helps a lot in keeping the world size relatively smaller when exploring new chunks. 
Ideally I would like to keep the mod for this reason, but with visual glitches like this, it becomes undesireable. 
As such, would it be possible to implement something similar into Embeddium? 
The aforementioned mod's code is closed source, so I imagine it might be incredibly difficult and annoying to fix the issue.
So maybe implementing a similar functionality to Embeddium, which can be toggled on or off, may be an alternative? 

Again, thanks for your hard work! 

### Reproduction Steps

1. Install Better FPS Render Distance by Moreaddon, alongside Embeddium and its addons. 
1.1. Aditionally, install Pluto, Canary, and Memmory Leak Fix. (These are optional, since it had one instance of it ahppening with just Embeddium+addons, and Better FPS Render Distance, but using all the mentioned mods increased the rate at which it happened.) 
2. Quickly ascend and decend along the Y axis, sometimes several times in quick succession. 
3. Observe chunks becoming transparent, with some chunks only becoming partially transparent. 

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14232445/latest.log)
[debug.log](https://github.com/embeddedt/embeddium/files/14232446/debug.log)

**Comment by embeddedt** [comment]
This bug should be reported to them because they [directly inject into Embeddium](https://github.com/someaddons/betterfpsdistances/blob/1.19.2/src/main/java/com/betterfpsdist/mixin/Sodiummixin.java)'s chunk renderer to implement the feature; it's unlikely we can do anything on our end.

We might consider adding this as a built-in feature in the future.

**Comment by DigitalWendigo** [comment]
I'll make a report on their mod page regarding the issue then. 
I had already suspected you wouldn't be able to do anything about it on your end, so it's all good! 
Just wanted to point it out in case similar issues arise again, so one knows where to look and make your debugging easier in the long run. 

Looking forward to the new feature! 
Cheers!

**Comment by embeddedt** [comment]
Thanks for the heads-up! :+1:
