### ISSUE TITLE
Embedium 0.3.2 complains oculus 1.6.15 isnt installed when it is

### ISSUE THREAD

**Issue by lolpowerluke** [FiniteReality/embeddium#205]
### Bug Description

![image](https://github.com/embeddedt/embeddium/assets/47672899/4d72a401-32c5-4d6a-83d2-470f90a3bc28)

### Reproduction Steps

have embedium and oculus installed (neoforge, but I dont think that matters)

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14251052/latest.log)

**Comment by lolpowerluke** [comment]
Also, on curseforge, 1.6.15 is the latest version, so I cant update it any higher
https://www.curseforge.com/minecraft/mc-mods/oculus/files/all?page=1&pageSize=20&showAlphaFiles=show

**Comment by embeddedt** [comment]
Works as intended, Oculus needs to release an update on 1.20+ (as mentioned in the changelog).
