### ISSUE TITLE
my game crashes with this mod randomly in a server

### ISSUE THREAD

**Issue by jojofenin99** [FiniteReality/embeddium#21]
[crash-2023-09-08_23.27.38-client.txt](https://github.com/embeddedt/embeddium/files/12564513/crash-2023-09-08_23.27.38-client.txt) :there is the crash log and here is the log: 
[latest.log](https://github.com/embeddedt/embeddium/files/12564517/latest.log)

**Comment by embeddedt** [comment]
Duplicate of #20.
