### ISSUE TITLE
Mod embeddium only supports oculus above 1.6.15  Currently, oculus is 1.6.15

### ISSUE THREAD

**Issue by Da2ndDimension** [FiniteReality/embeddium#210]
### Bug Description
I Been troubleshooting minecraft since yesterday and these two seem to not like each other, Idk why embeddium is not reading the corrent mod version when it is?

curseforge/minecraft/Instances/New Modpack/mods/embeddium-0.3.3+mc1.20.1.jar
	Failure message: Mod embeddium only supports oculus above 1.6.15
		Currently, oculus is 1.6.15
	Mod Version: 0.3.3+mc1.20.1

### Reproduction Steps

Have Oculus 1.6.15 and Embeddium 0.3.3

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14274079/latest.log)

**Comment by glea94** [comment]
Yes error in the log, ctd
[11:53:33] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Unsupported installed optional dependencies:
	Mod ID: 'oculus', Requested by: 'embeddium', Expected range: '(1.6.15,)', Actual version: '1.6.15'
i get the version but i don't get the version..🤔

**Comment by embeddedt** [comment]
https://github.com/embeddedt/embeddium/issues/209#issuecomment-1942293337

**Comment by Leshka7777** [comment]
https://securelogger.net/files/7e351a40-b6b0-464d-afb7-2c5537ba8491.txt

**Comment by Leshka7777** [comment]
https://securelogger.net/files/7e351a40-b6b0-464d-afb7-2c5537ba8491.txt смотрите что у меня, помогите решить проблему
