### ISSUE TITLE
Help for a fan who doesn't have 100% knowledge of Java.

### ISSUE THREAD

**Issue by Hir0DF** [FiniteReality/embeddium#211]
### Request Description

Your mod is very good and recently I've been playing on pojavlauncher, which is a Mine Java launcher for cell phones, I just found problems with embeddium and its addons, but let's just focus on embeddium, Minecraft starts, but it always crashes when entering a world or server, in itself it's a limitation of being on a cell phone, but there is a way to fix it, but I don't have that much knowledge in Java to understand the error, I'm not asking for a fix, but at least some guidance from my seniors so that I can fix the mod for the Pojav and share with everyone in the community who love your mod, but can't use it, I'll attach the crash report.
[crash-2024-02-15_19.25.22-client.txt](https://github.com/embeddedt/embeddium/files/14303287/crash-2024-02-15_19.25.22-client.txt)

**Comment by embeddedt** [comment]
Sorry, but we can't provide support for Pojav as the GPU drivers on phones tend to be incomplete/buggy when they need to emulate PC rendering.

Sodium [has the same policy](https://github.com/CaffeineMC/sodium-fabric/issues/1916).
