### ISSUE TITLE
Mythic Botany - Alfheim dimension is completely black

### ISSUE THREAD

**Issue by vgrynch** [FiniteReality/embeddium#214]
### Request Description

(
Asking it here because the mod author insists on not fixing issues related to custom renderers...
Just in a hope this can be easily improved
)
Mod: https://www.curseforge.com/minecraft/mc-mods/mythicbotany
Observed:
It is completely dark
Expected:
It is at least playable (no complete darkness).

Also, I do not insist on making it's custom skies with planets working. But would be good to have it too :) .

**Comment by embeddedt** [comment]
Which Minecraft version?

**Comment by vgrynch** [comment]
1.19.2
but...
Sorry. my bad, it's a different mod collision issue: for some reason, I have got infinite blindness. Closing...
