### ISSUE TITLE
Shimmer Crashes on newer versions of Embeddium

### ISSUE THREAD

**Issue by Camawama** [FiniteReality/embeddium#215]
### Bug Description

Shimmer and Embeddium 0.2.18 worked perfectly fine but after updating to 0.3.0 and above, it crashes when joining a world.

### Reproduction Steps

Install latest version of Shimmer
Install Embeddium 0.3.0 and up

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14320719/latest.log)

**Comment by embeddedt** [comment]
This needs to be reported to Shimmer, as they are injecting into Embeddium internals, which had to be changed in 0.3 to fix a bug.
