### ISSUE TITLE
ModelParts that are rendered with non-entity render type (for example text) cause crash when oculus shaders are enabled.

### ISSUE THREAD

**Issue by FINDERFEED** [FiniteReality/embeddium#216]
### Bug Description

I have a java model exported from blockbench or created with LayerDefinition. When it is being rendered through render method (then calling renderToBuffer from ModelPart) minecraft crashes with RuntimeException: Source format is missing element TANGENT as required by destination format. 
Render code: https://github.com/FINDERFEED/SolarCraftRepository/blob/4c18c28019ebbe446c96a383f11d7c67db6197db/src/main/java/com/finderfeed/solarcraft/content/blocks/solar_forge_block/SolarForgeBlockEntityRenderer.java#L59

Setting the render type to any entity-render-type (entityCutoutNoCull for example) fixes the issue but it should work for every render type like text which i use. (rubidium didn't have that issue)

### Reproduction Steps

How to reproduce with Solar Craft mod: Enable any shaders and place Solar Forge block and you get a crash.
How to reproduce without: Create a model part and render it with RenderType.text() in entity/block entity renderer and you get a crash.

### Log File

[debug-4.log](https://github.com/embeddedt/embeddium/files/14323872/debug-4.log)
[crash-2024-02-18_21.25.35-client.txt](https://github.com/embeddedt/embeddium/files/14323883/crash-2024-02-18_21.25.35-client.txt)

**Comment by embeddedt** [comment]
If this only happens with shaders enabled it should be reported to Oculus. TANGENT isn't an element type in Embeddium.

**Comment by FINDERFEED** [comment]
Yep it happens only when shaders are enabled. Okay, i will report it to Oculus then.
