### ISSUE TITLE
1.16.5  CCmod monitor bug

### ISSUE THREAD

**Issue by iamsoNewBee** [FiniteReality/embeddium#218]
### Bug Description

![image](https://github.com/embeddedt/embeddium/assets/98573273/f04893d7-ac3f-4bd9-b52f-5fad6ccbf172)
when shader is on,monitor become like this

### Reproduction Steps

.

### Log File

.

**Comment by embeddedt** [comment]
This should be reported to Oculus; Embeddium does not include built-in shader support.
