### ISSUE TITLE
Embeddium corrupts Resource Packs with Connected Texture Blocks

### ISSUE THREAD

**Issue by kazumadh** [FiniteReality/embeddium#219]
I installed Vanilla Tweaks Resource Pack with Connected Texture. When I install Embeddium, the texture of the blocks having Connected Texture get corrupted. In this video, I placed down iron blocks to form a line to make them connected, you can see the texture of the iron blocks keep flickering. 
Embeddium 0.3.4 Minecraft Forge 47.2.20 1.20.1
https://github.com/embeddedt/embeddium/assets/140326816/84600e2d-9cde-4434-adc5-64dafa9a5e23

**Comment by embeddedt** [comment]
Try disabling the Compact Vertex Format in video settings.

**Comment by kazumadh** [comment]
I disabled it, but nothing happens

**Comment by embeddedt** [comment]
You can't disable it with Oculus installed (it looks disabled in settings, but is actually enabled, this is a bug I need to get around to fixing at some point).

**Comment by kazumadh** [comment]
thanks

**Comment by betterworld-sjq** [comment]
> You can't disable it with Oculus installed (it looks disabled in settings, but is actually enabled, this is a bug I need to get around to fixing at some point).

Sir, mine is still not working. My CTM feature is achieved with a fabric mod Continuity with Sinytra Connector running on forge. Would you mind taking a look somehow? Great gratitude to you!

**Comment by embeddedt** [comment]
I believe you need Lazurite installed as well.

**Comment by betterworld-sjq** [comment]
> I believe you need Lazurite installed as well.

Thanks!

**Comment by embeddedt** [comment]
Closing as the issue is solvable with a config change and the root cause is not something we can easily fix.

**Comment by embeddedt** [comment]
A potential fix for Vanilla Tweaks packs was added to release 0.3.12, for the record.
