### ISSUE TITLE
Will make Create's Cogwheel and Shaft animations disappear

### ISSUE THREAD

**Issue by theabab2333** [FiniteReality/embeddium#22]
![QQ图片20230909150313](https://github.com/embeddedt/embeddium/assets/102858947/efb81802-74c9-4d11-9814-06549dbf200e)
在之前我使用的是铷，是正常显示的，但是换了embeddium之后会出现图片中大齿轮动画消失的情况，抽象放置齿轮、传动杆动画和重新出现

**Comment by embeddedt** [comment]
Duplicate of #14.
