### ISSUE TITLE
[1.20.1] Invisible bubble blocks when using Supplementaries and Embeddium

### ISSUE THREAD

**Issue by vukkax** [FiniteReality/embeddium#221]
### Bug Description

The title says it all, latest version of Forge, Supplementaries, Moonlight and Embeddium.
![imagen_2024-02-22_151043196](https://github.com/embeddedt/embeddium/assets/108903683/7fcfa045-ef7a-49d9-bfa4-60c4375c3fe3)
(there are bubble blocks in the picture, not only they are invisible they make water seethrough as well)

### Reproduction Steps

1.  Start Minecraft with Embeddium, Supplementaries and Moonlight.
2.  Place bubble block.
3.  Visual bug happens.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14374979/latest.log)

**Comment by vukkax** [comment]
Already reported this issue in the Supplementaries discord and MehVahdJukaar told me it was not their issue.

**Comment by embeddedt** [comment]
They do cause water to disappear behind them without Embeddium as well.

![image](https://github.com/embeddedt/embeddium/assets/42941056/d081e49b-5d80-4b6a-9177-c6b690d40ce1)


However, the texture not appearing is indeed a bug.

**Comment by embeddedt** [comment]
Fixed in 0.3.5
