### ISSUE TITLE
Cave's images not shown properly in the Cave Compendium with Embedium installed

### ISSUE THREAD

**Issue by Vinzound** [FiniteReality/embeddium#222]
### Bug Description

https://github.com/AlexModGuy/AlexsCaves/issues/808

As the title says, the images that appear in the Alex's Caves Compedium do not appear correctly if we have Embeddium installed, in the link that I shared there are more details about it with a video example.

### Reproduction Steps

By simply opening the Alex's Caves Compedium with Embeddium installed as well, you will be able to see the visual glitch.
https://github.com/AlexModGuy/AlexsCaves/assets/150374817/62b67f9f-2411-4bbe-8aa6-23fc4bae811b

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14394848/latest.log)

**Comment by embeddedt** [comment]
Fixed in 0.3.6
