### ISSUE TITLE
Please do a 1.20.4 Release for Forge.

### ISSUE THREAD

**Issue by GitCodMaster** [FiniteReality/embeddium#223]
### Request Description

Because **canary and saturn **don't have neoForge**** versions. and i would really be happy😁😁.

**Comment by embeddedt** [comment]
Unfortunately, we currently don't plan to support the original Minecraft Forge past 1.20.1 as most content mods are expected to move to NeoForge in the next major modding version. We'll reevaluate when the time comes but for now we're only targeting Fabric & NeoForge.
