### ISSUE TITLE
[1.20.1][Possibly Unrelated] Getting a weird light glitch.

### ISSUE THREAD

**Issue by VOLKOUL** [FiniteReality/embeddium#224]
### Bug Description

The reason for reporting this here is that I updated Embeddium (along with a few other mods) and I haven't observed such glitches before doing so. It is possible that Embeddium has nothing to do with it, but it seems like the most viable candidate. Ooor perhaps it's just a rare Minecraft thing...

![2024-02-25_22 02 54](https://github.com/embeddedt/embeddium/assets/97387920/4e910611-574d-4c16-b803-b08cea5a41f4)

### Reproduction Steps

S E A R C H
S E E K
O B S E R V E 
I D K

### Log File

https://mclo.gs/5cBCTyQ (I advise you to not even take a look at it. I warned you, there is a LOT of stuff there)

**Comment by VOLKOUL** [comment]
Could be Physics Mod, as it happened with sand that was suspended in the air.

**Comment by VOLKOUL** [comment]
If you confirm that it is most likely unrelated I'll close the issue

**Comment by embeddedt** [comment]
At first glance it looks like the effect you get if a mod was updated and removed some blocks (the spot where they used to be becomes air with light level 0, so it looks similar to this). I don't know how Embeddium would cause it specifically.

**Comment by VOLKOUL** [comment]
I had generated a new world, so it's not that probably. Anyway, thanks for your assessment!
