### ISSUE TITLE
Force-disabling mixin [NVIDIA_THREADED_OPTIMIZATIONS] 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [FiniteReality/embeddium#226]
### Bug Description

- Embeddium-0.3.7+mc1.20.1.jar
- Oculus-mc1.20.1-1.6.15a.jar
- Rubidium-extra-0.5.4.1+mc1.20.1-build.117.jar
- Embeddiumplus-1.20.1-v1.2.4.jar
- ImmediatelyFast-Forge-1.2.10+1.20.4.jar
- Textrues_embeddium_options-0.1.5+mc1.20.1.jar

https://gist.github.com/Krimatoria/ac7911402776720365e2ef8af6ca6bf2 - Log File
It turns out that this is a global problem. Oculus disables some functions.
I just hope that this will somehow help solve these errors.

1. Force-disabling mixin 'features.render.world.sky.
2. Force-disabling mixin 'features.render.gui.font
3. Force-disabling mixin 'features.render.entity.shadows.
4. Force-disabling mixin 'features.render.entity.fast_render
5. Force-disabling mixin 'features.render.entity.cull

Since the problem is old, in order not to duplicate the mention of branches, I just added them all via the link from Oculus that I could find with similar problems. There's a link to my problem with oculus in general, it's the same for Embeddium, just so that you can look at it and maybe find a solution.

1. https://github.com/Asek3/Oculus/issues/570 

### Reproduction Steps

I have described all the errors and the ways they occur in the link and in the paragraphs above. The prince is simple. When starting the world, I get these errors in the logs when the Oculus turns off some of the Embeddium functions

### Log File

https://gist.github.com/Krimatoria/ac7911402776720365e2ef8af6ca6bf2

**Comment by embeddedt** [comment]
It is normal for Iris/Oculus to disable some mixins from Embeddium; those mods reimplement the same functionality with patches for shader support.

The rest of the messages from Embeddium are just warnings and can be ignored.

The rest of the messages from Iris are warnings generated about the current shader pack and can usually be ignored, but I am not familiar enough with shaders to give any more specific advice.

**Comment by Krimatoria** [comment]
> Для Iris/Oculus нормально отключать некоторые миксины из Embeddium; эти моды переопределяют ту же функциональность с исправлениями для поддержки шейдеров.
> 
> Остальные сообщения от Embeddium являются просто предупреждениями и их можно игнорировать.
> 
> Остальные сообщения от Iris — это предупреждения о текущем пакете шейдеров, и их обычно можно игнорировать, но я недостаточно знаком с шейдерами, чтобы давать какие-либо более конкретные советы.

Thanks)
