### ISSUE TITLE
[1.20.1][Connector] Nvidium doesn't seem to work anymore. 

### ISSUE THREAD

**Issue by VOLKOUL** [FiniteReality/embeddium#227]
### Bug Description

Hi! This issue might be unrelated to Embeddium and may be caused by Connector (in that case I am sorry for reporting this here). I noticed that Nvidium doesn't work anymore. Previously, I managed to make Nvidium work on Forge/NeoForge by following the steps listed below. It used to work perfectly fine, giving me an absolutely huge fps boost and render distance, until I updated a few mods. I just don't know whether an Embeddium or Connector update broke it. (or... something else, though it seems unlikely to be caused by anything other than these two)

### Reproduction Steps

**To run Nvidium using Connector, follow these steps:**

![Screenshot (934)](https://github.com/embeddedt/embeddium/assets/97387920/47f7f6de-9c60-46b7-9cc4-650ee48ed732)

### Log File

It's uhhh, pretty messy: https://mclo.gs/R46kLNt

**Comment by embeddedt** [comment]
Please ask for help in the Connector Discord server; we don't officially support using Sodium add-ons through Connector.

**Comment by VOLKOUL** [comment]
FIXED! Had to update config format.
