### ISSUE TITLE
Port to old versions

### ISSUE THREAD

**Issue by seriousfreezing** [FiniteReality/embeddium#230]
### Request Description

I know it would be a huge job to port this mod to older versions, but it would be a great feature to have a Sodium for older versions, like 1.12.2

**Comment by Kasualix** [comment]
https://github.com/Asek3/sodium-1.12

**Comment by embeddedt** [comment]
Embeddium will not be backported to anything older than 1.16 (unless I have personal interest in doing it for fun). The repo linked above is a WIP port to 1.12 and https://github.com/GTNewHorizons/Angelica/ exists for 1.7.10.
