### ISSUE TITLE
[1.16] Biomes render as if in 1.18, leading to strange artifacts

### ISSUE THREAD

**Issue by K-2SAMO** [FiniteReality/embeddium#231]
### Bug Description

![2024-03-13_23 31 19](https://github.com/embeddedt/embeddium/assets/163368859/b6c8752e-412c-48e3-8a63-64167608fbad)
When I swapped from Optifine to Rubeddium and finally to Embeddium, I saw this visual glitch appear in my world edited warm ocean biome. The ocean should look normal and not checkered as I did not make it like that. I am sure that no other mods are causing this because I have never seen this issue before and it doesn't fix itself when closing an opening MinceCraft. I am in version 16.5

### Reproduction Steps

Make a normal ocean biome into a warm ocean and put cold ocean areas along the border. Have optifine at first, then rubbidium and end off with embeddium to see the visual glitch.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14596382/latest.log)

**Comment by embeddedt** [comment]
There are a lot of mods installed. Does it occur in a standalone instance with just Embeddium? If not, please narrow down what mod causes the issue. In the past, mods that hack the biome system to backport cave biomes have been known to cause this. I think Better End might also manipulate water color.

**Comment by K-2SAMO** [comment]
![2024-03-17_11 19 40](https://github.com/embeddedt/embeddium/assets/163368859/40e41f9a-3a2b-4c81-9f8a-d39b3f7a2da1)
Ok so I did the issue by just making a modpack with world edit, better end, and embeddium. Made a warm ocean, joined and rejoined the world and saw the bug.
[latest.log](https://github.com/embeddedt/embeddium/files/14627891/latest.log)

**Comment by K-2SAMO** [comment]
I just removed better end and the bug is still there, so it must be an embeddium issue.

**Comment by embeddedt** [comment]
The edited region looks normal enough to me...

![2024-03-17_11 37 23](https://github.com/embeddedt/embeddium/assets/42941056/2a25adae-56c2-43d1-a98f-9a4653d39aa2)

**Comment by K-2SAMO** [comment]
Try a larger area maybe, also I removed embeddium dynamic lighting and the issue is still there.

**Comment by embeddedt** [comment]
Can you send a small world file (with the broken ocean already present) in which I can reproduce the issue?

**Comment by K-2SAMO** [comment]
Sure I will. I removed embeddium and the issuewas no longer present. I redownloaded it again and the bug appeared.

**Comment by K-2SAMO** [comment]
How do I send the world :(

**Comment by embeddedt** [comment]
Compress it in a ZIP file and drag it here.

**Comment by K-2SAMO** [comment]
New World (file://LAPTOP-3NTBFNKD/Users/soray/curseforge/minecraft/Instances/Embedium%20bug%20test/saves/New%20World)

**Comment by K-2SAMO** [comment]
New World (file://LAPTOP-3NTBFNKD/Users/soray/curseforge/minecraft/Instances/Embedium%20bug%20test/saves/New%20World)
 see if this works, sorry for the issues, ive never done this before.

________________________________

**Comment by K-2SAMO** [comment]
[New World.zip.zip](https://github.com/embeddedt/embeddium/files/14628822/New.World.zip.zip)
Okay I did it properly finally!!!

**Comment by embeddedt** [comment]
Fixed in 0.3.12, thanks.
