### ISSUE TITLE
Prevent enabling translucency sorting with Nvidium present

### ISSUE THREAD

**Issue by Matthysse** [FiniteReality/embeddium#233]
### Request Description

Weird feature request and very specific, but it would be handy if translucent sorting from Embeddium would automatically disable itself when Nvidium is enabled (when in mod list AND enabled because no shader is laoded). That would mean I could just include Nvidium in a private modpack and therefore people with non-nvidium-compatible hardware would still have translucent sorting from Embeddium.  Right now, this isn't possible because one of the translucent sortings must be disabled manually each time as when both are enabled, of course it breaks translucency.

**Comment by LittleChest** [comment]
I use fabric for the same needs, no need to check for the presence of connector

**Comment by embeddedt** [comment]
This has theoretically been implemented in the latest [beta build](https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip), but I don't have the hardware to test it with Nvidium. Feedback would be appreciated.

**Comment by embeddedt** [comment]
@Nolij was able to confirm this works; it has been released with 0.3.14.
