### ISSUE TITLE
Transparent things cause water to become invisible when using a shader

### ISSUE THREAD

**Issue by Chris6ix** [FiniteReality/embeddium#235]
### Bug Description

When using a shader and looking through something transparent like a scope or glass, water behind it becomes invisible.

I thought that it was a bug of a resource pack I use, so I reported it to that dev. He said that it is my shaders fault (BSL) and I should report it to them, so I did. The BSL dev however said "transparency sorting isn't something I handle. from what i'm aware, this shouldn't be a problem with optifine, and this can sometimes happen while using sodium. not sure about embeddium since i never used it."

So according to him, it is an Embeddium/Sodium bug, so I guess ill report it here.

Here are some screenshots of the bug: https://imgur.com/a/LrtJnYJ
Here is the original conversation with the resource pack dev in case it helps:
![image](https://github.com/embeddedt/embeddium/assets/65610536/adc6d5ff-af95-4999-97ec-921e292bd242)

### Reproduction Steps

Use Forge 47.2.20 (MC 1.20.1) with Embeddium 0.3.7+mc1.20.1, Oculus 1.6.15a and the BSL 8.2.08 Shader.
Then look through tainted glass onto water.

Or optionally download Create 0.5.1.f, MrCrayfish's Gun Mod 1.4.14 and Create Guns 1.2.0-1.20.1.
Then look through either a medium or large scope onto water.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14625306/latest.log)

**Comment by embeddedt** [comment]
Enabling translucent face sorting in video settings will probably fix this.

**Comment by Chris6ix** [comment]
That is already enabled
![2024-03-16_22 31 43](https://github.com/embeddedt/embeddium/assets/65610536/8480a81c-fbc8-4b40-932a-3c40b8057599)

**Comment by embeddedt** [comment]
Does the water reappear if you toggle the shaderpack off?

**Comment by Chris6ix** [comment]
Yes, it only breaks when the shader is active
![2024-03-16_22 33 27](https://github.com/embeddedt/embeddium/assets/65610536/7eed6c19-f59e-43cc-9054-b5455355c306)
![2024-03-16_22 33 29](https://github.com/embeddedt/embeddium/assets/65610536/6c269211-740c-47e4-a9f2-19439f2174f3)

**Comment by embeddedt** [comment]
Then it seems like a bug in Iris/Oculus, not Embeddium. Embeddium has no built-in logic for shader handling.

**Comment by Chris6ix** [comment]
And onto the next one :/

**Comment by Chris6ix** [comment]
Thank you though

**Comment by embeddedt** [comment]
No worries, sorry I couldn't be of more help.
