### ISSUE TITLE
Shading issue with obj models that are flat

### ISSUE THREAD

**Issue by IThundxr** [FiniteReality/embeddium#237]
### Bug Description

Seems obj models dont specify shading/shadows properly? This doesnt occur with just stock forge or neoforge and only when embeddium is added.

Now i don't know exactly why this would be happening but my best guess is like how the obj loader doesn't pass along culling data it doesnt pass the data for how the block's shadow's should work either.

![image](https://github.com/embeddedt/embeddium/assets/74031881/c41597c5-c953-4be2-b3bb-1be77da6d7a7)

### Reproduction Steps

1. Grab a 1.6.0 release from [my maven](https://maven.ithundxr.dev/#/snapshots/com/railwayteam/railways/Steam_Rails-forge-1.19.2) or [github actions](https://github.com/Layers-of-Railways/Railway/actions/runs/8317036007) 
2. Place a boiler and put a block next to it on its flat side
3. Observe weird shading issue

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14661253/latest.log)

**Comment by embeddedt** [comment]
Plain Forge behaves identically for me (at least when the experimental lighting pipeline is off).

https://github.com/embeddedt/embeddium/assets/42941056/5ccdae62-6268-4003-8f38-113eea881035

**Comment by IThundxr** [comment]
Uh huh, I guess I'll report it to them then.
