### ISSUE TITLE
Crash on world load with big modpack?

### ISSUE THREAD

**Issue by BoardAnims** [FiniteReality/embeddium#238]
### Bug Description

Trying to launch a world crashes the game, disabling embeddium will make the world load as normal.

Sorry for having such a large modpack, im experimenting making a custom pack, but this crash started happening after updating some mods (including embeddium). Some other mods are also disabled and may therefore not be possible culprits. (example: Embeddium++)

check the crash-log instead for a shorter log. I'll binary search the pack more thoroughly later.

### Reproduction Steps

1. Launch (Custom Modpack Modded) Minecraft
2. Enter a pre-existing world OR create a new world.
3. After the "Loading terrain..." message it will display "Saving world", and crash.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14672326/latest.log)
[crash-2024-03-20_21.39.52-client.txt](https://github.com/embeddedt/embeddium/files/14672331/crash-2024-03-20_21.39.52-client.txt)

**Comment by embeddedt** [comment]
Looks like a duplicate of https://github.com/embeddedt/embeddium/issues/111

**Comment by BoardAnims** [comment]
> Looks like a duplicate of #111

Woops yeah, sorry I was very tired from binary searching all day lol.
Panda should really fix this...
