### ISSUE TITLE
Crash with 1.20.1

### ISSUE THREAD

**Issue by ROTCTHSPECIAL** [FiniteReality/embeddium#239]
### Bug Description

My mod is crash when I try to join the World or just click on Video setting 

### Reproduction Steps

Mod List: 
		dynamiclightsreforged-1.20.1_v1.6.0.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.20.1_v1.6.0       |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.20.1-1.3.30.jar                      |Blue Skies                    |blue_skies                    |1.3.30              |DONE      |Manifest: NOSIGNATURE
		global_packs-forge-1.19.4-1.16.2_forge.jar        |Global Packs                  |globalpacks                   |1.16.2_forge        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.3.1.jar                   |GeckoLib 4                    |geckolib                      |4.3.1               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		aether-1.20.1-1.0.0-neoforge.jar                  |The Aether                    |aether                        |1.20.1-1.0.0-neoforg|DONE      |Manifest: NOSIGNATURE
		barrels_2012-2.1.jar                              |Barrels 2012                  |barrels_2012                  |2.1                 |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.111.517.jar          |Sophisticated Core            |sophisticatedcore             |0.5.111.517         |DONE      |Manifest: NOSIGNATURE
		gpumemleakfix-1.20.1-1.8.jar                      |Gpu memory leak fix           |gpumemleakfix                 |1.20.1-1.8          |DONE      |Manifest: NOSIGNATURE
		ritchiesprojectilelib-1.0.0-369e88d+1.20.1-forge.j|Ritchie's Projectile Library  |ritchiesprojectilelib         |1.0.0-369e88d+1.20.1|DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.20.1-12.0.2.jar               |Controlling                   |controlling                   |12.0.2              |DONE      |Manifest: NOSIGNATURE
		modernfix-forge-5.9.3+mc1.20.1.jar                |ModernFix                     |modernfix                     |5.9.3+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.4-1.20.1.jar                          |Citadel                       |citadel                       |2.5.4               |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.1.jar                       |MixinExtras                   |mixinextras                   |0.3.1               |DONE      |Manifest: NOSIGNATURE
		weather2-1.20.1-2.8.1.jar                         |Weather2                      |weather2                      |1.20.1-2.8.1        |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.1.6.jar                 |Bookshelf                     |bookshelf                     |20.1.6              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.20.1-3.19.4.978.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |3.19.4.978          |DONE      |Manifest: NOSIGNATURE
		lost_aether_content-1.20.1-1.2.2.jar              |Aether: Lost Content          |lost_aether_content           |1.2.2               |DONE      |Manifest: NOSIGNATURE
		simpleplanes-1.20.1-5.2.6.jar                     |Simple Planes                 |simpleplanes                  |1.20.1-5.2.6        |DONE      |Manifest: NOSIGNATURE
		jeed-1.20-2.1.6.jar                               |Just Enough Effects Descriptio|jeed                          |1.20-2.1.6          |DONE      |Manifest: NOSIGNATURE
		Steam_Rails-1.5.3+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.5.3+forge-mc1.20.1|DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar                    |FPS Reducer                   |fpsreducer                    |1.20-2.5            |DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |DONE      |Manifest: NOSIGNATURE
		chat_heads-0.10.32-forge-1.20.jar                 |Chat Heads                    |chat_heads                    |0.10.32             |DONE      |Manifest: NOSIGNATURE
		exposure-1.20.1-1.2.2-forge.jar                   |Exposure                      |exposure                      |1.2.2               |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.20.1-1.3.1.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.3.1        |DONE      |Manifest: NOSIGNATURE
		shetiphiancore-forge-1.20.1-1.2.jar               |ShetiPhian-Core               |shetiphiancore                |1.20.1-1.2          |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.1893-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1893            |DONE      |Manifest: NOSIGNATURE
		konkrete_forge_1.6.1-2_MC_1.20.jar                |Konkrete                      |konkrete                      |1.6.1               |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.9+mc1.20.1.jar                      |Embeddium                     |embeddium                     |0.3.9+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		embeddiumplus-1.20.1-v1.0.1.jar                   |Embeddium++                   |embeddiumplus                 |1.0.1               |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.20.1-2.15.1.jar                   |Structure Gel API             |structure_gel                 |2.15.1              |DONE      |Manifest: NOSIGNATURE
		corpse-1.20.1-1.0.9.jar                           |Corpse                        |corpse                        |1.20.1-1.0.9        |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.20.1-forge-1.4.10.jar        |Advancement Plaques           |advancementplaques            |1.4.10              |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.1.1-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		entity_model_features_forge_1.20.1-1.3.jar        |Entity Model Features         |entity_model_features         |1.3                 |DONE      |Manifest: NOSIGNATURE
		entity_texture_features_forge_1.20.1-5.2.3.jar    |Entity Texture Features       |entity_texture_features       |5.2.3               |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |5.3.9               |DONE      |Manifest: NOSIGNATURE
		crashutilities-8.1.4.jar                          |Crash Utilities               |crashutilities                |8.1.4               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.20.1forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		DeathFinder-v8.0.1-1.20.1-Forge.jar               |Death Finder                  |deathfinder                   |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		TextruesRubidiumOptions-1.0.5+mc1.20.1.jar        |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.5+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		create_sabers-1.20.1-1.3.0.jar                    |Create Sabers                 |create_sabers                 |1.3.0               |DONE      |Manifest: NOSIGNATURE
		Bonfires-1.20.1-1.2.15-8613d54.jar                |Bonfires                      |bonfires                      |1.2.15              |DONE      |Manifest: NOSIGNATURE
		tfcambiental-1.20.1-3.2.0.jar                     |TFC Ambiental                 |tfcambiental                  |1.20.1-3.2.0        |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.4.5+1.20.1.jar                     |Curios API                    |curios                        |5.4.5+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-81-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-81-FORGE     |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.15a.jar                       |Oculus                        |oculus                        |1.6.15a             |DONE      |Manifest: NOSIGNATURE
		Searchables-forge-1.20.1-1.0.2.jar                |Searchables                   |searchables                   |1.0.2               |DONE      |Manifest: NOSIGNATURE
		Enchanting With TFC 1.20.1-1.0.0.jar              |EnchantingWithTFC             |enchanting_with_tfc           |1.0.0               |DONE      |Manifest: NOSIGNATURE
		aether_emissivity-1.20.1-1.0.0-neoforge.jar       |Emissivity                    |aether_emissivity             |1.20.1-1.0.0-neoforg|DONE      |Manifest: NOSIGNATURE
		cumulus_menus-1.20.1-1.0.0-beta.1-neoforge.jar    |Cumulus                       |cumulus_menus                 |1.20.1-1.0.0-beta.1-|DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.2.4b-mc1.20.1forge.jar                |Macaw's Roofs                 |mcwroofs                      |2.2.4b              |DONE      |Manifest: NOSIGNATURE
		littlelogistics-mc1.20.1-v1.20.1.2.jar            |Little Logistics              |littlelogistics               |1.20.1.2            |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		yuushya-1.20.1-forge-2.1.1.jar                    |Yuushya                       |yuushya                       |2.1.1               |DONE      |Manifest: NOSIGNATURE
		yuushya-modelling-1.20.1-forge-2.0.0.jar          |Yuushya Modelling             |yuushya_modelling             |2.0.0               |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.2.1-mc1.20.1forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.1               |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.6.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.6          |DONE      |Manifest: NOSIGNATURE
		umbral_skies-1.3.jar                              |Umbral Skies                  |umbral_skies                  |1.3                 |DONE      |Manifest: NOSIGNATURE
		nitrogen_internals-1.20.1-1.0.1-neoforge.jar      |Nitrogen                      |nitrogen_internals            |1.20.1-1.0.1-neoforg|DONE      |Manifest: NOSIGNATURE
		rubidium-extra-0.5.3.1+mc1.20.1-build.110.jar     |Rubidium/Embeddium Extra      |rubidium_extra                |0.5.3.1+mc1.20.1-bui|DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.20.1-forge-5.2.1.jar                 |Jade Addons                   |jadeaddons                    |5.2.1               |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.27.jar                 |Framework                     |framework                     |0.6.27              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		twilighttweaks-1.20.x-1.2.jar                     |Twilight Tweaks               |twilighttweaks                |1.2                 |DONE      |Manifest: NOSIGNATURE
		l2library-2.4.14-slim.jar                         |L2 Library                    |l2library                     |2.4.14              |DONE      |Manifest: NOSIGNATURE
		deep_aether-1.20.1-1.0.12.jar                     |Deep Aether                   |deep_aether                   |1.20.1-1.0.12       |DONE      |Manifest: NOSIGNATURE
		cuisinedelight-1.1.12.jar                         |Cuisine Delight               |cuisinedelight                |1.1.12              |DONE      |Manifest: NOSIGNATURE
		YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.ja|Yeetus Experimentus           |yeetusexperimentus            |2.3.1-build.6+mc1.20|DONE      |Manifest: NOSIGNATURE
		tfcoreprocessing-1.0.0.jar                        |Ore Processing for TFC        |tfcoreprocessing              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.20.1-0.3.2.161.jar           |Better Advancements           |betteradvancements            |0.3.2.161           |DONE      |Manifest: NOSIGNATURE
		clienttweaks-forge-1.20-11.1.0.jar                |Client Tweaks                 |clienttweaks                  |11.1.0              |DONE      |Manifest: NOSIGNATURE
		rhino-forge-2001.2.2-build.13.jar                 |Rhino                         |rhino                         |2001.2.2-build.13   |DONE      |Manifest: NOSIGNATURE
		createbigcannons-forge-1.20.1-0.5.3.b.jar         |Create Big Cannons            |createbigcannons              |0.5.3.b-nightly-8a45|DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-2001.1.4.jar                    |FTB Library                   |ftblibrary                    |2001.1.4            |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-2001.1.4.jar                      |FTB Teams                     |ftbteams                      |2001.1.4            |DONE      |Manifest: NOSIGNATURE
		item-filters-forge-2001.1.0-build.59.jar          |Item Filters                  |itemfilters                   |2001.1.0-build.59   |DONE      |Manifest: NOSIGNATURE
		platforms-forge-1.20.1-1.1.jar                    |Platforms                     |platforms                     |1.20.1-1.1          |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		kubejs-forge-2001.6.4-build.111.jar               |KubeJS                        |kubejs                        |2001.6.4-build.111  |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.18-forge.jar                |Journeymap                    |journeymap                    |5.9.18              |DONE      |Manifest: NOSIGNATURE
		breezy-1.20.1-1.1.1.jar                           |Breezy                        |breezy                        |1.1.1               |DONE      |Manifest: NOSIGNATURE
		artifacts-forge-9.2.0.jar                         |Artifacts                     |artifacts                     |9.2.0               |DONE      |Manifest: NOSIGNATURE
		[1.20.1-forge]-Epic-Knights-9.2.jar               |Epic Knights Mod              |magistuarmory                 |9.2                 |DONE      |Manifest: NOSIGNATURE
		[1.20.x-forge]-Epic-Knights-Slavic-Armory-1.4.jar |Epic Knights: Slavic Armory   |slavicarmory                  |1.4                 |DONE      |Manifest: NOSIGNATURE
		[1.20.x-forge]-Epic-Knights-Addon-1.6.jar         |Epic Knights: Addon           |magistuarmoryaddon            |1.6                 |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.20.1-14.0.28.jar             |CraftTweaker                  |crafttweaker                  |14.0.28             |DONE      |Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		3dskinlayers-forge-1.5.4-mc1.20.1.jar             |3dSkinLayers                  |skinlayers3d                  |1.5.4               |DONE      |Manifest: NOSIGNATURE
		TF_Lost_Blocks-1.20.1-1.3.2.jar                   |Twilight Forest: The Lost Bloc|tflostblocks                  |1.20.1-1.3.2        |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		corals-tfc-1.0.0-forge-1.20.1.jar                 |Corals TFC                    |coralstfc                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		alexscaves-1.1.4.jar                              |Alex's Caves                  |alexscaves                    |1.1.4               |DONE      |Manifest: NOSIGNATURE
		tact-1.1.1+1.20.1.jar                             |TACT                          |tact                          |1.1.1               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20.1-17.0.9.jar   |EnchantmentDescriptions       |enchdesc                      |17.0.9              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		AdvancedTFCTech-1.20.1-2.0.jar                    |Advanced TFC Tech Unofficial  |advancedtfctech               |2.0                 |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.8.72-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.72         |DONE      |Manifest: NOSIGNATURE
		labels-1.20-1.19.jar                              |Labels                        |labels                        |1.20-1.19           |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.20-2.25.jar                 |Mouse Tweaks                  |mousetweaks                   |2.25                |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.8.4+1.20.1.jar               |Better Combat                 |bettercombat                  |1.8.4+1.20.1        |DONE      |Manifest: NOSIGNATURE
		ftb-quests-forge-2001.2.0.jar                     |FTB Quests                    |ftbquests                     |2001.2.0            |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.20.1-10.0.0-169.jar        |Immersive Engineering         |immersiveengineering          |1.20.1-10.0.0-169   |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		NoChatReports-FORGE-1.20.1-v2.2.2.jar             |No Chat Reports               |nochatreports                 |1.20.1-v2.2.2       |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.6.3.jar                      |Jade                          |jade                          |11.6.3              |DONE      |Manifest: NOSIGNATURE
		kubejs_tfc-1.20.1-1.0.3.jar                       |KubeJS TFC                    |kubejs_tfc                    |1.20.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.25_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.25             |DONE      |Manifest: NOSIGNATURE
		smoothboot-mc1.20.1-0.0.3.jar                     |Smooth Boot (Reloaded)        |smoothboot                    |0.0.3               |DONE      |Manifest: NOSIGNATURE
		Ding-1.20.1-Forge-1.4.1.jar                       |Ding                          |ding                          |1.4.1               |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.20.x-1.1.6.jar                     |AstikorCarts Redux            |astikorcarts                  |1.1.6               |DONE      |Manifest: NOSIGNATURE
		aeroblender-1.20.1-1.0.1-neoforge.jar             |AeroBlender                   |aeroblender                   |1.20.1-1.0.1-neoforg|DONE      |Manifest: NOSIGNATURE
		ancient_aether-0.7.2.jar                          |Ancient Aether                |ancient_aether                |0.7.2               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.20.1-forge-1.1.16.jar                   |Iceberg                       |iceberg                       |1.1.16              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		Rats-1.20.1-8.1.2.jar                             |Rats                          |rats                          |1.20.1-8.1.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.6-universal.jar                 |Forge                         |forge                         |47.2.6              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		TerraFirmaCraft-Forge-1.20.1-3.1.4-beta.jar       |TerraFirmaCraft               |tfc                           |3.1.4-beta          |DONE      |Manifest: NOSIGNATURE
		waterflasks-3.0.2.jar                             |TFC Water Flasks              |waterflasks                   |3.0.2               |DONE      |Manifest: NOSIGNATURE
		FarmersDelightTFC-1.0.4-forge-1.20.1.jar          |Farmers Delight TFC           |farmersdelight_tfc            |1.0.4               |DONE      |Manifest: NOSIGNATURE
		TFC-IE-Crossover-1.20.1-1.1.4.jar                 |TFC + IE Crossover            |tfc_ie_addon                  |1.1.4               |DONE      |Manifest: NOSIGNATURE
		TFCAstikorCarts-1.20.1-1.1.7.2.jar                |TFC Astikor Carts             |tfcastikorcarts               |1.1.7.2             |DONE      |Manifest: NOSIGNATURE
		mcw_tfc_aio-0.2.8-1.20.1.jar                      |Macaw's All-In-One for TFC    |mcw_tfc_aio                   |0.2.8-1.20.1        |DONE      |Manifest: NOSIGNATURE
		FirmaCivilization-0.1.10-alpha-1.20.1.jar         |Firma: Civilization           |firmaciv                      |0.1.10-alpha        |DONE      |Manifest: NOSIGNATURE
		treetap-1.20.1-0.2.3.jar                          |Tree Tap                      |treetap                       |1.20.1-0.2.3        |DONE      |Manifest: NOSIGNATURE
		afc-1.0.0-1.20.1.jar                              |ArborFirmaCraft               |afc                           |1.0.0-1.20.1        |DONE      |Manifest: NOSIGNATURE
		htm-1.0.3-forge-1.20.1.jar                        |HardRock Tools & Materials    |htm                           |1.0.3               |DONE      |Manifest: NOSIGNATURE
		AnimalTrap-1.20.1-forge-1.0.1.jar                 |Animal Trap                   |animaltrap                    |1.0.1               |DONE      |Manifest: NOSIGNATURE
		AnimalTrapTFC-1.20.1-forge-1.0.1.jar              |Animal Trap TFC               |animaltraptfc                 |1.0.1               |DONE      |Manifest: NOSIGNATURE
		backpacked-forge-1.20.1-2.2.5.jar                 |Backpacked                    |backpacked                    |2.2.5               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		CGM-Unofficial-1.4.15+Forge+1.20.1.jar            |MrCrayfish's Gun Mod          |cgm                           |1.4.15              |DONE      |Manifest: NOSIGNATURE
		TFCAgedAlcohol-1.20.1-2.0.jar                     |TFC Aged Alcohol              |tfcagedalcohol                |2.0                 |DONE      |Manifest: NOSIGNATURE
		coroutil-1.20.1-1.3.0.jar                         |CoroUtil                      |coroutil                      |1.20.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		TFCWeather-1.20.1-1.6.jar                         |TFC Weather                   |tfcweather                    |1.6                 |DONE      |Manifest: NOSIGNATURE
		automobility-0.4.2+1.20.1-forge.jar               |Automobility                  |automobility                  |0.4.2+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		lootr-1.20-0.7.30.73.jar                          |Lootr                         |lootr                         |0.7.29.68           |DONE      |Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		biomemusic-1.20.1-2.3.jar                         |biomemusic mod                |biomemusic                    |1.20.1-2.3          |DONE      |Manifest: NOSIGNATURE
		ModernUI-Forge-1.20.1-3.9.0.4-universal.jar       |Modern UI                     |modernui                      |3.9.0.4             |DONE      |Manifest: 01:c4:52:25:b1:6e:5f:ac:fe:88:35:7e:cf:65:2f:69:1d:56:db:2b:93:f8:dd:7c:93:47:04:8c:e4:22:13:91
		PuzzlesLib-v8.1.11-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.11              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Firmalife-1.20.1-2.0.6-beta.jar                   |Firmalife                     |firmalife                     |2.0.6-beta          |DONE      |Manifest: NOSIGNATURE
		CastIronGrill-1.20.1-2.1.jar                      |TFC Cast Iron Grill           |castirongrill                 |2.1                 |DONE      |Manifest: NOSIGNATURE
		betterlily-1.20-1.3.1.jar                         |Better Lily Pads              |betterlily                    |1.20-1.3.1          |DONE      |Manifest: NOSIGNATURE
		TFCVesselTooltip-1.20.1-1.0.jar                   |TFC Vessel Tooltip            |tfcvesseltooltip              |1.0                 |DONE      |Manifest: NOSIGNATURE
		PacketFixer-forge-1.2.1-1.20.1.jar                |Packet Fixer                  |packetfixer                   |1.2.1               |DONE      |Manifest: NOSIGNATURE
		aether-redux-1.3.3-1.20.1-neoforge.jar            |The Aether: Redux             |aether_redux                  |1.20.1              |DONE      |Manifest: NOSIGNATURE
		expandability-forge-9.0.0.jar                     |ExpandAbility                 |expandability                 |9.0.0               |DONE      |Manifest: NOSIGNATURE
		IMBlocker_4.0.5+1.20.jar                          |IMBlocker                     |imblocker                     |4.0.5               |DONE      |Manifest: NOSIGNATURE
		flickerfix-1.20.1-4.0.1.jar                       |FlickerFix                    |flickerfix                    |4.0.1               |DONE      |Manifest: NOSIGNATURE
		0Pack2Reload-Forge-1.20.1-1.0.1.jar               |0Pack2Reload                  |opack2reload                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		createaddition-1.20.1-1.2.3.jar                   |Create Crafts & Additions     |createaddition                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14732024/latest.log)

**Comment by embeddedt** [comment]
Update TexTrue's Rubidium/Embeddium Options.

**Comment by ROTCTHSPECIAL** [comment]
my modpack dont have TexTrue's Embeddium Options inside the modoack
but it's had TexTrue's Rubidium Options for the lastest verison already

**Comment by ROTCTHSPECIAL** [comment]
> Update TexTrue's Rubidium/Embeddium Options.

my modpack dont have TexTrue's Rubidium Options inside the modoack
but it's had TexTrue's Embeddium Rubidium Options for the lastest verison already

**Comment by embeddedt** [comment]
That will probably not work with modern versions of Embeddium; I recommend you use TexTrue's Embeddium Options instead.

**Comment by ROTCTHSPECIAL** [comment]
> That will probably not work with modern versions of Embeddium; I recommend you use TexTrue's Embeddium Options instead.

![image](https://github.com/embeddedt/embeddium/assets/101528446/5e57587e-591b-41e9-8436-3c8486e89467)
I have both of it in my modpack

**Comment by ROTCTHSPECIAL** [comment]
> That will probably not work with modern versions of Embeddium; I recommend you use TexTrue's Embeddium Options instead.

Well, I have to downgrade it for TexTrue's Embeddium Options verison? or something?
