### ISSUE TITLE
IT'S KEEP CRASHING WITH 1.20.1

### ISSUE THREAD

**Issue by ROTCTHSPECIAL** [FiniteReality/embeddium#240]
### Bug Description

Video settings menu option or Join The World crashes game

### Reproduction Steps

I try to downgrade "Embeddium verison 0.3.1+mc1.20.4" for "TexTrue's Embeddium Options verison 0.1.5+mc1.20.1"

### Log File

Crash log :
[crash-2024-03-23_22.38.31-client.txt](https://github.com/embeddedt/embeddium/files/14732078/crash-2024-03-23_22.38.31-client.txt)

Lastes log :
[latest.log](https://github.com/embeddedt/embeddium/files/14732079/latest.log)

**Comment by embeddedt** [comment]
Please do not keep spamming the issue tracker. As mentioned in the bug report template, the issue tracker is not intended for support requests (these should be directed to Discord). Issues should be used for legitimate bug reports.

I have just tested, and the latest versions of Embeddium (0.3.9), Oculus (1.6.15a), and TexTrue's Embeddium Options (0.1.5+mc1.20.1) work fine together in a standalone instance. If you are still experiencing crashes, you probably have another add-on that needs to be upgraded or removed. I wouldn't advise downgrading Embeddium while using Oculus as it will usually cause a crash unless you also find an older Oculus version.

**Comment by ROTCTHSPECIAL** [comment]
> Oculus

it's keep crashing

[crash-2024-03-23_23.24.54-client.txt](https://github.com/embeddedt/embeddium/files/14732899/crash-2024-03-23_23.24.54-client.txt)

[latest.log](https://github.com/embeddedt/embeddium/files/14732900/latest.log)

**Comment by embeddedt** [comment]
As I mentioned, you should make sure all add-ons are up to date (in this case, your version of Rubidium Extra appears to be quite old, the latest is 0.5.4.2).

**Comment by ROTCTHSPECIAL** [comment]
> As I mentioned, you should make sure all add-ons are up to date (in this case, your version of Rubidium Extra appears to be quite old, the latest is 0.5.4.2).

I see I t will try
thank yo, mate
