### ISSUE TITLE
[1.20.1][Connector] Missing support for the FREX Flawless Frames API for Replay Mod.

### ISSUE THREAD

**Issue by VOLKOUL** [FiniteReality/embeddium#241]
### Bug Description

Replay Mod actually used to work with Embeddium (using Connector) without any issues. It seems that something got changed, however. Whenever you try to render a clip, there will be a grayed out "Render" button along with a warning message.

I have seen issue https://github.com/embeddedt/embeddium/issues/197, and know that you don't support Sodium/Connector stuff directly. Still, I find it weird that it was marked as "wontfix", considering Replay Mod **did** work at one point and especially considering that Embeddium focuses on compatibility. It was already an achievement to get Replay Mod to work on Connector, as support for it would break all the time (it is fixed now), but not having the ability to render clips with Embeddium essentially makes Replay Mod completely useless and throws all the time and effort of the Connector devs to the trash. Like, what even is the point of making Replay Mod work on Connector if you can't use it? I just can't wrap my head around it. Please, I ask you to take a look at this. It's a really useful tool that a lot of people and content creators need. Plus, Embeddium is the go to choice for Modpack creators and regular players alike. WE NEED IT TO WORK AAA <sup><sub>heeelp</sub></sup>

![Screenshot (949)](https://github.com/embeddedt/embeddium/assets/97387920/84bbf277-8614-4412-b2f2-fbbb5f62e0df)

**Comment by TelepathicGrunt** [comment]
@Wanderer70 Just FYI, if the bug specifically happens when Syntra Connector is on with the other mods involved, then the issue report should go to Syntra Connector’s issue report. 

The devs of Syntra Connector specifically told us modders that they do not want other modders fixing connector issues in their own mods. Only connector should be fixing issues related to connector. 

Have you opened an issue report with Syntra Connector about this yet? Their issue report repo is here: https://github.com/Sinytra/Connector/issues

**Comment by VOLKOUL** [comment]
Thanks for letting me know! I wasn't aware that the Connector devs told that to modders (though now that I think about it, it seems quite obvious). I am not sure however that this is a Connector issue, considering it's nature. Soo yeah, that's why I reported it here. Anyway, here is the report I made on Connector's repo: https://github.com/Sinytra/Connector/issues/932

**Comment by embeddedt** [comment]
At the moment this would need to be patched in Lazurite as the Forge build of Embeddium doesn't interact with any Fabric APIs. In the future, if support for Forgified Fabric API was merged in Embeddium itself, this would be in scope to fix.

> I find it weird that it was marked as "wontfix", considering Replay Mod did work at one point and especially considering that Embeddium focuses on compatibility. 

The above, along with the fact that we provide no guarantee of Fabric mods working properly when they try to interact with Embeddium through Connector, is why #197 was marked as "wontfix". We focus on compatibility with mods running on their native platform. It introduces a whole new dimension of possible issues when there is another third-party translation layer involved to run mods from one platform on the other.

**Comment by VOLKOUL** [comment]
Oke! Thanks for clarifying! There are quite a few mods involved and therefore sorry for entangling you into this. Like you suggested, I also made an issue report on Lazurite's repo. Hope this can be resolved rather effortlessly :D

**Comment by VOLKOUL** [comment]
Fixed it. Even with the Lazurite update I couldn't render anything, but after making a fresh installation I noticed that everything worked fine. There probably was some breaking change in an Embeddium update that altered the config file in some way. Anyway, I deleted all config files so that they could generate again and everything works perfectly!
