### ISSUE TITLE
[1.20.1][fabric loader] Replay Mod cannot be rendering when using embeddium but it can work with sodium

### ISSUE THREAD

**Issue by feipangjun** [FiniteReality/embeddium#242]
### Bug Description

![image](https://github.com/embeddedt/embeddium/assets/93204475/d4dbc6eb-c72c-417f-9b73-b4953859595c)
as the picture shows,the render button cannot be clicked and drop the missing api error
whatever it will be fixed or not,thanks in advance

### Reproduction Steps

loader:
Fabric loader 

mods:
embeddium 0.3.9
replay mod 2.6.15

steps:
install two mods on fabric
try to render a video

### Log File

no logs

**Comment by embeddedt** [comment]
Duplicate of #241.

**Comment by VOLKOUL** [comment]
Bro, did you really shamelessly take my screenshot just to report the same exact same thing I did? Bruh...
