### ISSUE TITLE
World invisible when used with immersive portals (through Sinytra Connector) (1.12.1)

### ISSUE THREAD

**Issue by 2dragonfire** [FiniteReality/embeddium#244]
### Bug Description

Every block is invisible. You can break blocks, interact with things, and even see particles (ie. breaking blocks and cherry blossoms falling), but everything else is invisible. Of course, this means the world loads...

### Reproduction Steps

use Minecraft forge 1.12.1 to launch immersive portals fabric through Sinytra Connector and embeium forge at the same time. (version 0.3.9 of embedium forge) (version 1.0.0.beta.40 of Sinytra Connector) (version 1.10.0 of connector extras) (version 0.92.0+1.11.3 of forgified fabric api) (version 3.3.9 of immersive portals fabric)

### Log File

N/A

**Comment by 2dragonfire** [comment]
trying different combos of versions of immersive portals fabric and embedium forge. Will update if I make any progress...

**Comment by embeddedt** [comment]
You likely need to register a mod alias in Connector's config so that IP detects Embeddium as Sodium. Please ask in the Connector support channels for help with this if needed.

**Comment by 2dragonfire** [comment]
mmmk, cool
