### ISSUE TITLE
Bug with FTB Chunks and Teams/Incompatibility 

### ISSUE THREAD

**Issue by ToxinZangoose** [FiniteReality/embeddium#247]
### Bug Description

Hello, I recently joined a server and hoped to use Embeddium with Lightman’s Currency.
I had an issue where the world map and minimap wouldn’t show up or open even with keybinds.

We are using Entity Culling and Sound Physics Remastered, but I think this has to do with rendering.

### Reproduction Steps

1. Install Lightman’s Currency, Embeddium and FTB chunks and teams.
2. Boot up Minecraft with Forge 47.2.21
3. Join a server with the mods installed
4. Try to open the world map with the keybind
5. Also notice the minimap missing

### Log File

https://mclo.gs/iXli0Mp

Here is the debug log from last night.

**Comment by embeddedt** [comment]
With just these mods installed, I am able to see the minimap & open the world map without issues.

**Comment by Nolij** [comment]
Closing this tomorrow if no updated reproduction steps are provided as we are unable to reproduce this issue. We can always re-open it if we receive updated reproduction steps after that.
