### ISSUE TITLE
Donation popup softlocks game with Controllable

### ISSUE THREAD

**Issue by Tslat** [FiniteReality/embeddium#248]
### Bug Description

Embeddium's new donation popup that comes up in the settings menu seems to remove the cursor entirely when using the [Controllable ](https://www.curseforge.com/minecraft/mc-mods/controllable) mod.

This causes the entire game to become unusable until you go back to a keyboard and mouse - which for users that have a setup built for controller, this can be a complete softlock of the entire game

### Reproduction Steps

Install Controllable and Embeddium

Open the video settings menu
See popup covering screen which removes the cursor from Controllable

### Log File

[Diagram.txt](https://github.com/embeddedt/embeddium/files/14808428/Diagram.txt)

**Comment by embeddedt** [comment]
Fixed in 0.3.14 by not showing the screen with Controllable present for now.
