### ISSUE TITLE
Light Blocks trail behind player like a particle effect

### ISSUE THREAD

**Issue by Naixatloz** [FiniteReality/embeddium#252]
### Bug Description

Whenever I hold a light block, I get a trail of them going behind me like some kind of particle effect. They aren't placed in the world, they're just a visual effect. Further, actual light blocks that have been placed in the overworld remain invisible even when I'm holding one. Just the outline remains.

![2024-03-30_21 54 09](https://github.com/embeddedt/embeddium/assets/92188768/13e6d8ee-baa9-4de8-b084-20fef0dd6c62)
![2024-03-30_22 01 48](https://github.com/embeddedt/embeddium/assets/92188768/07342f5e-2827-458c-ba3d-b9d1e87c9d80)

I have a lot of mods and I'll admit that I haven't tested them individually, but with all of my other mods active, but Embeddium and its dependents turned off, the block works as it should with no unexpected behavior. The moment I enable Embeddium (whether or not any of its dependents are enabled too), the problem starts.

### Reproduction Steps

1. Have Embeddium installed
2. Have a light block in your active inventory slot
3. Move around

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14814157/latest.log)

**Comment by embeddedt** [comment]
Fixed in 0.3.12
