### ISSUE TITLE
[1.20.1] Crash with BedrockWaters through the Sinytra Connector

### ISSUE THREAD

**Issue by Starexify** [FiniteReality/embeddium#253]
### Bug Description

When I install BedrockWaters alongside Embeddium through Sinytra Connector. It has many issues.

### Reproduction Steps

1 Install Embeddium alongside Sinytra Connector and BedrockWaters and try to open a world.

### Log File

[latest.log](https://github.com/Sinytra/Connector/files/14816023/latest.log)
[crash-2024-03-31_15.13.46-client.txt](https://github.com/Sinytra/Connector/files/14816019/crash-2024-03-31_15.13.46-client.txt)

**Comment by embeddedt** [comment]
As mentioned on the [compatibility page](https://github.com/embeddedt/embeddium/wiki/Compatibility#fabric-mods-sinytra-connector), we don't officially support running Fabric mods with Embeddium via Connector (although many work fine).
