### ISSUE TITLE
Embeddium Movement Issues with Server

### ISSUE THREAD

**Issue by Tralty** [FiniteReality/embeddium#254]
### Bug Description

Whenever I join a server, and teleport, move, then repeat one more time. My Client crashes and the crash log directs it towards Embeddium. I disabled Oculus earlier and the same exact crash occurred.

### Reproduction Steps

1) Join a server
2) Teleport to a random location (2 times)

### Log File

[crash-2024-03-31_19.25.12-client.txt](https://github.com/embeddedt/embeddium/files/14817939/crash-2024-03-31_19.25.12-client.txt)

**Comment by Tralty** [comment]
Nvm, I've solved the issue, it was caused by something I had enabled for the server

**Comment by embeddedt** [comment]
May I ask what you changed to resolve the issue? I sometimes get support requests with this problem and knowing what to suggest would be useful.

**Comment by Tralty** [comment]
I thought it would fix it, but the same crash occurred after I disabled the UDP Network on my server

**Comment by embeddedt** [comment]
The only underlying cause for that issue I've found is blocks being registered on the server but not the client, which usually means the server & client have mismatched mods/configs.

**Comment by Tralty** [comment]
I'll take that into consideration and get the mods and configs to match if they aren't matched already

**Comment by Tralty** [comment]
Hey, I solved the issue! Feywild was causing it so I removed the mod and the crash doesn't occur anymore.
