### ISSUE TITLE
Some Mahou Tsukai entities are invisible

### ISSUE THREAD

**Issue by sutepu-chan** [FiniteReality/embeddium#26]
Unable to render entities and thrown swords from Mahou Tsukai. They appear invisible. No other things are affected (the game run normally and smoothly)
I tested with the following items / entities:
- Power Consolidation
- Treasury (weapon projectile)
- AOE explosion
- Beam

FYI: I also tried these entities and swords with Rubidium but the game crashes immediately.

MC Version: 1.20.1
Forge: 47.1.47
Mahou Tsukai Mod Version: 1.20.1-v1.34.58
Embeddium Mod Version: 0.1.4+mc1.20.1

**Comment by embeddedt** [comment]
I've never used Mahou Tsukai before; can you provide some steps on what items I should use in creative to reproduce the issue?

**Comment by sutepu-chan** [comment]
I have further tested for the items and i realize that embeddiun only causes problem with treasury projections. The other problems are related to "Entity Culling" mod.

For using the treasury projection, use the item "Treasury Projection Gauntlet", together with a weapon (e.g. Diamond sword) somewhere in your inventory.

There are 3 different mode of the gauntlet, which are the targeted mode, AOE mode, and chain mode.

When you initially take out the item, it should be in targeted mode. Hold RC and the diamond sword will be projected out as entities with another entity "mahoujin". However, these entities are rendered as invisible with embeddium. This problem also appears in AOE mode

**Comment by embeddedt** [comment]
Disabling Embeddium's built-in entity culling in Video Settings -> Performance works around this for the time being.

**Comment by sutepu-chan** [comment]
Ok. Thanks for the temporary solution. Love to see if this problem fix some day :)

**Comment by embeddedt** [comment]
It will be fixed as of Embeddium 0.1.6.

**Comment by embeddedt** [comment]
Released.
