### ISSUE TITLE
Oculus Flywheel Compat Causes Crash 

### ISSUE THREAD

**Issue by TqLxQuanZ** [FiniteReality/embeddium#260]
### Bug Description

Before heading on, this bug is very unstable and log does not provide any useful information, so it could be a false report which the issue happen on Oculus' side, but it also has a chance to happen on Embeddium side because the mod Oculus Flywheel Compat  requires Oculus, and Oculus requires Embeddium, which has a chain dependencies.

In short, when all those 4 mods are installed, 

create-1.18.2-0.5.1.f.jar
https://www.curseforge.com/minecraft/mc-mods/create/files/4835188

embeddium-0.3.12+mc1.18.2.jar
https://www.curseforge.com/minecraft/mc-mods/embeddium/files/5230465

oculus-flywheel-compat-1.18.2-0.2.1.jar
https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat/files/4631182

oculus-mc1.18.2-1.6.4.jar
https://www.curseforge.com/minecraft/mc-mods/oculus/files/4578744

and flywheel is using Batching render type inside flywheel-client.toml, the game will straight out crash when entering a world, Instancing or Off render type for flywheel seems to work fine.

My apologies in advance because I am unable to identify which mod exactly it comes from (Either from Oculus, Embbedium, or Oculus Flywheel Compat itself)

### Reproduction Steps

1. Install the following mods: create-1.18.2-0.5.1.f.jar, embeddium-0.3.12+mc1.18.2.jar, oculus-flywheel-compat-1.18.2-0.2.1.jar, oculus-mc1.18.2-1.6.4.jar
2. Launch the game
3. Create a world and join the world
4. Crash.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14894582/latest.log)

This one has the weirdest log file without providing any proper info.

**Comment by embeddedt** [comment]
This is almost certainly an issue in either Oculus or Oculus Flywheel Compat. I believe the latter mod is known to have issues in some scenarios, although I'm unaware of what they are.
