### ISSUE TITLE
Stained / Tinted glass displays artifacting

### ISSUE THREAD

**Issue by quarkstuff** [FiniteReality/embeddium#265]
### Bug Description

Stained and Tinted glass shows clear artifacting ( possibly due to culling? ). This is both distracting, and makes certain building techniques impossible.

## Without Embeddium ( expected behavior )
![2024-04-16_07 38 20](https://github.com/embeddedt/embeddium/assets/47686923/7c1442e3-14d8-4e84-a6fe-e7e1eb5050c6)
## With Embeddium ( observed behavior )
![2024-04-16_07 37 48](https://github.com/embeddedt/embeddium/assets/47686923/85b10274-920d-4592-94f9-aae7279793a5)

### Reproduction Steps

1. Launch Minecraft with Embeddium
2. Build two layers of non-regular glass
    - 2 layers of stained glass of different colors next to each other
    - 2 layers of tinted glass with at least 1 air block separating them

### Log File

[Without Embeddium](https://github.com/embeddedt/embeddium/files/14997749/without_embeddium.log)
[With Embeddium](https://github.com/embeddedt/embeddium/files/14997747/with_embeddium.log)

**Comment by embeddedt** [comment]
Enable translucency sorting in video settings.
