### ISSUE TITLE
[1.16] Conflict with the Chisel and Bits mod

### ISSUE THREAD

**Issue by SEDIIK** [FiniteReality/embeddium#266]
### Bug Description

Hello, noticed a problem with shadows when working with the Chisel&Bits mod. When you break pixels in blocks, there are bugs with shadows. 
I attach a screenshot with the problem.
Minecraft version: 1.16.5
Embeddium version: 0.3.14
Chisel&Bits version: 1.0.63
![2024-04-16_18 52 37](https://github.com/embeddedt/embeddium/assets/130316398/66f3e588-ac03-434b-9a8e-f264f130a873)
![2024-04-16_18 52 28](https://github.com/embeddedt/embeddium/assets/130316398/50d8111b-8c42-4f94-9771-8deb90395412)

### Reproduction Steps

Just start breaking pixels in blocks thanks to this mod

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14999469/latest.log)

**Comment by embeddedt** [comment]
Cannot reproduce in a minimal instance with Embeddium/C&B, I broke pixels in various blocks and they seem to render fine.

![2024-04-16_19 28 34](https://github.com/embeddedt/embeddium/assets/42941056/b0a1d6f5-cabe-49c3-bccc-9015124906d9)

**Comment by SEDIIK** [comment]
Hello, I found out what the problem was - due to smooth lighting being turned off

**Comment by SEDIIK** [comment]
Hello, I found out what the problem is - due to the disabling of smooth lighting.
This is not Embeddium's fault, I apologize for wasting your time.
