### ISSUE TITLE
Render Erro

### ISSUE THREAD

**Issue by Sabertooph** [FiniteReality/embeddium#267]
### Bug Description

The game closes whenever I try to open it with holygl4es, even though I'm using an emulator on my cell phone, if I open it with Vulkan it will work "normally".  I don't use Vulkan because it is very slow with an average of 26 fps.

### Reproduction Steps

 Open Minecraft 1.20.1 in the Pojavlaucher and Foldcraftlaucher emulators and use Embeddium for the respective versions with Holygl4es as renderer, when trying to enter the world the game will crash.

### Log File

[crash-2024-04-21_00.18.43-client.txt](https://github.com/embeddedt/embeddium/files/15050542/crash-2024-04-21_00.18.43-client.txt)

**Comment by embeddedt** [comment]
The OpenGL emulation drivers used by Pojav Launcher are known to have compatibility problems with Sodium and its derivatives. We don't provide official support for these setups.
