### ISSUE TITLE
[1.20.1] Crashes when entering The Aether dimension. ("Encountered exception while building chunk meshes").

### ISSUE THREAD

**Issue by Gbergz** [FiniteReality/embeddium#27]
Entering the Aether from The Aether mod crashes the game.

### Versions:
MC: 1.20.1
Forge: 47.1.3
Embeddium: 0.1.4
The Aether: 1.0.0-beta.1.1 | https://legacy.curseforge.com/minecraft/mc-mods/aether/files/4756629

### Crash Report:
https://gist.githubusercontent.com/Gbergz/4dc829382e4a488611cca52787c6031e/raw/c1b621f76b46ad70bc403ff242dd0e0c807f8981/gistfile1.txt

**Comment by embeddedt** [comment]
Thanks! Should be fixed in 0.1.5.
