### ISSUE TITLE
Incompatibility with TexTrue's Embeddium Options

### ISSUE THREAD

**Issue by Vinzound** [FiniteReality/embeddium#276]
### Bug Description

![image](https://github.com/embeddedt/embeddium/assets/144878239/fccc7388-6d03-4e7f-af4c-708faabcba59)

The two recent Embeddium updates (01/05/2024) stopped supporting TexTrue's Embeddium Options, or according to that message it shows when I open the game, preventing me from playing.

### Reproduction Steps

Simply open the game.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/15181013/latest.log)

**Comment by embeddedt** [comment]
As mentioned in the [changelog](https://github.com/embeddedt/embeddium/wiki/Changelog#0316), the new config screen supersedes TexTrue's Embeddium Options. You no longer need that mod.

**Comment by Vinzound** [comment]
Oooh! I'm sorry for not realizing it before, thank you very much for adding that to the base mod :)

**Comment by Yaen11** [comment]
> Oooh! I'm sorry for not realizing it before, thank you very much for adding that to the base mod :)

What did you do to fix it?
