### ISSUE TITLE
Crash with Occulus

### ISSUE THREAD

**Issue by awbuckst11181999** [FiniteReality/embeddium#281]
### Bug Description

Game will randomly crash with a shader enabled with Occulus, see log file below.

java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.RenderSection.getCulledBlockEntities()" because "renderSection" is null

Let me know if this is more appropriate to report to Occulus instead!

### Reproduction Steps

It is fairly random

### Log File

[crash-2024-05-02_23.58.09-client.txt](https://github.com/embeddedt/embeddium/files/15196081/crash-2024-05-02_23.58.09-client.txt)

**Comment by embeddedt** [comment]
Please report it to Oculus unless you can reproduce it with shaders disabled/Oculus uninstalled.
