### ISSUE TITLE
Game close after Embeddium update in Forge 1.20.1

### ISSUE THREAD

**Issue by lynariel** [FiniteReality/embeddium#283]
### Bug Description

Game is closing at Forge loading since updating latest Embeddium upgrade. I have the latest version of all mods. I have the latest drivers for my graphic card. I pull of TexTrue's Embeddium Options mod. I tested with the 2 versions of Forge. The 47.2.0 and 47.2.30. When I read the latest.log 
It said "Method overwrite conflict for m_6104_ in embeddium.mixins.json:features.options.render_layers.LeavesBlockMixin, previously written by me.srrapero720.embeddiumplus.mixins.impl.leaves_culling.LeavesBlockMixin. Skipping method."

Thanks in advance !

### Reproduction Steps

I clic on play on the minecraft launcher. Forge is initializing and it closes  with exit code : 1

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/15203730/latest.log)

**Comment by embeddedt** [comment]
Please look for a `launcher_log.txt` in your `.minecraft` folder and send it; the log you sent doesn't appear to contain a crash.

**Comment by lynariel** [comment]
Ho sorry ! It's here !
[launcher_log.txt](https://github.com/embeddedt/embeddium/files/15203783/launcher_log.txt)

**Comment by embeddedt** [comment]
According to that log the crash is caused by Neruina, not Embeddium.

**Comment by lynariel** [comment]
Thanks ! It's better ! I just launch the game and Forge is loaded but crash with Flywheel ! I'll investigate why now !

Thank you !

**Comment by lynariel** [comment]
I close this issue !
