### ISSUE TITLE
Crash when clicking Video Settings, with both Embeddium++ and Embeddium Extra, for certain language set

### ISSUE THREAD

**Issue by EnderHane** [FiniteReality/embeddium#287]
### Bug Description

see https://github.com/dima-dencep/rubidium-extra/issues/78

### Reproduction Steps

Minecraft 1.20.1
Forge 47.2.30 or NeoForge 47.1.105
Embeddium 0.3.17+mc1.20.1
Embeddium++ 1.2.8
Embeddium Extra 0.5.4.3+mc1.20.1-build.121

(no other mods)

switch language to Français (France) and click the Video Settings button

### Log File

https://mclo.gs/EfOSnGi
https://mclo.gs/qH9cFxP

**Comment by embeddedt** [comment]
Thanks for the clear bug report; this is fixed in 0.3.18.
