### ISSUE TITLE
A new logo artwork

### ISSUE THREAD

**Issue by Safixoo** [FiniteReality/embeddium#29]
Not really a issue but rather a logo design that I made when I was bored that I think and hope that looks better than the actual embeddium logo
https://imgur.com/a/RMZ2EDS

**Comment by embeddedt** [comment]
Thank you! It looks very cool (and certainly better than my placeholder). However, out of respect for the upstream project, I don't want to use the same fire design as it might make people think Embeddium is an official fork of Sodium.

FYI, we have been discussing potential alternative logos on the Discord server - if you have any thoughts I'd love to hear them there.
