### ISSUE TITLE
White dots between blocks

### ISSUE THREAD

**Issue by Bruskych** [FiniteReality/embeddium#290]
### Bug Description

In dark places, many white dots begin to run between the blocks, which are located between the blocks. This is very annoying! It seems to me that I’m not the only one who encountered this

### Reproduction Steps

This can be seen very well in dark places (caves or in the shadows under blocks)
![2024-05-06_14 34 49](https://github.com/embeddedt/embeddium/assets/158246943/c1f7e68e-5fd5-4103-8c8b-9b7702b6e9bf)

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/15220753/latest.log)

**Comment by embeddedt** [comment]
We already have an issue open for this, so I'll close this one to keep the issue tracker organized. https://github.com/embeddedt/embeddium/issues/208#issuecomment-1949001234 is the currently recommended workaround.
