### ISSUE TITLE
Strange displacements & Keys' control problem.

### ISSUE THREAD

**Issue by 7777777-4547** [FiniteReality/embeddium#292]
### Bug Description

![PixPin_2024-05-12_22-29-36-ezgif com-optimize](https://github.com/embeddedt/embeddium/assets/83630775/7be26c52-531f-4d66-a3b0-289e4c0db173)

### Reproduction Steps

- Click the options which lower part the screen.

- Use keys to control the options' selections.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/15286733/latest.log)

**Comment by embeddedt** [comment]
Thanks, this should be fixed in 0.3.19.
