### ISSUE TITLE
Updated Embeddium version with loading specific biomes will become laggy

### ISSUE THREAD

**Issue by FlappiBakuse** [FiniteReality/embeddium#294]
### Bug Description

I'm using an Intel Arc A770 graphics card with the latest graphics drivers, when I start the game with the latest Embeddium version and create worlds to load specific biomes (eg. jungle, mangrove swamp) the game will become extremely laggy (other biomes will not have this problem), this problem disappeared when I downgraded Embeddium to version 0.3.12.

The following two images will show the difference in performance between different Embeddium versions. (render distance are all set to 32)

![2024-05-14_15 47 02](https://github.com/embeddedt/embeddium/assets/111492950/57475557-b120-490f-aa09-03051509c874)

![2024-05-14_16 05 43](https://github.com/embeddedt/embeddium/assets/111492950/de0b1b00-691d-49b0-b795-132830377ba9)

### Reproduction Steps

1. Install only Embeddium and the latest Forge loader and start the game.
2. Create single biome world with jungle or mangrove swamp biomes.
3. Walk around randomly and the game starts to lag.

### Log File

[debug.log](https://github.com/embeddedt/embeddium/files/15305649/debug.log)
[latest.log](https://github.com/embeddedt/embeddium/files/15305650/latest.log)

**Comment by embeddedt** [comment]
Hi, thanks for opening an issue. Is performance with this test build similar to 0.3.12?
[test_build.zip](https://github.com/embeddedt/embeddium/files/15309643/test_build.zip)

**Comment by FlappiBakuse** [comment]
Yes, it looks much better now. Thanks for the work!

![2024-05-14_22 37 58](https://github.com/embeddedt/embeddium/assets/111492950/81b2fcbc-8f67-4cfc-bfc3-6da8341c9599)

**Comment by embeddedt** [comment]
That isn't a fix, it was just me verifying which change caused the problem. :laughing: I'm working on a proper fix now.

**Comment by embeddedt** [comment]
Okay, does this also fix the issue?

[fix.zip](https://github.com/embeddedt/embeddium/files/15310224/fix.zip)

**Comment by FlappiBakuse** [comment]
It looks like this version is more unstable compared to the last test version of frametime.

![2024-05-14_23 04 01](https://github.com/embeddedt/embeddium/assets/111492950/33d37c10-9c02-4b57-8e44-73d53ae719f9)

**Comment by embeddedt** [comment]
How about this?
[fix2.zip](https://github.com/embeddedt/embeddium/files/15310459/fix2.zip)

**Comment by FlappiBakuse** [comment]
It's pretty close to the first test version, but still feels like it has some minor lag.

![2024-05-14_23 20 44](https://github.com/embeddedt/embeddium/assets/111492950/584cbb7b-6943-4621-a0bc-84329447cdcc)

**Comment by embeddedt** [comment]
I think it will be close enough. The original test version isn't suitable because it reverts a fix for a crash. The new code strikes a balance between attempting to emulate the old behavior enough to not cause significant lag, while also preventing the excessive memory usage that caused the crash in the first place.

**Comment by FlappiBakuse** [comment]
I think there's not a problem, at least it's already in a fully playable state, thanks again for your work.

**Comment by embeddedt** [comment]
The fix has been released in 0.3.19.
