### ISSUE TITLE
Textrue's Rubidium/Embeddium Options is both required but incompatible....

### ISSUE THREAD

**Issue by RandomGuy91** [FiniteReality/embeddium#295]
### Bug Description

When loading a custom modpack I'm making with embeddium-0.3.18+mc1.20.1-all.jar installed, an error occurs. (see photo below)
I have tried it without Texture's Options, but then it says that it is required. I don't believe there is a version of that mod with the specified version so I am assuming it is a bug. 

![Minecraft_ Forge Loading  5_15_2024 8_43_07 AM](https://github.com/embeddedt/embeddium/assets/107836342/1d63ddc0-4728-4e17-bdb0-7b549096eeb7)

Here is a list of the mods I am using in case you need them:
Additional Structures (by XxRexRaptorxX)
AI Improvements (by QueenOfMissiles)
Alex's Delight (by NCP_Bails)
Alex's Mobs (by sbom_xela)
Allurement (by TeamAbnormals)
AmbientSounds 6 (by CreativeMD)
Anvil Restoration (by Serilum)
AppleSkin (by squeek502)
Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
Armor Statues [Forge & Fabric] (by Fuzs)
Artifacts (by ochotonida)
AttributeFix (by DarkhaxDev)
Autumnity (by TeamAbnormals)
Bagus Lib (by bagu_chan500)
Balm (Forge Edition) (by BlayTheNinth)
Better Advancements (by way2muchnoise)
Better Archeology (by Pandarix)
Better Burning (by DarkhaxDev)
Better chunk loading[Forge/Fabric] (by someaddon)
Better Fps - Render Distance[Forge] (by someaddon)
Better Invisibility (by Purplicious_Cow_)
Better Mods Button [Forge] (by Fuzs)
Better Smithing Table (by jjblock21)
Better Spawner Control (by Serilum)
Better Than Mending (by legobmw99)
Better Third Person (by Socolio)
Better Villages - Forge (by jtl_elisa)
BetterF3 (by cominixo)
Blue Flame Burning (by LobsterJonn)
Blueprint (by TeamAbnormals)
Boatload (by TeamAbnormals)
Bookshelf (by DarkhaxDev)
Bottle Your Xp (by Serilum)
Buzzier Bees (by TeamAbnormals)
Bygone Nether (by izofar)
Caelus API (Forge/NeoForge) (by TheIllusiveC4)
Carpeted Stairs & Slabs (by MehVahdJukaar)
Carry On (by Tschipp)
Catalogue (by MrCrayfish)
Charm of Undying (Fabric/Forge/Quilt) (by TheIllusiveC4)
Cherished Worlds (Fabric/Forge/NeoForge/Quilt) (by TheIllusiveC4)
Citadel (by sbom_xela)
Clickable advancements[Forge/Fabric] (by someaddon)
Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)
Clumps (by Jaredlll08)
CoFH Core (by TeamCoFH)
Collective (by Serilum)
Colytra (Fabric/Forge/Quilt) (by TheIllusiveC4)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Conduits Prevent Drowned (by Serilum)
Configured (by MrCrayfish)
Configured Defaults [Forge & Fabric] (by Fuzs)
Controlling (by Jaredlll08)
Corail Woodcutter (by Corail_31)
CreativeCore (by CreativeMD)
Crying Portals (by Serilum)
Cupboard (by someaddon)
Curios API (Forge/NeoForge) (by TheIllusiveC4)
Delightful (by brnbrd)
Diagonal Fences [Forge & Fabric] (by Fuzs)
Diagonal Walls (by Fuzs)
Diagonal Windows [Forge & Fabric] (by Fuzs)
Distant Horizons: A Level of Detail mod (by James_Seibel)
Dungeon Crawl (by xiroc_)
Dungeons Enhanced (by Valarauko9)
Dungeons Plus (by ModdingLegacy)
Easy Anvils [Forge & Fabric] (by Fuzs)
Easy Magic [Forge & Fabric] (by Fuzs)
Easy Shulker Boxes [Forge & Fabric] (by Fuzs)
Eating Animation [Forge] (by matyrobbrt)
Effect Descriptions [Forge & Fabric] (by Fuzs)
Effect Tooltips (by DarkhaxDev)
Embeddium (by embeddedt)
Embeddium/Rubidium Dynamic Lights (by Anthxny)
Embeddium/Rubidium Extras (by Anthxny)
Enchantment Descriptions (by DarkhaxDev)
End Remastered (by jack_bagel)
End's Delight (by foggyhillside)
Ensorcellation (by TeamCoFH)
Every Compat (Wood Good) (by MehVahdJukaar)
Explorify – Dungeons & Structures (by bebebea_loste)
Extended Bone Meal (by Serilum)
Extended Slabs + | Now on 1.20.1 (by RealBlackout03)
Farmer's Delight (by vectorwing)
Fastload (by StockiesLad)
FastSuite (by Shadows_of_Fire)
FindMe (by Buuz135)
Flower Seeds 2 (by Trhod177)
Food Effect Tooltips (Forge) (by Suel_ki)
FPS Reducer (by bre2el)
Framework (by MrCrayfish)
Furnace Recycle (by Serilum)
Golden Hopper (by MrCrayfish)
GroovyModLoader (GML) (by matyrobbrt)
Guard Villagers (by almightytallestred)
Hunter'sReturn (by bagu_chan500)
I didn't mean it that way (by LobsterJonn)
Illager Invasion [Forge & Fabric] (by Fuzs)
Illagers Wear Armor (by almightytallestred)
Just Enough Archaeology (by LobsterJonn)
Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)
Just Enough Items (JEI) (by mezz)
KleeSlabs (by BlayTheNinth)
Library Ferret - Forge (by jtl_elisa)
Memory Settings[Forge/Fabric] (by someaddon)
Moonlight Lib (by MehVahdJukaar)
Mouse Tweaks (by YaLTeR)
Neko's Enchanted Books (by Nekomaster1000)
Placebo (by Shadows_of_Fire)
Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Sawmill (by MehVahdJukaar)
Searchables (by Jaredlll08)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
Structure Gel API (by ModdingLegacy)
Supplementaries (by MehVahdJukaar)
TexTrue's Embeddium Options (by TexTrue)
Visuality: Reforged (by DragonsPlus)
Xaero's Minimap (by xaero96)
Xaero's World Map (by xaero96)
YUNG's API (Forge) (by YUNGNICKYOUNG)

### Reproduction Steps

Run embeddium-0.3.18+mc1.20.1-all.jar with any version of Textrue's Rubidium/Embeddium options. 

### Log File

Not a log, but a crash report as I can't find a log for this startup:
[crash-2024-05-15_08.42.58-fml.txt](https://github.com/embeddedt/embeddium/files/15321742/crash-2024-05-15_08.42.58-fml.txt)

**Comment by embeddedt** [comment]
This is not an Embeddium bug, the "Embeddium/Rubidium Extras" mod (the one *without* an s) add-on marked as requiring TEO, for (as far as I'm aware) no real purpose. The best solution for now will be to remove that mod and replace it with Embeddium++.

**Comment by RandomGuy91** [comment]
Got it, thanks.
