### ISSUE TITLE
Factory Blocks textures don't connect

### ISSUE THREAD

**Issue by TheLexxxor** [FiniteReality/embeddium#298]
### Bug Description

I have a rather specific problem,
Me and some friends are playing a custom modpack and one of the mods is an addon for the chisel reborn mod with the name Factory Blocks and as long as i dont use Embeddium the connected textures are working fine but as soon as i add Embeddium to the pack only the connected textures from factory Blocks are broken and are only displayed as a normal single block as seen in the screenshot

![2024-05-18_11 53 43](https://github.com/embeddedt/embeddium/assets/18227311/1f3fe28a-172e-438b-b14b-b8b233cbbf17)

This is how they should look like 
![image](https://github.com/embeddedt/embeddium/assets/18227311/0659ebbc-9e23-4f17-aca4-8c6477981ef0)

### Reproduction Steps

Here is the modlist of our pack if needed 

### Log File

Here is the modlist of our pack if needed 

[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[RightClickHarvest (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/rightclickharvest)
[Brizzle's Mystic Paintings (by BrizzleWCBW)](https://www.curseforge.com/minecraft/mc-mods/brizzles-mystic-paintings)
[ManyIdeas Doors (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/manyideas-doors)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Brizzle's Anime Paintings (by BrizzleWCBW)](https://www.curseforge.com/minecraft/mc-mods/brizzles-anime-paintings)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[Pocket Storage (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/pocket-storage)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[Macaw's Fences - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-biomes-o-plenty)
[Industrial Foregoing (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing)
[Iron Chests: Restocked (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/ironchests)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Time in a bottle [FORGE] (by MangoRage)](https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle-forge)
[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
['Dustrial Decor (by BlueDuckYT)](https://www.curseforge.com/minecraft/mc-mods/dustrial-decor)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Wooden Hopper (by thecech12)](https://www.curseforge.com/minecraft/mc-mods/wooden-hopper)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/lendercataclysm)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Inventory Profiles Next (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next)
[Only Excavators [FORGE/FABRIC] (by Block_Legend001)](https://www.curseforge.com/minecraft/mc-mods/only-excavators-forge-fabric)
[The One Probe (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
[Workshop for handsome adventurer (by MoonFather)](https://www.curseforge.com/minecraft/mc-mods/workshop-for-handsome-adventurer)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[MOA DECOR: HOLIDAYS (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-holidays)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[Immersive Engineering (by BluSunrize)](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[MOA DECOR: ART (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-art)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Dramatic Skys (by thebaum64)](https://www.curseforge.com/minecraft/texture-packs/dramatic-skys)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[MultiBeds (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/multibeds)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Sinytra Connector (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector)
[Metal Barrels (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/metal-barrels)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Gaming Deco (by PlayTics)](https://www.curseforge.com/minecraft/mc-mods/gaming-deco)
[LibX (by noeppinoeppi)](https://www.curseforge.com/minecraft/mc-mods/libx)
[Refined Storage (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
[Paragliders (by Tictim)](https://www.curseforge.com/minecraft/mc-mods/paragliders)
[Cyclic (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/cyclic)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended)
[Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Flux Networks (by sonar_sonic)](https://www.curseforge.com/minecraft/mc-mods/flux-networks)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Macaw's Furnitures - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-biomes-o-plenty)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Immersive Melodies [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-melodies)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Botany Pots (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
[Iron Jetpacks (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks)
[Plain Grinder (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/plain-grinder)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Refined Polymorphism (by ninety)](https://www.curseforge.com/minecraft/mc-mods/refined-polymorphism)
[Curious Armor Stands (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands)
[cozy cottage (by elio)](https://www.curseforge.com/minecraft/mc-mods/cozy-cottage)
[ExtraStorage (by 3divad99)](https://www.curseforge.com/minecraft/mc-mods/extrastorage)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Motschen's Better Leaves (by Motschen)](https://www.curseforge.com/minecraft/texture-packs/motschens-better-leaves)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[MOA DECOR: GARDEN (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-garden)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[MOA DECOR: LIGHTS (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-lights)
[Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)
[Mystical Customization (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-customization)
[Fetzi's Asian Decoration (by NotFetzi)](https://www.curseforge.com/minecraft/mc-mods/fetzis-asian-decoration)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[MOA DECOR: COOKERY (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-cookery)
[Forgified Fabric API (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[The Mushrooms (by leo1011101)](https://www.curseforge.com/minecraft/mc-mods/the-mushrooms)
[Only Hammers [FORGE/FABRIC] (by Block_Legend001)](https://www.curseforge.com/minecraft/mc-mods/only-hammers-forge-fabric)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Tesseract (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/tesseract)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[Additional Lights (by mgen256)](https://www.curseforge.com/minecraft/mc-mods/additional-lights)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Items Displayed [Forge] (by FREEDINNER)](https://www.curseforge.com/minecraft/mc-mods/items-displayed-forge)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Craft slabs back into blocks [Fabric/Forge/NeoForge] (by Mars)](https://www.curseforge.com/minecraft/mc-mods/craft-slabs-back-into-blocks)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[[1.20.1] OpenStairs (by HookerHeels)](https://www.curseforge.com/minecraft/mc-mods/openstairs)
[Chisel Reborn (by Slaincow)](https://www.curseforge.com/minecraft/mc-mods/chisel-reborn)
[TrimsEffects (by Lupin)](https://www.curseforge.com/minecraft/mc-mods/trimseffects)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[libIPN (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/libipn)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[More Music Discs (Records) (by neon_cranberries)](https://www.curseforge.com/minecraft/mc-mods/more-music-discs-records)
[Faithful 64x (by Faithful_Resource_Pack)](https://www.curseforge.com/minecraft/texture-packs/faithful-64x)
[Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[Twigs (by ninnih_)](https://www.curseforge.com/minecraft/mc-mods/twigs)
[FramedBlocks (by XFactHD)](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[Dark Paintings (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Zeta (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/zeta)
[Decorative Gaming Consoles (by maxsteelbro)](https://www.curseforge.com/minecraft/mc-mods/decorative-gaming-consoles)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Mystical Agradditions (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions)
[ManyIdeas Core (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/manyideas-core)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Macaw's Bridges - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty)
[Simple Hats (by fonnymunkey)](https://www.curseforge.com/minecraft/mc-mods/simplehats)
[Recipes Library (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/recipes-library)
[MOA DECOR: TOYS (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-toys)
[Refined Storage Addons (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Pam's HarvestCraft 2 - Trees (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Xray Ultimate (by Filmjolk)](https://www.curseforge.com/minecraft/texture-packs/xray-ultimate-1-11-compatible)
[MOA DECOR: BATH (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-bath)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Sword Displays (by sokratis12GR)](https://www.curseforge.com/minecraft/mc-mods/sword-displays)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[Refined Storage: Requestify (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/rs-requestify)
[Re:Deco (by oopsonlydelta)](https://www.curseforge.com/minecraft/mc-mods/redeco)
[Factory Blocks (by Slaincow)](https://www.curseforge.com/minecraft/mc-mods/factory-blocks)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[Beautify! (by Pandarix)](https://www.curseforge.com/minecraft/mc-mods/beautify-decorate)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[ExpandAbility (by florensie)](https://www.curseforge.com/minecraft/mc-mods/expandability)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[ShetiPhianCore (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Knaves' Needs (by KodoDenka)](https://www.curseforge.com/minecraft/mc-mods/knaves-needs)
[GraveStone Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Pam's HarvestCraft 2 - Crops (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)
[Simple Decorations: Soft and Squishy (by JestemZbychu)](https://www.curseforge.com/minecraft/mc-mods/soft-and-squishy)
[Mystical Agriculture (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Travel Anchors (by CastCrafter)](https://www.curseforge.com/minecraft/mc-mods/travel-anchors)
[Monster Plus (by Nitespring)](https://www.curseforge.com/minecraft/mc-mods/monster-plus)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[Better Dogs X Doggy Talents Next (by mrblueyeti)](https://www.curseforge.com/minecraft/mc-mods/better-dogs-x-doggy-talents-next)
[Cluttered (by beelake)](https://www.curseforge.com/minecraft/mc-mods/cluttered)
[Fay's Cottagecore Details (by i_be_alex)](https://www.curseforge.com/minecraft/mc-mods/fays-cottagecore-details)
[Doggy Talents Next (by dashiedev)](https://www.curseforge.com/minecraft/mc-mods/doggy-talents-next)
[EdivadLib (by 3divad99)](https://www.curseforge.com/minecraft/mc-mods/edivadlib)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Magic Vibe Decorations (Crystals, Halloween additions) (by LillouArts)](https://www.curseforge.com/minecraft/mc-mods/magic-vibe-decorations)
[Modonomicon (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[Dynamic Lights (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Decorative Pavers (by Alexander8VKHZ)](https://www.curseforge.com/minecraft/mc-mods/decorative-pavers)
[Why stacks of 16? (by LaidBackSloth)](https://www.curseforge.com/minecraft/mc-mods/why-stacks-of-16)
[CosmeticArmours (by iiJowonny)](https://www.curseforge.com/minecraft/mc-mods/cosmeticarmours)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[More Villagers (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/more-villagers)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[Fantasy's Furniture (by ApexModder)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)
[Mekanism-MoreSolarPanels (by Pocky)](https://www.curseforge.com/minecraft/mc-mods/mekanism-moresolarpanels)
[FLIB (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/flib)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Night Lights (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/nightlights)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Titanium (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/titanium)
[HammerLib (by Zeith)](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)

**Comment by embeddedt** [comment]
Since you didn't provide version numbers, I'll assume you're playing 1.20.1. I tried installing just Embeddium 0.3.19, Chisel Reborn 1.7.1, Athena 3.1.2, and Factory Blocks 1.3.1. The connected textures rendered without issues. Have you tested this in isolation to ensure it's not an issue with another one of your mods?

![2024-05-18_10 48 23](https://github.com/embeddedt/embeddium/assets/42941056/0de422f4-126b-486d-9f4b-0ae67f4f0842)

**Comment by TheLexxxor** [comment]
ah sorry, i totally forgot to mention the game version we are using.
but it seems like that the fault is the current version of factory blocks, i used a newer version and it partly fixed itself
