### ISSUE TITLE
Since the update including Textrues Embeddium Options my game just crashes when loading.

### ISSUE THREAD

**Issue by padraigpearse** [FiniteReality/embeddium#299]
### Bug Description

I updated to Embeddium 0.3.19 and because the Embeddium Options mod is no longer needed/compatible I deleted it but now when i try to load up my game it just crashes with a null exception and error code -1.

### Reproduction Steps

Download 0.3.19update and delete Embeddium Options.

### Log File

[crash-2024-05-19_20.55.47-client.txt](https://github.com/embeddedt/embeddium/files/15370657/crash-2024-05-19_20.55.47-client.txt)

**Comment by embeddedt** [comment]
Please provide the full `latest.log` file; at first glance the crash appears unrelated to Embeddium.

**Comment by padraigpearse** [comment]
here's the latest .log file [latest.log](https://github.com/embeddedt/embeddium/files/15378107/latest.log)

**Comment by embeddedt** [comment]
The crash appears to be caused by one of Every Compat, Excessive Building, or Builder's Additions. Not sure which, but Embeddium doesn't seem to be involved.

**Comment by padraigpearse** [comment]
oh right ok thanks sorry for bothering you! :)

**Comment by embeddedt** [comment]
No problem.
