### ISSUE TITLE
[1.20.1] Oculus is not yet compatible

### ISSUE THREAD

**Issue by jburrows82** [FiniteReality/embeddium#3]
Minecraft 1.20.1
Windows 11/GraalVM 17.0.8 (22.3.3)
Neoforge 47.1.75

[crash-2023-08-31_23.34.42-client.txt](https://github.com/embeddedt/embeddium/files/12494103/crash-2023-08-31_23.34.42-client.txt)

[debug.log](https://github.com/embeddedt/embeddium/files/12494119/debug.log)

[latest.log](https://github.com/embeddedt/embeddium/files/12494120/latest.log)

**Comment by embeddedt** [comment]
You unfortunately can't use Oculus yet as it's designed for Rubidium 0.6, while Embeddium was forked from 0.7.

**Comment by Cixon** [comment]
was just about to post about this, thanks

**Comment by uhloin** [comment]
Here is my similar crash report for 1.20.1, neoforge 47.1.76, oculus 1.20-1.6.4
Second crash report is a failed launch of embeddium + nocubes
[crash-2023-09-07_23.04.53-client.txt](https://github.com/embeddedt/embeddium/files/12552759/crash-2023-09-07_23.04.53-client.txt)
[crash-2023-09-07_23.17.33-client.txt](https://github.com/embeddedt/embeddium/files/12552760/crash-2023-09-07_23.17.33-client.txt)

**Comment by gitguette** [comment]
> You unfortunately can't use Oculus yet as it's designed for Rubidium 0.6, while Embeddium was forked from 0.7.

if you made a fork that uses rubidium 0.6, could it work with sinytra connector?

**Comment by Tursiops-G** [comment]
If the current release of Embeddium isn't compatible with Oculus AT ALL, PLEASE remove the suggestion to USE Oculus from your Mod Description/Compatibility on Modrinth  & CF:

"**Compatibility**
Generally Embeddium should work out of the box with many more mods than Rubidium. However, given the scope of changes it makes to the renderer, it may have compatibility issues with some mods that use advanced rendering. Please open an issue if you experience problems. Some issues may require changes to be made in the other mod but it's good to have them documented.

OptiFine is not supported for obvious reasons.

**Shaders**
**For now, please continue to use [Oculus]**(https://www.curseforge.com/minecraft/mc-mods/oculus) if you want shader support. Note that Oculus is somewhat buggy, and your experience will probably be more stable without it. I recommend removing Oculus if you do not need shaders."

**Comment by SiverDX** [comment]
I don't really see the problem, the description is for the mod as a whole, not just the 1.20.x version

Just because there is no Sodium 0.5.x compatible Oculus version (meaning the latest Rubidium version for 1.20.x is also not compatible with Oculus) doesn't mean the statement is problematic

**Comment by embeddedt** [comment]
Oculus 1.6.9 and Embeddium 0.1.9 work together on 1.20.1. :rocket:

**Comment by uhloin** [comment]
Yes
But with NoCubes still does not work
[crash-2023-09-25_14.38.14-client.txt](https://github.com/embeddedt/embeddium/files/12714137/crash-2023-09-25_14.38.14-client.txt)

**Comment by embeddedt** [comment]
This looks like it will need to be fixed on NoCubes' end as that mod uses mixins into the vanilla world renderer.
