### ISSUE TITLE
Render thread crash (NeoForge / Connector) 

### ISSUE THREAD

**Issue by oof100200** [FiniteReality/embeddium#310]
### Bug Description

crash with ultracraft mod

### Reproduction Steps

crash with ultracraft mod

### Log File

https://pastebin.com/3CYbruvR

**Comment by embeddedt** [comment]
The mod injects an [extra chunk render layer](https://github.com/absolutelyaya/ultracraft/blob/a19f3583ac2d164be09518d9e026c74f0431b035/src/main/java/absolutelyaya/ultracraft/mixin/client/render/RenderLayerMixin.java#L22), which is not something any modloader currently provides an API for (as it has significant implications for performance, among other things). Most rendering optimization mods also don't support this. 

They do appear to detect the presence of Sodium, and disable this feature, so adding a mod alias for Sodium in Connector's config should solve the problem; please ask on the Connector Discord server if you need instructions on how to do that.
