### ISSUE TITLE
The mod stopped working with Valkyrien Skies

### ISSUE THREAD

**Issue by X0GEM** [FiniteReality/embeddium#313]
### Bug Description

Minecraft does not start

### Reproduction Steps

Launching Minecraft

### Log File

[tl-logger84902080066362889.txt](https://github.com/user-attachments/files/15830808/tl-logger84902080066362889.txt)

**Comment by embeddedt** [comment]
I cannot reproduce this in a standalone instance with Embeddium & Valkyrien Skies, and the error in your log is from VS, not Embeddium. Please verify that this isn't caused by another mod.

**Comment by X0GEM** [comment]
Yes, you're right, I just noticed that Kotlin is needed for Valkyrie Skies, I thought I would have time to remove the request, but you respond quickly, thank you for your wonderful mod, I hope you will continue to do it, this mod is incredible

> I cannot reproduce this in a standalone instance with Embeddium & Valkyrien Skies, and the error in your log is from VS, not Embeddium. Please verify that this isn't caused by another mod.
