### ISSUE TITLE
Partially transparent blocks render differently than vanilla

### ISSUE THREAD

**Issue by zChenX1** [FiniteReality/embeddium#314]
### Bug Description

Partially transparent blocks render differently than vanilla
As shown in the picture below:
![image](https://github.com/embeddedt/embeddium/assets/94461675/2d9ff8f5-c294-4179-96d0-9c2c9d9f7da2)
↑Embeddium(Mod version: 0.3.20+mc.1.20.1)
![image](https://github.com/embeddedt/embeddium/assets/94461675/2d9ff8f5-c294-4179-96d0-9c2c9d9f7da2)
↑Vanilla(1.20.1)

Sodium also has this problem

### Reproduction Steps

Placing slime blocks and honey blocks arbitrarily has this problem

Water too

### Log File

[latest.log](https://github.com/user-attachments/files/15856178/latest.log)

**Comment by embeddedt** [comment]
Enable translucency sorting in video settings.

**Comment by zChenX1** [comment]
> Enable translucency sorting in video settings.

Thankfully, I didn't check carefully
