### ISSUE TITLE
Industrial Revolution liquids don't render with embeddium

### ISSUE THREAD

**Issue by NolanHewitt** [FiniteReality/embeddium#316]
### Bug Description

Molten Gold and Molten Iron are both invisible when using embeddium. Without it, it displays normally. On sodium they render with incorrect colors, and it effects more of the molten liquids. Since this is based off of sodium maybe its connected in some way. [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution)

### Reproduction Steps

Run the game using just industrial revolution and its requirements, these ores look fine. Add embeddium and these now two are now invisible, though the other molten liquids render normally. This was tested on quilt, but I did make a fabric instance to test this as well and the same issue also happens on fabric.

### Log File

[latest.log](https://github.com/user-attachments/files/15860668/latest.log)

**Comment by embeddedt** [comment]
You can use the build from https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Ffabric/Embeddium.zip until I have a chance to release 0.3.21.

**Comment by embeddedt** [comment]
0.3.21 has been released.
