### ISSUE TITLE
Sodium version 1.5.8 to 1.5.10

### ISSUE THREAD

**Issue by Grass69z** [FiniteReality/embeddium#317]
### Bug Description

For Iris 1.7.1 it requires 1.5.10 of sodium to work but Embeddium has sodium version 1.5.8

### Reproduction Steps

Have Embeddium 0.3.2 and Iris 1.7.1 then launch you won't be able to because it says you need 1.5.10 of sodium not 1.5.8

### Log File

[latest.log](https://github.com/user-attachments/files/15877798/latest.log)

**Comment by embeddedt** [comment]
Duplicate of #312
