### ISSUE TITLE
Wings Reborn bug

### ISSUE THREAD

**Issue by ventibrot** [FiniteReality/embeddium#318]
### Bug Description

The wings reborn mod, on version 1.20.1, has an incompatibility glitch, in where some of the wing variants are not visible. Any wings with "feathers" are instead plucked to look like chicken wings. The only wings that are fully visible are the insect wings. All other mods as seen in the log were not causing the same bug, thus ruled out emeddium to be the issue.

### Reproduction Steps

Install: Using Curseforge 1.20.1-47.3.0
Wings Reborn version 1.20.1-2.1.4
Oculus 1.20.1-1.7
Embeddium 1.20.1-0.3.20 

bug also persists with Embeddium++ installed

### Log File

[2024-06-18-7.log.gz](https://github.com/user-attachments/files/15882921/2024-06-18-7.log.gz)

**Comment by embeddedt** [comment]
Please provide instructions on how to wear a wing variant that showcases the issue.

**Comment by ventibrot** [comment]
In the creative search bar, search wing, 10 potion bottles with different wing variants should appear. Drink the angel wing potion, then change your pov to third person to view the wings. The wings are still functional, but are missing their feathers. Drink the dragon wings to see the same effect, as well as the flame wings. The only wings that have the correct textures are the Monarch Butterfly wings, Slime wings, Blue butterfly wings, and fairy wings.

**Comment by embeddedt** [comment]
Got it, I looked at the code and I have an idea of what causes the issue. Fixing it properly while maintaining shader compat will be annoying because of how Iris is designed; might do the same workaround I did for bendy-lib for now.

**Comment by ventibrot** [comment]
Please let me know if you do find/make a fix for it! Thank you <33

**Comment by embeddedt** [comment]
The latest beta (https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip) includes a fix for this issue. The fix will not have any effect if Iris/Oculus are installed (even if shaders are disabled) because they duplicate the problematic code, which I cannot solve on my end.

It may take 5-10 minutes for the beta to update with the change.

**Comment by embeddedt** [comment]
Released the fix in 0.3.22
