### ISSUE TITLE
Is there no fabric version of embeddium 1.0?

### ISSUE THREAD

**Issue by BlackRiceXY** [FiniteReality/embeddium#319]

**Comment by embeddedt** [comment]
That's correct. Fabric support is currently on hold as the project is now maintained by only one developer (me) and I don't have time to support both modloaders at the level I want. The focus is on NeoForge for the time being; it can still be used with vanilla servers.

**Comment by seriousfreezing** [comment]
I'm quite saddened by this news, as I like Embeddium much more for shortening 2 mods.
But I'd ask you to post somewhere or in a changelog that Fabric won't be supported for now.

**Comment by embeddedt** [comment]
I made an announcement on Discord about this but I've also added the link to the changelog now; thanks for the suggestion.
