### ISSUE TITLE
[Backport request] 0.3.20 version for 1.20.4

### ISSUE THREAD

**Issue by Anonyku05** [FiniteReality/embeddium#320]
### Request Description

Hi, as said in the title, i would like to know if it's possible to backport the 0.3.20 embeddium version for Minecraft 1.20.4, i have a minor issue with another mod that would likely be fixed with that embeddium's version

**Comment by embeddedt** [comment]
I don't plan to do this backport myself as it's not realistic for me to maintain many minor versions singlehandedly; I'd recommend using 1.20.1 or 1.20.6.
