### ISSUE TITLE
conflicts with the bendy-lib library

### ISSUE THREAD

**Issue by deadrabbit12** [FiniteReality/embeddium#321]
### Bug Description

conflicts with the emotecraft mod> more precisely with the bendy-lib library for it, which allows models to bend during animation; when the embendium mod is running, bending does not occur and many animations look clumsy and ugly

### Reproduction Steps

when the embendium mod is running, bending does not occur and many animations look clumsy and ugly

### Log File

%

**Comment by embeddedt** [comment]
Please verify that this issue occurs even when Iris/Oculus are not installed.

**Comment by deadrabbit12** [comment]
oculus is installed, and without Embedded there is no conflict, this is a conflict with the Embedded mod

**Comment by deadrabbit12** [comment]
To check, I also ran it with the Embedded mod and without the oculus the error is the same, so this is 100% a problem in Embedded

**Comment by embeddedt** [comment]
Please check whether the problem still occurs in the beta (https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip) without Oculus installed, the entity rendering optimization has been rewritten for better compatibility with these types of mods.

**Comment by deadrabbit12** [comment]
Yes, thank you, everything works great, now I'm happy with your mod

**Comment by deadrabbit12** [comment]
Why do you reject the oculus mod, will there be support for this mod in the future

**Comment by embeddedt** [comment]
I cannot fix it on my end. Iris/Oculus are designed very poorly, and duplicate substantial amounts of Sodium code inside them, so even after I fix a bug, Oculus often undoes the fix when installed.

**Comment by deadrabbit12** [comment]
Thank you very much for your answer I think this thread can be closed I am very grateful to you your mod is the best

**Comment by embeddedt** [comment]
Conflict fixed on my end in 0.3.22; Oculus will need to be updated for the fix to take effect when it's installed.
