### ISSUE TITLE
Group Embeddium Stubs for ModMenu

### ISSUE THREAD

**Issue by CompeyDev** [FiniteReality/embeddium#323]
### Request Description

On ModMenu, the embeddium injected stubs are separate from Embeddium itself - would it be possible to use their API and group them under the main Embeddium mod entry?

See [parent grouping](https://github.com/TerraformersMC/ModMenu?tab=readme-ov-file#parents-parent-mod_id-or--).

**Comment by embeddedt** [comment]
I'll check again, but I remember trying this and finding some major issue that made it impractical - it may have been that Sodium addons that set Sodium as a parent stopped appearing in the menu at all (i.e. the grouping only works one layer deep), but I'm not 100% sure.

**Comment by embeddedt** [comment]
Yeah, can't be done unless something changes in Mod Menu. The addons stop appearing in the menu at all once I do the grouping, which is much more confusing for users.

![2024-06-30_16-41](https://github.com/embeddedt/embeddium/assets/42941056/95faa284-c272-4107-96c1-1d8a941436ff)

![2024-06-30_16-41_1](https://github.com/embeddedt/embeddium/assets/42941056/68da116a-63ac-4a4e-8dec-bfe291468a7c)

**Comment by CompeyDev** [comment]
What's wrong with the first? It's clear that they're provided my embeddium. I'd say clearer than having to read the description.

**Comment by embeddedt** [comment]
Sodium Extra (an add-on) disappears from the mods list altogether. It doesn't appear under Embeddium, Sodium, or by itself.
