### ISSUE TITLE
Bliss shaders support

### ISSUE THREAD

**Issue by GitCodMaster** [FiniteReality/embeddium#325]
### Request Description

i have noticed that Embeddium isn't compatible with bliss shaders for Distant Horizons mod, but Sodium is. So i please you to add support for these shaders because they just look awesome.
![2024-06-24_14 14 14](https://github.com/embeddedt/embeddium/assets/158101468/18189d73-44a4-4485-8413-989454bf87f9)

**Comment by embeddedt** [comment]
This should be reported to Oculus; Embeddium does not have built-in support for shaderpacks.
