### ISSUE TITLE
The problem of entity mappings

### ISSUE THREAD

**Issue by Anarchist-BallistixOFFICAL** [FiniteReality/embeddium#326]
### Bug Description

The other day I wanted to add "Create physics mods to my build: interactive, valkyrien skies, eureka airships, clockwork".  These mods worked, but there was a problem with the creatures not being displayed. I looked for the problem for a long time and it turned out that due to the poor compatibility of these mods with Embeddium, they caused a problem in the rendering of entities. I would like to ask the authors of Embeddium when mod compatibility will appear. 
I would remove Embeddium from the build, but my FPS in the game drops significantly.

- You may ask why I wrote about this on Github?

- I just wanted to ask when these mods will be compatible.

### Reproduction Steps

Install these mods:
Create
Clockwork
Create: Interoctive
valkyrien skies
eureka airships
Embeddium
And start the game and go into the world

### Log File

Logs were lost during cleanup computer disk
[logs.log](https://github.com/user-attachments/files/15994309/logs.log)

**Comment by embeddedt** [comment]
Valkyrien Skies (which all of these mods use as a base, to my knowledge) implements Embeddium compatibility on their end using mixin patches; I would suggest directing this question to them.
