### ISSUE TITLE
[1.20] Crash with Snow Real Magic

### ISSUE THREAD

**Issue by litjohn50** [FiniteReality/embeddium#33]
embeddium-0.1.7+mc1.20.1
Forge 47.1.3

Steps to recreate. So I was trying to speed up my fps on a modpack, and I added this mod it loads. But when I joined the server it threw a mixin crash.

https://gist.github.com/litjohn50/93209bce706e2c63648ff08caf05d3fc

**Comment by embeddedt** [comment]
This will have to be fixed on Snow Real Magic's end, as it's using [mixins to access Sodium internals](https://github.com/Snownee/SnowRealMagic/tree/1.20-forge/src/main/java/snownee/snow/mixin/sodium), which is not stable and could break with future updates, as happened here. I've added it to the incompatibilities list for posterity.
