### ISSUE TITLE
Allow mods to hook into the frustum update condition

### ISSUE THREAD

**Issue by forkiesassds** [FiniteReality/embeddium#331]
### Request Description

My mod depends on a mixin for Sodium that makes it so that the frustum update condition is controlled by a feature of the mod. It would be great if it was possible to do what I'm doing with the mixin through an event of sorts instead.

**Comment by embeddedt** [comment]
The latest version of Embeddium will respect setting the vanilla `needsFrustumUpdate` flag in `SectionOcclusionGraph` to true (for 1.21, a similar flag can be found in `LevelRenderer` for 1.20). Is this enough for your purposes?

**Comment by forkiesassds** [comment]
> The latest version of Embeddium will respect setting the vanilla `needsFrustumUpdate` flag in `SectionOcclusionGraph` to true (for 1.21, a similar flag can be found in `LevelRenderer` for 1.20). Is this enough for your purposes?

This seems enough for me. Didn't know there was a more better method though... I simply mixed into `setupRender` to be able to do so.
