### ISSUE TITLE
A very weird crash, not sure if Embeddium is the reason but it would be my guess

### ISSUE THREAD

**Issue by Aabyonis** [FiniteReality/embeddium#333]
### Bug Description

having a weird crash when opening JEI or creative inventory and searching for something, reading the logs im assuming its something to do with embeddium? not sure tho if you guys find out its not the mods fault i could redirect the issue to the mod that is responsible. It doesnt upright crash but instead freeze so i have to force crash the game in order to get out

### Reproduction Steps

written in description but this could also not be JEI or Embeddiums fault and could be a mod in the mod list, which is quite a big list

### Log File

[latest.log](https://github.com/user-attachments/files/16103190/latest.log)

**Comment by embeddedt** [comment]
Please test without Embeddium Extra installed.

**Comment by Aabyonis** [comment]
Ah thank you, that seems to have fixed it, but is there an alternative to Embeddium extra that i could use?
and also do you recommend i report this to them aswell?

**Comment by embeddedt** [comment]
> is there an alternative to Embeddium extra that i could use?

I am unfortunately not aware of any alternative at the moment.

> do you recommend i report this to them aswell?

Yes. The issue seems to be caused by some change they patch into Embeddium's internals; I am not sure what the purpose of it is.
