### ISSUE TITLE
MixinTaintDetector crashes game on launch

### ISSUE THREAD

**Issue by ModernGamingWorld** [FiniteReality/embeddium#334]
### Bug Description

Updated mod and crashed

### Reproduction Steps

Updated mod and crashed on Launch

### Log File

![2024-07-04_22 22 38](https://github.com/embeddedt/embeddium/assets/75923060/237aa3b8-f8bd-49aa-aada-bbebec81cbc5)
[latest.log](https://github.com/user-attachments/files/16104473/latest.log)

**Comment by dima-dencep** [comment]
Whoa, what's that? Another mod that hacks embeddium?

**Comment by embeddedt** [comment]
This is not an Embeddium bug. The impl classes are implementation details, which may change in any update, that mods should not interact with. They should only interact with API classes.

The weird part is that I have been in touch with this mod author, and they had designed the mod to only use APIs. So I'm not sure what happened here; maybe an outdated file was uploaded to CF/MR. I'd suggest reporting this to them.

**Comment by someaddons** [comment]
fixed in 4.4^^
