### ISSUE TITLE
Game black screens when I go to The End (Distant Horizons incompatibility?)

### ISSUE THREAD

**Issue by Hanyuu123** [FiniteReality/embeddium#335]
### Bug Description

Minecraft 1.16.5 Forge

Game black screens after I load in some chunks in The End after going through the portal. Everytime this happens I have to close Minecraft by clicking the X button on the window or with the task manager.

### Reproduction Steps

1) Download Distant Horizons and Embeddium

2) Go to The End and stay there for a few seconds, look around, load some chunks etc. sometimes it happens instantly sometimes it takes 2-3 seconds.

### Log File

https://gitlab.com/-/project/18204078/uploads/b65458f1c25398237036f78cf390390c/latest.log

### Example Picture

https://gitlab.com/-/project/18204078/uploads/9426ced70f5820a63c83f26dc302078d/image.png

**Comment by embeddedt** [comment]
Unfortunately, 1.16.5 is no longer supported. That said, judging by your log, the issue appears to be errors being thrown from DH's world generator, not Embeddium. So I would ask about this on the DH side.

**Comment by Hanyuu123** [comment]
> Unfortunately, 1.16.5 is no longer supported. That said, judging by your log, the issue appears to be errors being thrown from DH's world generator, not Embeddium. So I would ask about this on the DH side.

Yeah I reported this on that mod's issue tracker but I wanted to try my chance here as I couldn't get a response. Thank you for the reply anyways.
