### ISSUE TITLE
Water cauldrons do not show water, but other liquids work fine

### ISSUE THREAD

**Issue by vinnyg0621** [FiniteReality/embeddium#336]
### Bug Description

when I put some water in a cauldron, it looks empty. but it acts as if there's still water in it. but the water does not show in a water cauldron at any level. it works fine with _all_ other liquids like lava, milk, & colored water.
![2024-07-05_21 39 02](https://github.com/embeddedt/embeddium/assets/57818441/ecaba07f-6856-4a78-90d2-7f516e7a08d2)
![2024-07-05_21 40 08](https://github.com/embeddedt/embeddium/assets/57818441/dd97db4e-8e87-481d-9205-e45d2e7b86c0)
![2024-07-05_21 40 31](https://github.com/embeddedt/embeddium/assets/57818441/82a671dc-1098-4a9a-a879-e4655b8faf2e)
![2024-07-05_21 40 49](https://github.com/embeddedt/embeddium/assets/57818441/059cbe22-e225-40f5-bebe-540c20c9a748)

### Reproduction Steps

1. Place a cauldron
2. fill it with water
3. the water will not be there, so it will look empty

### Log File

[latest.log](https://github.com/user-attachments/files/16114888/latest.log)

**Comment by embeddedt** [comment]
Please remove Redirector and see if the issue still occurs. If it still happens, please try to narrow down what set of mods are needed to reproduce the issue - there is way too much installed here for me to guess. You may wish to start by searching for the log messages from `Embeddium-MixinTaintDetector`, and removing the mods noted there, but the culprit may not be listed there.

**Comment by vinnyg0621** [comment]
well, I see something in the log that says "Block minecraft:water_cauldron had its color provider replaced and will not use per-vertex coloring"
and I did remove redirector and it still doesn't render!

**Comment by embeddedt** [comment]
The water cauldron works fine in a standalone instance, so it is some type of mod conflict. Per-vertex coloring doesn't need to be in use for water to still render in it.

**Comment by embeddedt** [comment]
Closing as there are far too many mods installed to action this issue; please reopen/comment if you are able to isolate to a specific minimal set of mods.
