### ISSUE TITLE
[1.21] Crash on world load when the world has spawnChunkRadius set to zero

### ISSUE THREAD

**Issue by Tux-Prowess** [FiniteReality/embeddium#338]
### Bug Description

When loading a world, and that world has no spawn chunks (via SpawnChunkRadius set to 0), Embeddium will crash with a "Bufferbuilder was empty" error. This happens on any world with zero spawn chunks, including worlds created with SpawnChunkRadius already set to 0.

### Reproduction Steps

1. On a new Neoforge 1.21 instance with Embeddium installed, make a new world. Keep the spawn chunks at default on world creation. While in-game, set SpawnChunkRadius to 0.
2. Exit out of the world and re-enter the world.

### Log File

[latest.log](https://github.com/user-attachments/files/16117095/latest.log)

**Comment by embeddedt** [comment]
This issue was fixed in 1.0.5.
