### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by ChumbleDev** [FiniteReality/embeddium#339]
### Bug Description

World completely doesn’t load when I use embeddium, You can still see the block headers but no textures load in except for the sky and it’s just blank.
My mods are:
Sinytra Connecter
Fabric API (forge)
Immersive Portals
Embeddium

### Reproduction Steps

Launch a world with embeddium

### Log File

No log file

**Comment by embeddedt** [comment]
https://github.com/embeddedt/embeddium/issues/244#issuecomment-2020518528

**Comment by ChumbleDev** [comment]
> [#244 (comment)](https://github.com/embeddedt/embeddium/issues/244#issuecomment-2020518528)

I have already done that and it still does not load the world
