### ISSUE TITLE
Compatibility for Immersive Petroleum's Projector

### ISSUE THREAD

**Issue by TqLxQuanZ** [FiniteReality/embeddium#34]
This is a humble request for adding the compatibility with IP's Projector, as whenever it's paired with rubidium or embeddium, nothing will show up from it.

**Comment by embeddedt** [comment]
Can you provide instructions on exactly how I should use the projector to reproduce this? I haven't used this block before. I tried the most obvious way of using it, and I saw a halo in the world that appeared the same with and without Embeddium. My test instance just has IE, IP, and Embeddium installed.

**Comment by unilock** [comment]
More information can be found on Immersive Petroleum's bug tracker: https://github.com/TwistedGate/ImmersivePetroleum/issues/147

But, as I mentioned there, I've not experienced the issue with Embeddium, even in a larger modpack.

**Comment by embeddedt** [comment]
@TqLxQuanZ Can you confirm that you tested this with Embeddium, not Rubidium and still saw the issue?

**Comment by TqLxQuanZ** [comment]
Oh, interesting, I tested with the latest version and there's no issue with it anymore, strange I definitely saw it quite some time ago.
But thanks a lot! It works pretty well.
