### ISSUE TITLE
Explanation of the world not loading error

### ISSUE THREAD

**Issue by ChumbleDev** [FiniteReality/embeddium#342]
### Bug Description

This is not supposed to be a dupe of my last issue (#339) but rather an explanation 
1 - Yes I have tried adding embeddium to the connector config, does not fix my issue
2 - Yes I have tried disabling certain mods, does also not fix my issue

Id say it would just be connector incompatibility, but if there’s anything you know that could fix my issue, please reply to this or #339 
Thank you.

### Reproduction Steps

Launch any version of minecraft with Sinytra Connector and Embeddium

### Log File

No Log File.

**Comment by ChumbleDev** [comment]
I will continue trying to fix it.

**Comment by embeddedt** [comment]
Please ask in the Connector discord if you need support on this; they are more familiar with the necessary configuration.
