### ISSUE TITLE
crash embeddium-0.3.16+mc1.20.1-all 

### ISSUE THREAD

**Issue by NotSakura1** [FiniteReality/embeddium#348]
### Bug Description

I play on 1.20.1 with mods, in particular with oculus and embeddium. The very essence of the problem, the game enters calmly, you can play in the world, but as soon as I open the graphics settings, NOE warns about a crash drop of the game, referring to the mod specified in the topic, I tried both rubidium and embeddium in place and separately, if you remove the addon that adds shader support, then everything is fine, but this is not it, for obvious reasons. Crashlog below, if some information is not enough, then write - I will send, I just don't understand absolutely anything about it. System: Ryzen 3 3250U, Vega 3
P.S. I apologize for possible mistakes, I write through a translator due to my lack of knowledge of English. 

### Reproduction Steps

As I wrote above, when you install Embeddium and Oculus, the game starts normally, but it is impossible to change the graphics settings, since when you click on the button in the menu, Minecraft crashes. But at the same time, if you don't do this, then you can safely play, with a standard graphics preset.

### Log File

[crash-2024-07-14_23.02.24-client.txt](https://github.com/user-attachments/files/16228703/crash-2024-07-14_23.02.24-client.txt)
[latest.log](https://github.com/user-attachments/files/16228710/latest.log)

**Comment by embeddedt** [comment]
You should update to the latest version of Embeddium and remove TexTrue's Rubidium/Embeddium Options, as Embeddium includes the same features now. That will likely resolve the problem.
