### ISSUE TITLE
Please consider compatibility with model resource packages

### ISSUE THREAD

**Issue by Xiwang-99** [FiniteReality/embeddium#351]
### Bug Description

After using embeddium, the resource pack with block models will have the problem of texture block offset and misalignment. If the block model is rotated, the offset will be more serious, which will greatly affect the visual experience.

### Reproduction Steps

Loading a resource pack with block models

### Log File

none

**Comment by Xiwang-99** [comment]
Before using embeddium
![2FCFEA60124B4CFE89F6714E9F9374EE](https://github.com/user-attachments/assets/852535fc-3354-4d0d-a776-cbf9ac3ca166)
After using embeddium
![7D8DD555303FA2F9A91170A00E591603](https://github.com/user-attachments/assets/f5fa9742-3a5d-4c8f-b70d-e1695aec857a)

**Comment by embeddedt** [comment]
Disabling the compact vertex format in Video Settings should fix any alignment issues compared to vanilla at the cost of some performance (the cost varies depending on your GPU; it may not be a significant drop).
