### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by CJRemix98** [FiniteReality/embeddium#355]
### Bug Description

Trojan virus Message. 

### Reproduction Steps

Hello. Trying to download the embeddium on Curseforge, the second i try to do it with the newest version which is : 
1.07 1.21  and im unable to download it. There is no problem with downloading previous version but im asked to update it. Any answers?
I get a message : Mod file integrity failed. and my Windows defender pick ups trojan which deletes afterwards bit later.
![Przechwytywanie](https://github.com/user-attachments/assets/07db062a-6b58-4b63-8b12-1f06db44f263)
![Przechwytywanie](https://github.com/user-attachments/assets/b3dd2983-d9ff-4d2c-bd3f-40f51ffc6284)

### Log File

123

**Comment by CJRemix98** [comment]
![Bez tytułu](https://github.com/user-attachments/assets/05d940d5-4c1f-4695-8a0d-b0d3499dda1b)

update, when downloading it by browser.

**Comment by embeddedt** [comment]
It's a false positive; Microsoft Defender does this every so often. As far as I know, there is nothing I can do on my end. You can see that VirusTotal also [reports](https://www.virustotal.com/gui/file/e7b971db82fcae20e5386e837d2a1b697ace3e22a1d2ee57167d417c8ad2812b) the file is safe. You may be able to report an incorrect scan in Windows to prevent it from happening in the future.
