### ISSUE TITLE
Embeddium now crashes when on dedicated server.

### ISSUE THREAD

**Issue by Rushmead** [FiniteReality/embeddium#356]
### Bug Description

Version 0.3.25+mc.1.20.1 does not cause the server to crash if Embeddium is installed on it, 0.3.27+mc.1.20.1 crashes with `java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER` when loaded on the server.

### Reproduction Steps

1. Install latest Embeddium for 1.20.1 on Forge dedicated server

### Log File

[crash-2024-07-25_11.13.25-fml.txt](https://github.com/user-attachments/files/16376884/crash-2024-07-25_11.13.25-fml.txt)

**Comment by embeddedt** [comment]
Thanks, should be fixed in 0.3.28.

**Comment by Id-S-go** [comment]
Why would you put client mod on the server?
