### ISSUE TITLE
Support for Iris on NeoForge 1.21

### ISSUE THREAD

**Issue by VOLKOUL** [FiniteReality/embeddium#357]
### Request Description

Hi! I recently found out that Sodium and Iris are being ported to NeoForge (latest builds can be found on the Iris Discord), while Oculus won't receive any updates or releases for the newer versions (unconfirmed). Surprisingly, when using Embeddium instead of Sodium on NeoForge 1.21, the game launches and works perfectly fine with Iris! (without shaders) The problems arise when you enable any shader however. Well, visually there is only **_one_** problem: The world doesn't render and is completely invisible / transparent. The sky and light appear to be working though! I hope this will come to your attention and I wish you all the best :D

**Comment by embeddedt** [comment]
There is an addon in-development to enable this. It is a separate project from Embeddium, and will technically thus not be officially supported by Embeddium, but it should work, and should be available shortly after the official release of Iris, unless further complications arise.

Note that there may be mod compatibility issues when using Iris+Embeddium that don't exist with Embeddium by itself; this is a side effect of the assumptions made by shader packs.

**Comment by VOLKOUL** [comment]
Where can I learn more about the development of this addon and how it's called in the first place? Does it have a GitHub page or something similar?

**Comment by embeddedt** [comment]
https://github.com/ferriarnus/Monocle

We had public test builds in our Discord server, but had to put them on hold due to an issue we identified in how Iris licenses their code. We're going to release a new test build that avoids that issue soon :tm:.
