### ISSUE TITLE
Embeddium fails to load with the latest version of Iris from Discord on 1.20.1 Forge

### ISSUE THREAD

**Issue by AwesomeSavage** [FiniteReality/embeddium#359]
### Bug Description

Pretty much self-explainatory, but I should note that Iris says Sodium is not installed when trying to load the mods together. Also, Embeddium worked just fine with the previous alpha from the Iris Discord.

### Reproduction Steps

Install the latest version of Iris alpha from the Discord of Iris for 1.20.1 forge, and the latest version of Embeddium, and watch the game fail to load.

### Log File

[debug.log](https://github.com/user-attachments/files/16472967/debug.log)
[latest.log](https://github.com/user-attachments/files/16472968/latest.log)

**Comment by embeddedt** [comment]
This is not a bug; Iris is designed for Sodium 0.6, which Embeddium is not based on. Iris & Embeddium only work together with an extra add-on to add the necessary compatibility, which is in (private) testing, but is not yet available publicly.
