### ISSUE TITLE
Crash on clicking Embeddium's config button in Neo's config UI

### ISSUE THREAD

**Issue by ghost** [FiniteReality/embeddium#361]
### Bug Description

NeoForge: 21.0.163
Embeddium: 1.0.7+mc1.21

[ETA: Somehow managed to gist the wrong report/log initially, now fixed.]

A user on NeoForge's `#user-support` channel reported a crash in a very small modpack when trying to use Neo's new in-game config UI. Message link here: <https://discord.com/channels/313125603924639766/437001959950778368/1270822799606288384>.

I've managed to shrink the instance down to a single-mod reproducer containing just Embeddium.

### Reproduction Steps

1. Load clean instance as above
2. Main menu, click on `Mods` button
3. Select Embeddium and click `Config` button

### Log File

- [latest.log](https://gist.github.com/antiphysika/631aed5f4fed585bfd7c7a355c6e716c)
- [crash report](https://gist.github.com/antiphysika/8254f83e8dd6b550001b6f06bb65e53e)

**Comment by embeddedt** [comment]
This is already fixed; I have just been slow with a release since very few people actually use that config button.

**Comment by embeddedt** [comment]
Fixed in 1.0.9.
