### ISSUE TITLE
1.19.2 building chunk mesh crash

### ISSUE THREAD

**Issue by ink717** [FiniteReality/embeddium#362]
### Bug Description

this is at a low chance, as it only happened twice over the past 2 weeks. But both crash log looks somehow similar.
1.19.2 Forge, Mac Studio M2 Max, MacOS Sonoma 14

### Reproduction Steps

n/a

### Log File

[crash-2024-08-02_16.47.53-client.txt](https://github.com/user-attachments/files/16559303/crash-2024-08-02_16.47.53-client.txt)
[crash-2024-08-09_17.26.03-client.txt](https://github.com/user-attachments/files/16559304/crash-2024-08-09_17.26.03-client.txt)

**Comment by embeddedt** [comment]
The crash is caused by a bug in MrCrayfish's Furniture Mod (their shape calculation is not thread-safe, it needs to be for chunk meshing). You should report it to them; even if I still supported 1.19.2, there isn't anything I can do on my side to fix it.
