### ISSUE TITLE
game crashed with vivecraft on 1.21

### ISSUE THREAD

**Issue by Fury94-Echo** [FiniteReality/embeddium#363]
### Reproduction Steps

vivecraft-1.21-1.1.11-b5-neoforge
embeddium-1.0.7+mc1.21
neoforge-21.0.167

### Log File

[crash-2024-08-12_10.13.56-client.txt](https://github.com/user-attachments/files/16576871/crash-2024-08-12_10.13.56-client.txt)

**Comment by embeddedt** [comment]
Fixed in 1.0.9.
