### ISSUE TITLE
No animation with Bendy-lib

### ISSUE THREAD

**Issue by Stiles52** [FiniteReality/embeddium#364]
### Bug Description

The Bendy-Lib library used for player animator and emote craft does not handle body curves. Currently, animations are rigid. On Bendy-Lib's GitHub the problem is reported, but I'm taking the liberty of reporting it here too, as I don't know who can fix it.

We're in 1.20.1 under embeddium on the client.
Here's the outcome: https://github.com/KosmX/bendy-lib/issues/37

I hope you can do something about it because it would make the roleplay experience on our server more realistic ^^

Stiles

### Reproduction Steps

Simple installation of : 
- Player animator
- Emote craft
- Bendy lib

Prevents normal operation with embeddium

### Log File

//

**Comment by embeddedt** [comment]
This should already be fixed in the latest Embeddium version, please remove Oculus/Iris and check if it still happens; those mods overwrite the fix.

**Comment by Stiles52** [comment]
I see, is there another way to get shaders then? 

Or can I be contacted the mod developer and see for him to fix this on his side? 

I wanted to apologize if my translation is bad, I'm French and I go through a translator. 

Stiles

**Comment by embeddedt** [comment]
There is no other shaders mod, unfortunately. You would have to ask them if they're willing to fix it; they currently quite literally overwrite that part of Embeddium's code with theirs, so there is nothing I can do on my side.

**Comment by Stiles52** [comment]
Thank you for your reply! Well, I'll check with them, in any case thank you for your work and your response! Wishing you all the best ^^

**Comment by embeddedt** [comment]
Sorry I couldn't be of more help; my hands are quite tied when it comes to how Iris is designed.
