### ISSUE TITLE
[Feature request] A setting to render all the chunks around the player instead of rendering only visible ones

### ISSUE THREAD

**Issue by yellowcake3d** [FiniteReality/embeddium#366]
### Request Description

While playing embeddium with immersive portals I have encountered two visual bugs which you probably already know about.

One of the visual bugs in question is [this one](https://www.youtube.com/watch?v=yQDX9JDrgPs) (this is a link to a video of a bug) When chunks that are currently not visible from a player POV are visible from a portal POV, and are not being loaded because player can't see them because a player doesn't look at those chunks at the moment

I think that issue #132 adresses a similar bug

The solution I would like to propose is to add a setting for embeddium to also render chunks that are not currently visible from a player POV (Like chunks behind a player). While I understand that this option might not do good from optimisation point of view, enabling it might fix this visual bug. Although I'm unaware of the performance impact this sort of seting would do.

So this is more of a feature request of this particular setting, then a request to fix immersive portals visual bug that can't be properly fixed as you have clearly stated in the issue #132

**Comment by embeddedt** [comment]
If you are playing with IP on 1.16.5, Embeddium is no longer supported/updated on that version, so this won't get added.

If you are playing with IP on 1.18.2 or newer, I believe they include Sodium/Embeddium integration on their end, so if this visual issue still exists, you should report it to them, and it should be possible for them to fix.
