### ISSUE TITLE
Clicking "Video Settings" causes game to crash

### ISSUE THREAD

**Issue by ReeCodes** [FiniteReality/embeddium#367]
### Bug Description

Clicking the button "Video Settings" causes the game to crash.

### Reproduction Steps

Be in a world, then click on the Video Settings button.

### Log File

Crash log
https://mclo.gs/r5qSl4j

latest.log 
https://mclo.gs/YhBUTkB

**Comment by embeddedt** [comment]
This is an issue with a mixin from Bobby; I may be able to fix it, but there are better ways for them to accomplish what they need than using a mixin.

**Comment by embeddedt** [comment]
Fixed in 0.3.30.
