### ISSUE TITLE
Screen goes completely white when entering the nether

### ISSUE THREAD

**Issue by EvilDrone0800** [FiniteReality/embeddium#368]
### Bug Description

https://github.com/user-attachments/assets/648494ce-6334-407d-98ff-6d7156f7c335

https://github.com/user-attachments/assets/55617c77-2fe7-4e39-9218-a88ad0376915

Hello! I'm new to this so sorry if I'm not as clear as intended. I'm currently playing a custom modpack and just recently installed embeddium. Everything was fine until I entered the Nether. The first time, I took some steps and the screen goes white. After that, upon entering the portal it does the same thing, as the video shows. I spent hours searching for solutions, if there were any noticeable mod conflicts, but nothing helped. I guessed it was Embeddium since only after installing this mod the issue appeared. As I'm just a regular player, I thought this was a rendering issue, so installed oculus and turned a shaderspack on and voilá. A simple workaround, but I'm more interested in playing without shaders. I removed entity culling from the modpack. Tried all video setting. The only way to really stop the bug is removing embeddium or use a shaderspack alongside embeddium. Also, the video is the only thing which stops. Although I can only see the bright white, the game is still running and can be heard by the Ambient sound mod / Sound filters mod.
Anyways, this bug kind of weird and hopefully is just a conflict that I don't know of or something alike. But maybe this will help in the future. 

I'm playing on 1.16.5. There are many other mods, so I'll paste some screenshots of all of them just in case. I can send the modpack if needed. I'm sorry if this is a dumb post which has already been solved. Thanks in advance.
![Captura de tela 2024-08-16 011049](https://github.com/user-attachments/assets/106a1f99-df3e-4ae7-b1e3-0fd4976fac61)
![Captura de tela 2024-08-16 011106](https://github.com/user-attachments/assets/fc4069ef-4956-4210-90bc-1d12edbb7975)
![Captura de tela 2024-08-16 011117](https://github.com/user-attachments/assets/34aa18f5-9bca-43ae-ad41-3ab5cc8177ee)
![Captura de tela 2024-08-16 011127](https://github.com/user-attachments/assets/2a272b66-7cc8-4ebb-90ef-3f47ac4add5d)

### Reproduction Steps

Step 1: Having the mods installed, simply walk through the Nether Portal.
Step 2: Completely white screen.

### Log File

[latest.log](https://github.com/user-attachments/files/16632741/latest.log)

**Comment by embeddedt** [comment]
I don't provide official support for 1.16.5 anymore, and there are too many mods installed to narrow down the cause of the issue. I am suspicious this is a mod conflict so I would advise narrowing down the rest of the mods to determine which one is conflicting.

Additionally, the issue tracker is not intended for support requests, only bug reports that can be reproduced with a minimal mod set. Please use the [Discord server](https://discord.gg/rN9Y7caguP) for support requests.

**Comment by EvilDrone0800** [comment]
Oh my bad, I'm not really used to do this. Thanks for the reply! I tested
it out myself and found out that Distant Horizons version 2.1.2 was at
fault of the conflict, which was resolved by switching to version 2.1.0.
Maybe that helps? Anyways, great work with those mods!

Em sex., 16 de ago. de 2024 às 18:02, embeddedt ***@***.***>
escreveu:
