### ISSUE TITLE
Perspective phenomenon occurs when destroying a square or placing a square

### ISSUE THREAD

**Issue by ly05772** [FiniteReality/embeddium#369]
### Bug Description

In version 1.20.1 and forge47.3.0, only two mods, Embeddium and Embeddium++, are added. Whether it is survival mode or creation mode, when placing or destroying blocks in the main world, there will be striped or blocky perspectives, such as seeing a tree behind a wall, or seeing an underground mine.

### Reproduction Steps

In the case I mentioned above, placing or breaking a block in a specific position and orientation will trigger the bug. This is also very common in terms of position and orientation, and can usually be triggered by placing or breaking blocks while moving the character and adjusting the camera

### Log File

[latest.log](https://github.com/user-attachments/files/16643597/latest.log)

**Comment by embeddedt** [comment]
I do not think this is a bug. There are two things that can cause it:

* "Always Defer Chunk Updates" is enabled by default (like vanilla, although vanilla uses a different name for the option) which causes the game not to wait for all nearby chunks to update when breaking a block. This can cause a visual hole to appear in the world for a few frames. Disabling this option may help.
* Your game is using the integrated Intel iGPU, some older Intel drivers have issues with the whole world disappearing momentarily when breaking a block, if I recall correctly. Updating your drivers to the latest from Intel's website may help.

Without a video I'm not sure exactly which of these applies to your problem, but one of those two solutions should work.
