### ISSUE TITLE
Embeddium makes Spring Water from Spelunkery turn yellow

### ISSUE THREAD

**Issue by etherealgears** [FiniteReality/embeddium#370]
### Bug Description

The spring water fluid from the mod Spelunkery looks yellow with Embeddium installed. It should be light blue. This has been reported on the Spelunkery github, but I was told to report it here. This is the issue: https://github.com/AstralOrdana/Spelunkery/issues/243

### Reproduction Steps

Launch Minecraft with Spelunkery and Embeddium both installed. The Spring Water fluid will be yellow. Removing Embeddium makes it blue again.

### Log File

[latest.log](https://github.com/user-attachments/files/16646869/latest.log)

**Comment by embeddedt** [comment]
This is not an Embeddium bug. https://github.com/AstralOrdana/Spelunkery/issues/243#issuecomment-2295050160
