### ISSUE TITLE
Game freeze after launching 

### ISSUE THREAD

**Issue by dirolov** [FiniteReality/embeddium#372]
### Bug Description

FML doesnt respond

### Reproduction Steps

Im just launching my game from XMCL, but after some time FML early loading progress doesnt respond and stuck on same values.
![Mods](https://github.com/user-attachments/assets/d88fbf49-1ea3-4ff9-97ef-ff7bec211e29)
![Version](https://github.com/user-attachments/assets/d90701da-e437-4497-9d15-aea8b72728c6)
Java version: 8

### Log File

[latest.log](https://github.com/user-attachments/files/16691802/latest.log)

**Comment by embeddedt** [comment]
1.16.5 is not supported anymore. That said, I am pretty sure the issue here is from trying to launch Embeddium & OptiFine at the same time (which won't work, they do the same thing).

**Comment by xJon** [comment]
@embeddedt Why is OptiFine not included in the incompatibility list? https://github.com/FiniteReality/embeddium/wiki/Compatibility

**Comment by embeddedt** [comment]
I assumed it was common knowledge that Sodium-like mods don't work with OptiFine; maybe that was a bad assumption. I unfortunately can't edit the wiki to add it now as I relinquished my push permissions to the repository.

**Comment by xJon** [comment]
@embeddedt Who can I contact instead?
