### ISSUE TITLE
Support between entity texture features, Valkyrian skies and oculus

### ISSUE THREAD

**Issue by DrCub** [FiniteReality/embeddium#374]
### Request Description

Entity texture features, Valkyrian skies and oculus crash the game whit Embeddium installed. So id like support between them

**Comment by Nolij** [comment]
I literally told you on the Discord that if Embeddium reports taint support will not be provided. Report the bug to the mods that hack Embeddium instead of simply requesting an API. @embeddedt please close this issue.
