### ISSUE TITLE
incompatibility with essential

### ISSUE THREAD

**Issue by xXFoundationXx** [FiniteReality/embeddium#375]
### Bug Description

when paired with essential causes players who join a hosts world to crash, it can range from immediately after joining to a minute after joining

### Reproduction Steps

**v1.20.1 Forge - 47.3.7**

1. add essential
2. add Embeddium
3. start game
4. start a world
5. invite a friend
6. wait for crash

### Log File

xxx

**Comment by Amateur233** [comment]
what are your other mods

**Comment by xXFoundationXx** [comment]
to discover this, i played with only these 2 mods, 

but i found out it has to do with essential updating that didn't play nice with Embeddium, let alone itself,

**Comment by embeddedt** [comment]
I believe the Essential updater is known for causing issues with some mods. Does the issue occur if Essential hasn't updated itself on that launch?

**Comment by xXFoundationXx** [comment]
it took awhile, but it was the most recent update essential offered, if i downgrade it fixes the issue, so may be on them, idk
