### ISSUE TITLE
Incompatibility with Shimmer

### ISSUE THREAD

**Issue by trewqaGGG** [FiniteReality/embeddium#377]
Without Embeddium installed, Shimmer's coloured lights work (along with the Blooming Blocks resource pack) as intended in 1.20.1, which is also the case when Sodium and Indium is installed, but with Embeddium installed, coloured light becomes invisible except for around the edges (this is not the case for dynamic lights however, which seem to work fine with Embeddium)

With Embeddium:
![image](https://github.com/user-attachments/assets/f25b040f-79fb-4733-bdff-532ddeabd41f)

W/O Embeddium: 
![image](https://github.com/user-attachments/assets/a92f725a-2c31-47fe-9585-93b34a0f8c97)

**Comment by embeddedt** [comment]
The Shimmer mod applies its own patches to Sodium (and derivatives) to implement bloom; please report this to them.
