### ISSUE TITLE
Botania Mana Bursts don't translucency sort correctly

### ISSUE THREAD

**Issue by anoomolu** [FiniteReality/embeddium#378]
### Bug Description

When placing any stained/tinted glass above the path of a mana burst, it gets culled when the expectation is that they stay visible.

### Reproduction Steps

Pulse mana spreader above a Creative mana pool, with tinted glass above the path of mana bursts. I'm using a mana detector with a mana blaster to remotely activate the contraption.

![image](https://github.com/user-attachments/assets/c24760fd-c323-4996-923b-9fa660f4ccbf)

### Log File

https://mclo.gs/YcXyz6f

**Comment by embeddedt** [comment]
I suspect mana bursts are an entity, not a block, which means translucency sorting of terrain (which is what Embeddium does) is not relevant. Does Fabulous mode fix this?

**Comment by anoomolu** [comment]
Oh I see, sorry for the misunderstanding. Fabulous does seem to fix the issue.

**Comment by embeddedt** [comment]
That's what I thought would happen. I don't think it's an Embeddium issue, then; you would see the same issue in vanilla in non-Fabulous mode. It's one of the scenarios that Fabulous mode is designed to fix (if you're willing to trade a lot of performance :melting_face:).
