### ISSUE TITLE
game crash when open the shadow

### ISSUE THREAD

**Issue by blackvccat** [FiniteReality/embeddium#379]
### Reproduction Steps

when open the shadow

### Log File

[latest.log](https://github.com/user-attachments/files/16874160/latest.log)

**Comment by blackvccat** [comment]
[
[错误报告-2024-09-05_0.06.46.zip](https://github.com/user-attachments/files/16874173/-2024-09-05_0.06.46.zip)
](url)

**Comment by embeddedt** [comment]
As mentioned in the issue template, if you need help with crashes or other support, please [ask on our Discord server](https://discord.gg/rN9Y7caguP). The issue tracker should only be used for bugs that can be narrowed down to a specific mod/mod set, and have specific reproduction steps.
