### ISSUE TITLE
Class not found: ColorABGR

### ISSUE THREAD

**Issue by Merlunis** [FiniteReality/embeddium#38]
Minecraft was attempting to initialize the game.
During initialization, it encountered an issue with Mixin transformations.
The specific problem was the inability to find the class ColorABGR from the mod "Sodium." In this case only Embeddium is installed.
Exit Code: -1
[latest.log](https://github.com/embeddedt/embeddium/files/12708740/latest.log)

**Comment by embeddedt** [comment]
I don't think this is the reason for the crash - if you look further up in the log you'll see:
```
java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
```
which likely means that some of your Create addons are not compatible with the latest version of Create.
