### ISSUE TITLE
Mana and Artifice Entity Culling Issue

### ISSUE THREAD

**Issue by no-name-provided** [FiniteReality/embeddium#382]
### Bug Description

While standing on a wellspring multiblock near sea level, looking in a specific direction causes the wellspring pillars to disappear. The exact vertical angle appears to be a function of your angle with the cardinal directions (x and z axis), but there's a rough circle that's problematic. This causes an unpleasant flickering effect while walking around the wellspring. Reported to mod author here: https://github.com/Mithion/Mana-And-Artifice/issues/879. They're confident the issue is on your end. 

![image](https://github.com/user-attachments/assets/1fd8d253-a439-442f-a2bb-3eb93016b28a)

Should look like this:

![image](https://github.com/user-attachments/assets/33659258-1cd5-499b-a859-74ff732c3001)

Note that the wellspring pillars are oversized blocks (or some other trickery), rather than several blocks placed individually.

### Reproduction Steps

Install mana and artifice and embeddium. Read the codex, use the command "/mna progression tier 5" to unlock the wellspring multiblock, place a wellspring pillar on the ground, stand a few blocks away and one block above the wellspring pillar's base. Then, look diagonally up. The pillar will disappear.

Verified with embeddium version 0.3.28+mc1.20.1

### Log File

No relevant log entries.

**Comment by embeddedt** [comment]
I've written a long analysis comment on the original issue. I don't think it's an Embeddium issue.
