### ISSUE TITLE
Crash with Lodestone-1.20.1-1.6.2.3-fabric

### ISSUE THREAD

**Issue by emihead** [FiniteReality/embeddium#383]
### Bug Description

https://github.com/LodestarMC/Lodestone/issues/46#issue-2512611732

I opened an issue on Lodestone about this and they apparently removed support for versions of Sodium older than 0.5.9. This combo makes the game crash.
I haven't tested on 1.6.2.3b or c but I can only assume the issue is still there since the changelogs don't mention anything about reverting the Sodium-related changes. Even if they did, it may be worth adding in some compat so Lodestone doesn't have to hold itself back.
Since it's an old Sodium problem I figured it'd be better if I came here about it than kept bugging the Lodestone devs.

### Reproduction Steps

1. install embeddium and lodestone-1.20.1-1.6.2.3-fabric
2. launch game

### Log File

https://mclo.gs/z5ksHqe

**Comment by embeddedt** [comment]
Lodestone uses a mixin into Embeddium/Sodium internals, which is not guaranteed to work across updates. For what they are trying to do, they should be able to just inject into the vanilla `renderChunkLayer` function, and not touch Embeddium internals at all. They just need to change their mixin's priority so it doesn't conflict with Embeddium/Sodium.
