### ISSUE TITLE
Game crashes on startup with Embeddium installed.

### ISSUE THREAD

**Issue by SnowXDev** [FiniteReality/embeddium#385]
The titles says it all, my game crashes on star-tup if embeddium is installed. Unfortunately I cannot decipher the crash log(s).

**Minecraft Ver**
Minecraft 1.20.1 (Forge 47.3.0)

**Embeddium Ver**
embeddium-0.3.31+mc1.20.1.jar

**Oculus Ver (When Using)**
oculus-mc1.20.1-1.7.0.jar

Reproduction Steps:
1. Launch Game
2. Loads for a second or two.
3. Crashes to launcher.

Embeddium & Oculus:
https://mclo.gs/JoZM7Td

Embeddium Only:
https://mclo.gs/b6gQ7o9

(Game starts up fine without Embeddium)

**Comment by embeddedt** [comment]
Chunk Animator and Embeddium aren't compatible.
