### ISSUE TITLE
[1.19.2] Transparency for tools/weapons not rendered correctly over the tranclucent background

### ISSUE THREAD

**Issue by vgrynch** [FiniteReality/embeddium#386]
### Bug Description

Transparency for semi-transparent (translucent) tools/weapons not rendered correctly over the water.
I have tried various options with no help at all, in particular, the most relevant options too:
- Fabulous graphics (not supported by Alex's mobs for a pick axe, Epic Fight weapons still hide water)
- Animate only visible textures (no effect when enabling/disabling)
- Translucent face sorting (disabling it has no effect)
- Shader (ComplementaryShaders 4.7.2) - same issue when enabled.

I have tried removing EMF and JSON entity features etc. - no help. Looks like it is not related to texture packs as well because different mods weapons have the same issue for Epic Fight, including the default one.

Video toolkit mods:
Embeddium: embeddium-0.3.18.1+mc1.19.2
Embeddium++: embeddiumplus-1.19.2-v1.2.13
Oculus: oculus-mc1.19.2-1.6.9

### Reproduction Steps

See screens.
Alex mobs: obtain Ghostly pickaxe and stand like on the screen below. Behind the tool, water disappears.
Epic fight: weapon animations' semi-transparent parts also hide water - see screens (the last one with shader).

![image](https://github.com/user-attachments/assets/3a0085eb-1065-45a0-a72c-f3a37d859e5c)
![image](https://github.com/user-attachments/assets/9e8a0b71-d721-458a-aa14-f0a52eacd8ae)
![image](https://github.com/user-attachments/assets/76189958-6d51-4de2-9875-fc9e1bd797c2)
![image](https://github.com/user-attachments/assets/a0914b98-2425-4875-a6a7-fddc602c0281)

### Log File

Nothing wrong in the logs observed, just a visual issue.

**Comment by vgrynch** [comment]
More screens: It also happens with glass or any modded translucent liquids:
![image](https://github.com/user-attachments/assets/a93eecc2-3eff-44d2-9ad6-2fb9d362c70e)
![image](https://github.com/user-attachments/assets/2e82a0c8-f0bf-4d8f-af0a-c72a492cc15f)

**Comment by vgrynch** [comment]
And, on top of it: third view, spectator mode: certain things in hands hidden by transparency in spectator mode are displayed as below.
![image](https://github.com/user-attachments/assets/682be6f1-6724-4b05-9bc9-d590ee8c7004)
(not a big issue though :-) )

**Comment by embeddedt** [comment]
Are  you sure these issues can't also happen without Embeddium installed? From what I can tell, the ghostly pickaxe has similar issues in vanilla:

![image](https://github.com/user-attachments/assets/fb95e132-58fd-412b-a6c1-9cbb07d04873)

And similar issue with my own head culling water in spectator mode, with vanilla:

![image](https://github.com/user-attachments/assets/a4924c8e-ca54-4523-b4c3-455a3608b3b8)

In general, interactions between translucent entities and translucent terrain are not Embeddium's fault; terrain is rendered at roughly the same time/order it would be in vanilla.

Fabulous is supposed to solve those issues, but mods need to be coded to use it properly, and many mods in older versions just didn't support Fabulous.

**Comment by vgrynch** [comment]
Any clues if this can be improved? What needs to be changed in texture packs?

**Comment by embeddedt** [comment]
It's not something that can really be fixed with a resource pack; the mod needs to be designed to use the Fabulous mode feature set properly. And in non-Fabulous mode, some of the cases are not really possible to fix.

**Comment by vgrynch** [comment]
I don't understand why it cannot be fixed, but I assume that it's not like a simple static bitmap putting over another :-) For me, it looked like some kind of over-culling issue, especially when I saw a few semi-transparent mobs rendered correctly.
Please, close the ticket if you see it's not doable.
