### ISSUE TITLE
[1.16.5] Gui Scale issue when installed with Modern UI

### ISSUE THREAD

**Issue by Kasualix** [FiniteReality/embeddium#39]
Modern UI without Embeddium (max GUI Scale: 3):
![image](https://github.com/embeddedt/embeddium/assets/110756250/e7dd79b3-1fbd-4787-836c-bbb67a9c25ef)

Modern UI with Embeddium (max GUI Scale: 2):
![image](https://github.com/embeddedt/embeddium/assets/110756250/502e2c5e-298c-47a7-822a-ed8a93afc0c3)

Embeddium without Modern UI (max GUI Scale: 3):
![image](https://github.com/embeddedt/embeddium/assets/110756250/2c90085c-1ab8-45bc-b3c8-88a8965b3bc0)

Expected: max GUI Scle = 3 with mui and embeddium

In some computers, it may cause huge inconvenience to users who is more used to 3 under 2.

Solution is to edit the GUI Scale in options.txt manually.

Maybe related to MUI's [MixinWindow](https://github.com/BloCamLimb/ModernUI/blob/1.16.5/mod-forge/src/main/java/icyllis/modernui/mixin/MixinWindow.java)

Rubidium has this issue too

**Comment by Kasualix** [comment]
The situation remains the same, it's not fixed

**Comment by embeddedt** [comment]
Are you testing using the build from that commit? There hasn't been a release yet. On my end the maximum GUI scale is now the same for both (4), where it was previously 2.

**Comment by Kasualix** [comment]
It's reverted by Rubidium Extra lmao
https://github.com/dima-dencep/rubidium-extra/blob/1.16.x/stable/src/main/java/me/flashyreese/mods/sodiumextra/mixin/sodium/gui_scale/MixinSliderControl.java

**Comment by Kasualix** [comment]
Fixed in [my fork](https://github.com/MCTeamPotato/EmbeddiumExtension/commit/c77dc635300716ae18fee3505645971d5d190f6b)
