### ISSUE TITLE
How do I access shaders?

### ISSUE THREAD

**Issue by oohkoto** [FiniteReality/embeddium#390]
This may sound silly, but I can't find the shaders option. Could you tell me where it is?

**Comment by embeddedt** [comment]
Embeddium does not have built-in support for shaders; you need to use a third-party add-on. If you have Oculus/Iris installed, the menu item for shaders will appear in video settings.

**Comment by Morgarix** [comment]
Uh, i have it installed and it still dont show up

**Comment by Morgarix** [comment]
![Screenshot 2025-01-09 221104](https://github.com/user-attachments/assets/f31d61d5-9b74-4848-b430-666acded36c1)

**Comment by Morgarix** [comment]
nvmnd im just a dumbass who didnt reenable oculus 💀💀💀
