### ISSUE TITLE
[1.19.2][Crash]Incompatible with the latest version of Rubidium extra

### ISSUE THREAD

**Issue by ghost** [FiniteReality/embeddium#40]
Embeddium0.1.8 is incompatible with Rubidium Extra 0.4.19
[latest.log](https://github.com/embeddedt/embeddium/files/12714950/latest.log)
[crash-2023-09-25_20.26.25-fml.txt](https://github.com/embeddedt/embeddium/files/12714952/crash-2023-09-25_20.26.25-fml.txt)

**Comment by TonimatasDEV** [comment]
I don't think it will be fixed. Explication: #16

**Comment by embeddedt** [comment]
Should be fixed in 0.1.10.
