### ISSUE TITLE
1.20.1 Bug with angle rails from mod Create

### ISSUE THREAD

**Issue by Kogomre** [FiniteReality/embeddium#41]
Hi, how can i fix it? 
Use: Embeddium-0.1.10+mc1.20.1.jar
Loader: NeoForge 1.20.1-47.1.77
I have this problem with Create-1.20.1-0.5.1.d and Steam_Rails-1.5.1+forge-mc1.20.1
Command /flywheel backend off fix problem but drop fps in two times when near buildings from create mod.
Cogwheels and another items from create mod after press F3+A become transparent too
![Screenshot_1](https://github.com/embeddedt/embeddium/assets/43267690/48c33ca4-efd6-44a4-873d-78148e093705)

**Comment by embeddedt** [comment]
Update to Create 0.5.1e.
