### ISSUE TITLE
All the mods 9 modpack client CRASH

### ISSUE THREAD

**Issue by vinnyg0621** [FiniteReality/embeddium#423]
### Bug Description

when I died, the client crashed.

### Reproduction Steps

1. be dead
2. a tombstone will appear
3. the client will crash.

### Log File

https://mclo.gs/M6DaH8I
[latest.log](https://github.com/user-attachments/files/17983303/latest.log)

**Comment by FiniteReality** [comment]
I'm not sure this is the fault of Embeddium; at least looking through the log the first exception I see after you died is releated to Blood Magic failing to get your Curios inventory to render some UI elements. It's possible that this exception messes up the PoseStack Minecraft uses to know where to render UI elements, leading to all of the other UI elements throwing similar exceptions, including the death screen which leads to a game crash.

It looks like a similar report has been opened on the Blood Magic repo about this, including players being kicked from servers: https://github.com/WayofTime/BloodMagic/issues/2063

In light of this, I'm going to close this as a "not our problem" issue, but if it persists please let me know and I can look into it again :smile:
