### ISSUE TITLE
Potential rendering issues with mods using Fabric rendering APIs

### ISSUE THREAD

**Issue by Syclusion** [FiniteReality/embeddium#43]
Using sinytra and newest embeddium, game and world will load. But all blocks fail to render, works on rubidium.

**Comment by embeddedt** [comment]
At the moment mods utilizing advanced Fabric rendering will generally have bad results with Embeddium - I am working with the Connector dev to find a proper solution to this. The solution Rubidium uses has the potential to cause compatibility issues with Forge mods if you use Fabric mods at the same time.

**Comment by Syclusion** [comment]
Oh i see! Thanks for such a detailed response, and actually explaining the problem lol. Most developers just say to bad so sad.

Hopefully you can work it out!

**Comment by n0proxy** [comment]
Are there other known Forge mods that run into this problem?

**Comment by embeddedt** [comment]
This issue is specifically referring to using Fabric mods/Sinytra Connector with Embeddium. Regular Forge mods that use Forge rendering APIs should not suffer from this.

**Comment by Gronglegrowth** [comment]
I have noticed this issue with running Modern Industrialization via sinytra connector; none of its tileentities will render. Hopefully something happens in regard to fixing this.

**Comment by Su5eD** [comment]
Hi, just wanted to let you know I'm working on resolving this issue

**Comment by embeddedt** [comment]
Installing [Lazurite](https://modrinth.com/mod/lazurite) will resolve most issues with blocks not rendering. However, invasive mods like Replay Mod/Immersive Portals will likely still not work.

For future readers: please refer to the [Connector](https://github.com/embeddedt/embeddium/wiki/Compatibility#fabric-mods-sinytra-connector) section on the compatibility wiki page for up-to-date information.
