### ISSUE TITLE
Can someone please tell me where this problem is coming from?

### ISSUE THREAD

**Issue by SirTwsted** [FiniteReality/embeddium#44]
I have tried Emeddium and I tried Rubidium.
Installed with Oculus, Iris

The problem only happens when I use any shader no matter which shader I use.

At it also ONLY happens at specific in-game time (NOT real time, but in game time).
from 00:00 to 01:00  
then 
from 11:00 to 12:00

Here is what happens.  And I can't get to the bottom of this issue.
except with turning off shaders completely.
I have even tried 5 different shaders, including.
BSL Shaders
Complementary Unbound Shaders
Sildur's Shaders.

And I still get this problems.
Pictures below.

![2023-09-29_08 54 14](https://github.com/embeddedt/embeddium/assets/15247713/54af15e2-cddd-4bb0-b307-73620db7e80a)

![2023-09-29_08 54 55](https://github.com/embeddedt/embeddium/assets/15247713/2d46ed98-456f-426b-97b2-6b1862887116)

![2023-09-29_08 55 23](https://github.com/embeddedt/embeddium/assets/15247713/7ec75826-9116-4c3d-8098-816157faca9d)

![2023-09-29_08 56 15](https://github.com/embeddedt/embeddium/assets/15247713/bbc76642-9f06-4658-8915-810cd31f623a)

Its frustrating as I don't know what mod is actually doing this.

If anyone knows please help.
Thank you.

**Comment by embeddedt** [comment]
If this issue only occurs with shaders, it should be reported to Oculus. I apologize, as many issues there have historically gone unanswered, but there is likely nothing I can do about it from Embeddium's end, as all of the shader handling is added by Oculus.

**Comment by SirTwsted** [comment]
Ok, Thank you very much.  And sorry for the bother.  😋
