### ISSUE TITLE
Incompatible with Chunk Animator (1.18.2)

### ISSUE THREAD

**Issue by Mqony** [FiniteReality/embeddium#47]
[crash-2023-09-30_22.11.27-client.txt](https://github.com/embeddedt/embeddium/files/12776467/crash-2023-09-30_22.11.27-client.txt)
This is the main incompatibility that I hoped Embeddium would fix, since the Chunk Animator devs have gone MIA. Is it possible to do on your end, or does it have to be done by the Chunk Animator team?

**Comment by embeddedt** [comment]
Unfortunately, I think it has to be fixed on Chunk Animator's end, so someone will have to fork it.
