### ISSUE TITLE
Crashes at plasmo voice GUI

### ISSUE THREAD

**Issue by kakashi1464** [FiniteReality/embeddium#48]
When open plasmo voice gui game crashes
 crash report - https://mclo.gs/39WdKKT
 latest log - https://mclo.gs/W3SiR9n
 debug log - https://mclo.gs/HBjIwyD

**Comment by embeddedt** [comment]
Great catch! Fixed in 0.1.14.

**Comment by kakashi1464** [comment]
Tysm!
