### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Catomax262** [FiniteReality/embeddium#49]
log 1: https://mclo.gs/Dgfu5sK
log 2: https://mclo.gs/DbiUT7T

**Comment by embeddedt** [comment]
These crashes are usually caused by your computer running low on memory or a bug in the NVIDIA drivers - in the future I plan to backport some related fixes from newer Sodium versions to older MC versions, but that might not fix the issue, as NVIDIA drivers are very temperamental especially on Windows. These issues are usually very difficult to pinpoint to a single source.

**Comment by embeddedt** [comment]
One workaround you can try is reducing render distance.

**Comment by Catomax262** [comment]
> These crashes are usually caused by your computer running low on memory or a bug in the NVIDIA drivers - in the future I plan to backport some related fixes from newer Sodium versions to older MC versions, but that might not fix the issue, as NVIDIA drivers are very temperamental especially on Windows. These issues are usually very difficult to pinpoint to a single source.

It's more of a memory leak. One of my mods was acting up because it got updated. I can not tell you which is it, because i have over 490 mods. Tried downloading 3 memory fix and optimization mods, yet it runs like crap even with 13 GB allocated.

I'm contacting you because one of the logs mentions sodium-related stuff.

**Comment by Catomax262** [comment]
> One workaround you can try is reducing render distance.

An error i had more specifically is that blocks when broken didn't render, and they left a ghost block of sorts. However, when i used F3 + A it did update them, but then dropped a massive memory leak.

**Comment by embeddedt** [comment]
It's very likely that one of your mods is causing the memory leak, and Embeddium got caught in the crossfire. I would love to be more helpful, but I am not aware of what tools can be used to find this type of memory leak at the moment - it's different from regular Java memory leaks which are fairly easy to track down with enough time.
