### ISSUE TITLE
1.20.1 Vsync does not work properly

### ISSUE THREAD

**Issue by Lukasviedenz** [FiniteReality/embeddium#50]
every time I restart the game and join a world vsync is still enabled according to the setting but the fps goes way above the vsync value so as if it was off. this can only be fixed by turning off the option then pressing done and then turning vsync on again. but then you have to repeat this every game restart when you have joined a world. I have the some Issue with Rubidium.

Mc Version: 1.20.1
Embedium version: 0.1.14
PC specs: I7 and a rtx 2070

**Comment by embeddedt** [comment]
I am pretty sure this is caused by a Forge bug - the fancy loading screen currently disables VSync during startup. I'll investigate a workaround.

**Comment by Lukasviedenz** [comment]
thanks for the quick reply. i also noticed it earlier when i disabled all mods and it was still like that.

**Comment by embeddedt** [comment]
I've added a workaround for the next Embeddium release; for now you can use the beta linked here:

https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip

**Comment by Lukasviedenz** [comment]
thank you very much ! :)

**Comment by embeddedt** [comment]
I've released the fix in 0.1.16.
