### ISSUE TITLE
Transparency issues emissive plugin

### ISSUE THREAD

**Issue by Aer-ink** [FiniteReality/embeddium#51]
**Describe the bug**
Transparency issues with "plant" blocks near or in water when the emissive plugin from moremcmeta is in the same instance.

**To reproduce**
just get near kelp or any plant near water.

**Screenshots or videos**
![2023-10-02_12 17 48](https://github.com/MoreMcmeta/emissive-plugin/assets/19780430/acd30222-21c0-45e8-a51f-93dad98b7e7f)
![2023-10-02_12 18 11](https://github.com/MoreMcmeta/emissive-plugin/assets/19780430/73a575b5-054f-420a-9b71-0bbc2f7611b7)
![2023-10-02_12 18 51](https://github.com/MoreMcmeta/emissive-plugin/assets/19780430/99253dc6-0e62-401e-9b96-a27bf6b1750b)

**Which Minecraft versions does this bug affect?**
Tested in 1.18.2 and Forge v 40.2.5

**Mods list**
moremcmeta-1.18.2-4.2.4-forge
emissive-plugin-1.18.2-1.1.1-forge
textrues_embeddium_options-0.1.1+mc1.18.2
embeddium-0.1.14+mc1.18.2

**Comment by embeddedt** [comment]
I looked at the code for this mod - it appears to modify parts of how vanilla's renderer handles transparent blocks (like plants), and these modifications will not work with mods like Embeddium that replace the vanilla renderer. Support would need to be added on their end, or with us working together.
