### ISSUE TITLE
Incompatible mod add to wiki

### ISSUE THREAD

**Issue by Ki-Tan2934** [FiniteReality/embeddium#53]
The mod [Chunk Animator](https://www.curseforge.com/minecraft/mc-mods/chunk-animator) is incompatible.

I know this is not a place to ask and is a bit cheeky, but a working version of that mod would be swell maybe that's integrated ;)

**Comment by embeddedt** [comment]
Thanks, I've added it to the wiki. Implementing this feature in Embeddium directly is out-of-scope, but I'm happy to work with someone who wants to implement it if API hooks are needed.
