### ISSUE TITLE
MC.1.20 Incompatible with Connected Glass [Crash]

### ISSUE THREAD

**Issue by litjohn50** [FiniteReality/embeddium#55]
Forge 47-1.3
connectedglass-1.1.8-forge-mc1.20.1
embeddium-0.1.15+mc1.20.1
oculus-mc1.20.1-1.6.9

Randomly as I am walking around the world with shaders or without shaders my game crashes and throws this report.

I am walking around my building that has it connected glass.

[crash-2023-10-05_23.45.59-client.txt](https://github.com/embeddedt/embeddium/files/12827003/crash-2023-10-05_23.45.59-client.txt)

**Comment by embeddedt** [comment]
Someone else had a similar issue on Discord and they found a similar crash occurs even without Embeddium; does the same occur for you?

**Comment by embeddedt** [comment]
Please also try updating to 0.1.16; I found an issue in the code that might be related.

**Comment by litjohn50** [comment]
I'll try it out and let you know.

**Comment by litjohn50** [comment]
It seems to have fixed the issues. I played for a couple of days and haven't had a crash since I updated.
