### ISSUE TITLE
[MC 1.20.1][Forge 47.2.1] Game crash with Supplementaries when placing book in world

### ISSUE THREAD

**Issue by ElasticKnife** [FiniteReality/embeddium#57]
Issue with model rendering
[crash-2023-10-06_22.32.20-client.txt](https://github.com/embeddedt/embeddium/files/12836709/crash-2023-10-06_22.32.20-client.txt)

**Comment by embeddedt** [comment]
Please send the full `latest.log` file.

**Comment by embeddedt** [comment]
Update: someone mentioned a similar crash in another community and apparently this is https://github.com/Layers-of-Railways/Railway/issues/290, which is a conflict between Supplementaries and Create: Steam 'n Rails. I don't think it can be fixed on my end.
