### ISSUE TITLE
Texture randomization is different from Minecraft Vanilla

### ISSUE THREAD

**Issue by Lolothepro** [FiniteReality/embeddium#6]
[Embeddium](https://github.com/embeddedt/embeddium):

![2023-09-02_15 07 48](https://github.com/embeddedt/embeddium/assets/68275908/2e47aa02-67a9-4f6c-94b3-63a0e230e22b)

Forge:

![2023-09-02_15 08 38](https://github.com/embeddedt/embeddium/assets/68275908/a0a5ef38-f469-4e4b-b62b-c11bdab302af)

Sodium:

![2023-09-02_15 10 03](https://github.com/embeddedt/embeddium/assets/68275908/7d3fe823-6985-4831-abd9-46b1c6ecd3c0)

**Comment by Lolothepro** [comment]
RP: https://www.planetminecraft.com/texture-pack/optimi-disable-vanilla-minecraft-animations/

**Comment by embeddedt** [comment]
Does this still happen with 0.1.4? I had to place the blocks in the same positions manually, but it seems to look the same as your Forge & Sodium screenshots now.

![2023-09-09_13 07 36](https://github.com/embeddedt/embeddium/assets/42941056/3c3c8e46-b86d-44a2-b84f-2ba4749caf03)

**Comment by Lolothepro** [comment]
> Does this still happen with 0.1.4? I had to place the blocks in the same positions manually, but it seems to look the same as your Forge & Sodium screenshots now.
> 
> ![2023-09-09_13 07 36](https://user-images.githubusercontent.com/42941056/266793912-3c3c8e46-b86d-44a2-b84f-2ba4749caf03.png)

nope
