### ISSUE TITLE
[1.20.1] Immersive Engineering render issues

### ISSUE THREAD

**Issue by Luviam** [FiniteReality/embeddium#64]
Wires and Windmills from Immersive Engineering don't render while using Embeddium and or Rubidium. (Could be caused by using a NeoForge mod in a regular Forge environment although I doubt it as they haven't really separated yet)

MC Version 1.20.1
Forge Version 47.2.0
Immersive Engineering Version 1.20.1-10.0.0-169
Embeddium Version 0.2.1+mc.1.20.1

Tested it with Rubidium just in case and same thing, the wires don't render
Rubidium Version 1.20.1-0.7.1

And yes the wires render fine without Embeddium and or Rubidium (Although my FPS goes away because I don't have the lovely optimizations)

**Comment by embeddedt** [comment]
IE uses a vanilla renderer mixin to make its wires render so compatibility has to be added on our end each time it ports to a new Minecraft version. Ideally it would use a proper Forge event for this instead so that explicit compatibility isn't needed. I'll try to fix this soon.

**Comment by Luviam** [comment]
Jesus Christ you responded quick. But good to know you're looking into it, cheers.

**Comment by Luviam** [comment]
My windmill from IE appears to also not render.

**Comment by embeddedt** [comment]
I placed a windmill in a test world (obtained by choosing the "Windmill" item in creative) and it seems to render without issues for me.

**Comment by Luviam** [comment]
I Just now realized my windmill is rendering but is offset by quite a few blocks and not animated, might be another mod. I'll check and see.

**Comment by Luviam** [comment]
Disabled Embeddium and it fixed the windmill issue for me, could be an incompatibility with another mod or maybe hardware/driver related? I'll re-enable and it try and see if ModernFix or Create's built-in Flywheel is messing with Embeddium.

**Comment by embeddedt** [comment]
How do I make the windmill spin? I just tested with a static one.

**Comment by Luviam** [comment]
Place it on a kinetic dynamo, on the side with the hole, also it needs a fair amount of free space. Place it up like 4-5 blocks above ground without any blocks next to it or in front of it preferably. (Update, Modernfix and Create's built-in flywheel are not the issue... Although my Windmill is acting funny now without Create's flywheel. It renders if I'm super close but then de-renders when I get about 5 blocks away, tf)

**Comment by embeddedt** [comment]
It spins properly and is not offset in a standalone instance with IE & Embeddium so there must be another mod causing issues.

In other news, I have just pushed a beta which adds the necessary integration for wire rendering.

https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip

**Comment by Luviam** [comment]
Alright cool, I'm gonna keep messing with the windmill, also what version of forge were you using to get the windmill to work properly?

**Comment by embeddedt** [comment]
NeoForge 47.1.79. I don't think IE officially supports Forge anymore.

**Comment by Luviam** [comment]
IE Doesn't officially support forge anymore but 1.20.1 Neoforge and 1.20.1 Forge are backwards compatible. Albeit there could be issues and the windmill rendering could be because of that. I'm gonna mess around with Forge, Neoforge versions and other performance mods to see if I can't find anything, wish me luck.

**Comment by embeddedt** [comment]
If you have Oculus installed try without it first, it can break random things.

**Comment by Luviam** [comment]
I Don't have Oculus installed because of that reason lmao.

**Comment by Luviam** [comment]
Yeah no its another mod causing it, with Just IE and Embeddium on regular Forge the windmill renders perfectly fine.
God the problem mod will not be fun to look for.

**Comment by Luviam** [comment]
I've concluded its not an IE issue, but the issues I ran into... I'll let my short video do the talking.
https://youtu.be/ztxgwUI74CI

**Comment by embeddedt** [comment]
Ah I see. It has issues with multiple windmills at once. I'll look into that.

**Comment by Luviam** [comment]
Alright, I'm a bit flabbergasted at these issues because they're so weird lmao. Good luck trying to figure it out, cheers.

**Comment by embeddedt** [comment]
That took way too much debugging effort LOL. But I tracked it down to a Sodium optimization which tries to reuse position matrix objects; that optimization is incompatible with IE as then all the windmills end up rendering at the same position. Should be fixed with the new beta.

https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip

**Comment by Luviam** [comment]
Alrighty I'll try it out.

**Comment by Luviam** [comment]
![image](https://github.com/embeddedt/embeddium/assets/56097409/0ef4ae00-9162-4057-9b57-35c656da9e91)
Works, even in my modpack with all the extra shit that's not in NeoForge. Guess this debug crusade is over lmao.

**Comment by embeddedt** [comment]
The fix has been released as part of Embeddium 0.2.2, and I also submitted a change to Immersive Engineering that will fix it from their end.
