### ISSUE TITLE
"Performance Impact" localization is invalid

### ISSUE THREAD

**Issue by Kasualix** [FiniteReality/embeddium#66]
https://github.com/embeddedt/embeddium/blob/dd4a93ff4337fcc748758500f7c920846258285e/src/main/java/me/jellysquid/mods/sodium/client/gui/SodiumOptionsGUI.java#L235
![image](https://github.com/embeddedt/embeddium/assets/110756250/7b43bc3c-2f2d-49aa-ad60-1a1cfa99d5d5)

**Comment by embeddedt** [comment]
This doesn't seem to happen for me. :thinking: Could it be an addon interfering again?

Language:

![image](https://github.com/embeddedt/embeddium/assets/42941056/253d687d-9154-4a4d-9044-b48f15d2bcd5)

Result:

![image](https://github.com/embeddedt/embeddium/assets/42941056/540377b0-b67b-4c1f-a0b0-05405000d032)

**Comment by Kasualix** [comment]
https://github.com/dima-dencep/rubidium-extra/blob/ba091f6c3356794a7c5825b1b4a47275faa56b69/src/main/java/me/flashyreese/mods/sodiumextra/client/gui/scrollable_page/OptionPageScrollFrame.java#L118
LMAO, I'll fix it
