### ISSUE TITLE
[1.19.2] Minecolonies structure preview rendering issue

### ISSUE THREAD

**Issue by vgrynch** [FiniteReality/embeddium#68]
(I am sending it here in the hope you find a fix for a long-lasting issue https://github.com/Asek3/Rubidium/issues/371. Minecolonies devs say it's a rubidium issue, and rubidium did not fix it for a long time.)

Please, see the picture below. Steps:
1. Create a new Forge profile with these mods:
rubidium-mc1.19.2-0.6.2c
blockui-1.19-0.0.69-ALPHA
domum_ornamentum-1.19-1.0.135-BETA-universal
minecolonies-1.19.2-1.1.197-BETA
structurize-1.19.2-1.0.652-BETA
2. Create a new world and try to place some structure in Minecolonies using the build tool.
3. During the preview of the structure placing, observe rendering issues as on the screenshot during the structure placement preview.

After the removing rubidium/embeddium, all renders correctly.

This is reproduced also with a few other versions of mods.

![image](https://github.com/embeddedt/embeddium/assets/46818018/7991473a-ba07-42cd-bfe3-bb65c87a5938)

**Comment by embeddedt** [comment]
I am able to reproduce this with Rubidium 0.6.2c, but not the latest beta of Embeddium (https://nightly.link/embeddedt/embeddium/workflows/gradle/19.2%2Fforge/Embeddium.zip), which I also just released minutes ago as 0.2.2. Can you confirm the same on your end?

**Comment by embeddedt** [comment]
Just wanted to make sure the above message wasn't missed.

**Comment by vgrynch** [comment]
Confirmed the issue vanished in later versions.
