### ISSUE TITLE
Occlusion culling is too aggressive

### ISSUE THREAD

**Issue by 323237216** [FiniteReality/embeddium#69]
钠让我的世界1.18以上版本出现MC-70850的bug，而你的模组用了更高版本钠的移植，导致区块无法渲染的这个bug再次出现

**Comment by 323237216** [comment]
Sodium caused the bug of MC-70850 in minecraft version 1.18 and above, and your mod uses a higher version of sodium porting, which caused the bug of block rendering to reappear.

**Comment by embeddedt** [comment]
This should be fixed as of Embeddium 0.2.2.

**Comment by 323237216** [comment]
Sorry, I thought Edge would automatically translate what I wrote, so I wrote it in Chinese. Later, I realized that it wasn't like that. I already posted the translated version in the comments section

**Comment by qznfbnj** [comment]
> Sorry, I thought Edge would automatically translate what I wrote, so I wrote it in Chinese. Later, I realized that it wasn't like that. I already posted the translated version in the comments section抱歉，我以为Edge会自动翻译我写的内容，所以我用中文写的。后来我发现事情并不是这样的。我已经把翻译版发在评论区了
> 
> 抱歉，我以为Edge会自动翻译我写的内容，所以我用中文写的。后来我发现事情并不是这样的。我已经把翻译版发在评论区了

Bro, you can edit the original text directly.
