### ISSUE TITLE
[1.16.5] More Red rendering issues

### ISSUE THREAD

**Issue by DarkKostas** [FiniteReality/embeddium#72]
![Χωρίς τίτλο](https://github.com/embeddedt/embeddium/assets/1405072/662bbe3f-f746-4fad-a480-eb16a10586ff)

Using either latest Embeddium 0.2.2 for 1.16.5 or Rubidium 0.2.13, cables don't render connected between blocks.
But if you hover the cursor on it, it will show the outline properly going from one side of the block to the other.

**Comment by embeddedt** [comment]
This will be fixed in a release shortly; in a couple minutes when the beta is finished compiling you can download it [here](https://nightly.link/embeddedt/embeddium/workflows/gradle/16.x%2Fforge/Embeddium.zip) as an interim fix.

**Comment by embeddedt** [comment]
I've pushed 0.2.4 with the fix.

**Comment by DarkKostas** [comment]
Thanks for the quick response and fix. Tried both and works as expected now!
