### ISSUE TITLE
Render distance > 64 chunks render ownly 32 chunks

### ISSUE THREAD

**Issue by Quantum-mutnauQ** [FiniteReality/embeddium#74]
I'm setting the render distance to 64 via the options.txt. Than I and start Minecraft and check the Render distance option, the display shows 64. Than I load a world and would see the nice view. After all chunks are loaded, I realized that Minecraft only rendering 32 chunks. 

**Forge version:** 1.20.1 - 47.2.1
**Embeddium version:** 0.2.2+mc1.20.1

**Comment by embeddedt** [comment]
Sodium & Embeddium are only designed to support render distances that vanilla allows in the GUI (i.e. up to 32), so this is working as intended. At this time I do not plan to support larger render distances within Embeddium.

**Comment by Quantum-mutnauQ** [comment]
Hello,
Do you know if there exist an mod that fix the poblem?

**Comment by embeddedt** [comment]
A Forge port of Bobby might; that is the only mod I can think of.

**Comment by Quantum-mutnauQ** [comment]
Thaks you,
That helped me a lot.
