### ISSUE TITLE
Some Items Rendering Incorrectly In Hotbar

### ISSUE THREAD

**Issue by Eletoast** [FiniteReality/embeddium#75]
The item "lighting" is usually fine, but whenever I pull out an item with a 3d model (in this case, from Ars Nouveau), it screws up the lighting. The item causing this is the spell book, however some other items also cause this same effect. Image 1 is with the spell book in hotbar. Image 2 is spell book not in hotbar. Image 3 is spell book in inventory.
![image](https://github.com/embeddedt/embeddium/assets/143987495/6bf04ba8-8903-432e-8aa4-18c28e21c249)
![image](https://github.com/embeddedt/embeddium/assets/143987495/7b9e8fa9-014e-4f39-aea2-2da5df708b95)
![image](https://github.com/embeddedt/embeddium/assets/143987495/7ce2a355-f716-4e00-b75d-b0cb61533047)

**Comment by embeddedt** [comment]
Hmm, I'm not seeing this occur in a standalone instance with Ars Nouveau 4.7.4 and Embeddium 0.2.2.

![image](https://github.com/embeddedt/embeddium/assets/42941056/32ceb9cf-596f-40d9-a3f4-b2921000fb6c)

**Comment by Eletoast** [comment]
I'll look more into it to see what may be the compatibility issue. It started happening after the 0.2.0 update to Embeddium though.

**Comment by embeddedt** [comment]
Hmm, as far as I know there were not any changes in 0.2.0 that would affect item rendering.

**Comment by wsxiya** [comment]
> “照明”项目通常很好，但是每当我拿出带有3D模型的项目（在这种情况下，来自Ars Nouveau）时，它都会搞砸照明。造成这种情况的物品是法术书，但其他一些物品也会产生同样的效果。图 1 是热栏中的法术书。图像 2 是不在热栏中的咒语书。图3是库存中的法术书。 ![image](https://user-images.githubusercontent.com/143987495/277135652-6bf04ba8-8903-432e-8aa4-18c28e21c249.png) ![image](https://user-images.githubusercontent.com/143987495/277135656-7b9e8fa9-014e-4f39-aea2-2da5df708b95.png) ![image](https://user-images.githubusercontent.com/143987495/277135721-7ce2a355-f716-4e00-b75d-b0cb61533047.png)

Whether to install the "ImmediatelyFast" mod

**Comment by Eletoast** [comment]
Thanks for the heads up. Checked to see and it seems like it's just a minor incompat with ImmediatelyFast. Sorry for the false report.
