### ISSUE TITLE
Rendering issues with Fog Looks Good Now / Fog Looks Modern Now

### ISSUE THREAD

**Issue by HollyBlocky** [FiniteReality/embeddium#77]
Using Embeddium with Fog Looks Modern Now (or Fog Looks Good Now on older versions) will cause fog to flicker while moving, as if the settings of the fog are trying to override each other.

**Comment by embeddedt** [comment]
I looked at the code for this mod and it appears to use mixins to modify the vanilla renderer, which means it may have compatibility issues with Embeddium. I would suggest asking them to investigate this incompatibility on their end first.
