### ISSUE TITLE
Render Problem **Nyctophobia Mod**

### ISSUE THREAD

**Issue by DonorKrovi** [FiniteReality/embeddium#78]
https://youtu.be/hniGSNqvzR0
Embeddium version in video

**Comment by embeddedt** [comment]
In a standalone instance with this mod and Embeddium 0.2.2, I don't see the flickering - the fog remains dense permanently while I'm in the haunted lakes biome.

**Comment by DonorKrovi** [comment]
Hmm, ok, thanks

**Comment by DonorKrovi** [comment]
Can you provide me with your graphics settings?

**Comment by embeddedt** [comment]
I don't think much has been changed from the default, but here.

[embeddium-options.json](https://github.com/embeddedt/embeddium/files/13063929/embeddium-options.json)

**Comment by DonorKrovi** [comment]
yeah, this is alex caves issue

**Comment by embeddedt** [comment]
Maybe try https://github.com/AlexModGuy/AlexsCaves/issues/109#issuecomment-1772949387?

**Comment by DonorKrovi** [comment]
> Maybe try [AlexModGuy/AlexsCaves#109 (comment)](https://github.com/AlexModGuy/AlexsCaves/issues/109#issuecomment-1772949387)?

Thank you, I'll try it now

**Comment by DonorKrovi** [comment]
Yes, fixed :)
