### ISSUE TITLE
Rendering issue on twilight forest block

### ISSUE THREAD

**Issue by ghost** [FiniteReality/embeddium#8]
The block of iron wood has a rendering issue when working with CTM and embeddium
working with rubidium:
![2023-09-03_22 13 13](https://github.com/embeddedt/embeddium/assets/129179911/e116565a-291a-4a21-95d6-96aff7848a61)
working with embeddium and CTM:
![2023-09-03_22 16 11](https://github.com/embeddedt/embeddium/assets/129179911/dc299f0f-eeb9-494e-9771-8176ac44d169)

**Comment by embeddedt** [comment]
I'm not able to reproduce this on 1.16. Are you using any other mods, or resource packs?

**Comment by ghost** [comment]
> I'm not able to reproduce this on 1.16. Are you using any other mods, or resource packs?

No.Have u tried to reproduce it on 1.19?The texture of ironwood returns to normal if I switch to Rubidium

**Comment by embeddedt** [comment]
Hmm, the texture seems broken with just Twilight Forest & CTM, with Embeddium removed. Rubidium essentially causes CTM to not function for the most part which is probably why it works correctly there.

![2023-09-03_15 11 24](https://github.com/embeddedt/embeddium/assets/42941056/5965b80a-4b41-43da-b047-79e7b5ffbc88)

**Comment by ghost** [comment]
> Hmm, the texture seems broken with just Twilight Forest & CTM, with Embeddium removed. Rubidium essentially causes CTM to not function for the most part which is probably why it works correctly there.
> 
> ![2023-09-03_15 11 24](https://user-images.githubusercontent.com/42941056/265284369-5965b80a-4b41-43da-b047-79e7b5ffbc88.png)

So rubidium just masks the issue,right?I will report this to Twilight Forest team.

**Comment by embeddedt** [comment]
Yes.
