### ISSUE TITLE
things ive noticed with the 1.20.1 version

### ISSUE THREAD

**Issue by SDUBZ** [FiniteReality/embeddium#81]
1. in the console it mentions alot of unsafe parking involving embeddium
2.rendering terrain bugs chunks stay parked and take awhile to load like they would back in 1.7.10 [confirmed i tested with vanilla rendering and works normally]
3.stuttering as you explore sometimes locks up for a sec 

post logs below:
[debug.log](https://github.com/embeddedt/embeddium/files/13164755/debug.log)
[latest.log](https://github.com/embeddedt/embeddium/files/13164758/latest.log)

**Comment by embeddedt** [comment]
Based on the log, it appears chunks not loading quickly is caused by server-side lag from worldgen being slow in your singleplayer world (the game still runs a server in singleplayer). This is not an issue with Embeddium, as it does not make any changes to server-side functionality.
