### ISSUE TITLE
[1.18.2-1.20.1] Quads rendered in Pokecube AIO's models disappear when looking in certain directions.

### ISSUE THREAD

**Issue by DeliWtz** [FiniteReality/embeddium#83]
I also submitted an issue to the Pokecube Dev. I'm noticing an issue that specifically only occurs with shaders enabled, so I'm unsure if I should report this to the Oculus team or not. Pokemobs that have tris in their geometry load just fine. Quads however seem to completely disappear when looking in certain directions in-world. The issue does not appear if no shaderpacks are loaded. Apologies if this is the wrong place for this, it may be worth noting that Pokecube does utilize a proprietary renderer for their mobs.

https://github.com/embeddedt/embeddium/assets/44705710/e4c5dc72-f02e-4e9d-9a60-7c8a1911bb3f

**Comment by DeliWtz** [comment]
ignore the video title, the recording is from 1.20.1 with embeddium 0.2.2

**Comment by DeliWtz** [comment]
Updated info: seems like it is an embeddium incompatibly or something of the sort. While the models only become invisible when shaders are enabled, when shaders aren't enabled, the models render over the environment. This occurs the same way, by looking a certain direction in the world.
![image](https://github.com/embeddedt/embeddium/assets/44705710/cdfa1876-22e0-4397-bf17-63e29100a375)

**Comment by embeddedt** [comment]
The issue that occurs only with shaders is out of scope for Embeddium to fix and should be reported to Oculus.

The other issue is strange, but will be annoying to track down if the renderer is proprietary/closed-source. Input from the Pokecube dev would be welcome.

**Comment by DeliWtz** [comment]
Sorry for not clarifying - the mod is open source. 

[https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.18.2/src/thutcore/java/thut/core/client/render/model/parts/RenderTypeProvider.java#L45-L92](url)

Thutmose, the creator, stated:

"Might be able to follow it back to where things are going wrong from here. Any input on more proper ways/places to setup the render types, or to change to the VertexConsumer would be useful, as the present system is whatever was reverse engineered together in MC 1.15. As such, it is possibly the wrong way to go about the whole thing now. We would appreciate any feedback at all for how to do it more properly"

**Comment by Thutmose** [comment]
I think I found the problem, earlier on in the update I had been using something related to one of the vanilla implementations of a  buffer source, seems that section of code is not needed anymore, but may be responsible for this issue. I will address that, then it can be re-tested to see if this still occurs.

**Comment by embeddedt** [comment]
Sounds good!
