### ISSUE TITLE
IE wires not visible from all angles

### ISSUE THREAD

**Issue by zakcodez** [FiniteReality/embeddium#89]
The wires are paper thin from some angles but perfectly fine from others.
MC 1.20.1, Forge 47.2.1, Immersive Engineering 1.20.1-10.0.0-169 and Embeddium 0.2.5

![2023-11-05_08 27 22](https://github.com/embeddedt/embeddium/assets/88604164/091cd47f-7fbc-40f9-a362-e12173640f2c)
![2023-11-05_08 27 30](https://github.com/embeddedt/embeddium/assets/88604164/ec5804c8-498a-4bbf-b90a-ab82366eaaf5)
![2023-11-05_08 27 11](https://github.com/embeddedt/embeddium/assets/88604164/cf7b659a-245c-4751-807a-6c20f51b9a58)
![2023-11-05_08 27 18](https://github.com/embeddedt/embeddium/assets/88604164/0e643721-e33a-4932-a2a0-8bd3f9026e27)

**Comment by embeddedt** [comment]
Fixed, you can use the [beta](https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip) for now until I make a new release.
