### ISSUE TITLE
[1.20.1] - Crash with Pixelmon searching for items via JEI

### ISSUE THREAD

**Issue by aking4125** [FiniteReality/embeddium#9]
Hello,

Upon searching the JEI page for Pixelmon stuff, the game crashes upon viewing one of the pages: https://crashy.net/fcb1a76b-cfe6-463c-9871-ddc3c577bc44

This same issue occurs with Rubidium as well.

Any ideas?

**Comment by embeddedt** [comment]
This issue occurs because Pixelmon submits baked quads with 28 byte vertex data arrays instead of the proper 32 bytes. The vanilla renderer silently ignores this for some reason, but Sodium (and by extension, all forks) crash.

It's highly nonstandard and weird for Pixelmon to do this, so it'd be ideal for them to fix it, or at least someone there to explain why this behavior is needed.

**Comment by aking4125** [comment]
Understood. I'll submit a ticket to Pixelmon and report the information here.

EDIT: A ticket was already submitted: https://pixelmonmod.com/tracker.php?p=2&t=20914

**Comment by aking4125** [comment]
Update 2: A similar ticket was reported here and the Pixelmon team refuses to fix it: https://pixelmonmod.com/tracker.php?p=2&t=20867

It seems to be a similar issue here reported to Rubidium: https://github.com/Asek3/Rubidium/issues/584

Since this is a fork of Rubidium 0.7, the issue occurs with embeddium.

**Comment by embeddedt** [comment]
*sigh* I'll just emulate the vanilla quirk then.

**Comment by embeddedt** [comment]
I've finally managed to get Pixelmon loaded on my machine and I will not be fixing this. They need to correct their baked quad implementation. The model does not even seem to render properly in vanilla (it disappears in third person, and renders with corruption if you throw the item out of your inventory, see below). This issue can very easily be fixed on their end by correcting the quad to use a proper vertex length. The Pixelmon team is welcome to get in touch with me for more information; feel free to pass this on to them.

![2023-09-03_16 50 22](https://github.com/embeddedt/embeddium/assets/42941056/92637539-056e-4bc6-b318-aea174d78078)

**Comment by embeddedt** [comment]
Added a workaround to prevent crashing, but items with invalid quads may still render somewhat incorrectly.

**Comment by embeddedt** [comment]
Workaround released in 0.1.2.
