### ISSUE TITLE
[1.16.5] Stuttering after prolonged gameplay

### ISSUE THREAD

**Issue by A0000Xz** [FiniteReality/embeddium#91]
Version: embeddium-0.2.6+mc1.16.5
In the course of recent playthrough, I noticed that Embeddium still has an same issue with the 1.16.5 Rubidium
“The game will drop frames after a long time of opening”
When frame drops, the longest time the game takes to open is 6 hours, and the shortest time is close to 4 hours.
We may have speculated that it was caused by a memory leak, but now there is basically no memory leak，But I finally found the truth
I opened the Task Manager when the game was dropping frames and found that my video memory was full.
And when I first started the game, the video memory usage didn't even reach 10%
I don't know if there is such a thing as "video memory leak"，But at the moment, it seems that the video memory usage is getting higher and higher as the game is being turned on longer and longer.
But the strange thing is that this problem has never appeared in the vanilla or Fabric's sodium
And since this issue is more difficult to reproduce, I don't have much time, so I can only ask first.

**Comment by A0000Xz** [comment]
Oh, and "Drop Frames" means "The frame rate is reduced".I used translation software and felt that there might be some words that didn't make the right sense

**Comment by embeddedt** [comment]
The legacy versions of Embeddium are based on rather outdated versions of Sodium, so it's very possible that there is a VRAM memory leak. In particular, I am aware of an issue on 1.16.5 where the game uses more VRAM than it needs to, but haven't had time to write a proper fix yet.

I will add a mitigation for that issue, but I am not sure if it will solve your problem, especially since I suspect it might be exacerbated by a mod.

**Comment by embeddedt** [comment]
Try using https://nightly.link/embeddedt/embeddium/workflows/gradle/16.x%2Fforge/Embeddium.zip. It is based on 0.2.7 but contains an additional patch.

**Comment by A0000Xz** [comment]
Looks like the issue is solved, and the version you provided really doesn't have this issue anymore.
The longest test time is about 8 hours, and the VRAM footprint never exceeds 1GB in those 8 hours.
Before, it would slowly take up all the memory, but this time the memory is not going up。
Anyway the problem is solved, thanks.

**Comment by embeddedt** [comment]
I have released this fix in 0.2.9.
