### ISSUE TITLE
Visual Bugs with Create, SecurityCraft and Embeddium

### ISSUE THREAD

**Issue by MineyShadow** [FiniteReality/embeddium#93]
There seems to be a bug with the create mod where visual issues happen if you enter and exit a security camera from security craft. Some examples include ghost items on conveyor belts or display board letters persisting. This issue seems to be present on rubidium as well and no longer occurs if embeddium/rubidium is removed.
MC Version: 1.19.2
Forge: 43.3.0
Mods:
- Embeddium 0.2.7
- Create 0.5.1f
- SecurityCraft 1.9.6.1

**Comment by embeddedt** [comment]
I took a look at the SecurityCraft code, and the mixins used to implement the camera seem quite invasive. I am not sure if this can be fixed from my end.

Can you provide a simple block setup (e.g. in a superflat world) that can be used to reproduce the problem?

**Comment by MineyShadow** [comment]
https://youtu.be/1D_a9GSITBk

Even after breaking the blocks, these visual issues persist until you rejoin the world or a server.

**Comment by embeddedt** [comment]
Can you check if the same behavior occurs if you run `/flywheel backend off`? (You can run `/flywheel backend instancing` to re-enable Flywheel afterwards).

**Comment by MineyShadow** [comment]
Still happens even after using /flywheel backend off

**Comment by embeddedt** [comment]
Can you see if the latest beta fixes it? https://nightly.link/embeddedt/embeddium/workflows/gradle/19.2%2Fforge/Embeddium.zip

**Comment by MineyShadow** [comment]
Issue seems to be fixed in the beta, nice work!

**Comment by MineyShadow** [comment]
A side effect i noticed after the beta version during gameplay is there is a chance that some entities (eg: floating items, block entities) appear invisible after using a camera, though an easy workaround is either interacting with a block (eg: door) or reloading chunks with F3+A.

**Comment by embeddedt** [comment]
I think it is just an artifact of the weird way in which they implement their camera; it seems very likely to cause subtle bugs in my opinion, but I'm not a SecurityCraft developer. Even the other issue, despite being a bug in Embeddium, wouldn't occur in practice unless a mod was swapping the chunks in use under the hood like SecurityCraft does.

 I couldn't reproduce any disappearing entities/block entities in the test world even after flipping back and forth 50 times, so I will probably leave that unfixed, as the workaround is not annoying.

**Comment by MineyShadow** [comment]
Well the current beta fix/workaround is good enough if that is the case. thank you for the quick responses and beta fix!
