### ISSUE TITLE
Crash on world load.

### ISSUE THREAD

**Issue by LordM4x** [FiniteReality/embeddium#95]
I was exploring my world casually but my game randomly crashed, then I started it again thinking it was something else and it crashed again.
Minecraft version: 1.20.1
Embeddium version: 0.2.8
Embeddium + version: 1.0.1

Logs attached
[crash-2023-11-11_21.28.13-client.txt](https://github.com/embeddedt/embeddium/files/13326439/crash-2023-11-11_21.28.13-client.txt)
[latest.log](https://github.com/embeddedt/embeddium/files/13326440/latest.log)

**Comment by embeddedt** [comment]
It's a bug in Fusion/Rechiseled; I have reported it to their developer.

**Comment by embeddedt** [comment]
Downgrading to Fusion 1.0.6 might work for the time being.
