### ISSUE TITLE
[1.20.1] Create 0.5.1e contraptions visual glitches

### ISSUE THREAD

**Issue by KcDev09** [FiniteReality/embeddium#97]
Embeddium.: 0.2.9
Create ver.: 0.5.1e
Forge ver.: 47.2.0

NOTE: Create & Embeddium are bundled together with other mods, which may cause this issue. 
Feel free to let me know if you need a list of all the mods installed.

While testing my modpack, I came across an issue which causes the rear end of mechanical belts to visually remain in place while the hitbox is no longer present. It only disappears once I rejoin the world, but unfortunately returns once I build/destroy mechanical belts.
![2023-11-12_21 10 19](https://github.com/embeddedt/embeddium/assets/102786839/c0a4c4fc-dac5-419b-b1fa-1c7865d138ed)

This is not the only issue present, as windmills tend to go crazy in the form of twitching/ erratic spinning, tho this is only visual as the rest of the contraption remain the same & functioning as intended. 
(a screenshot unfortunately won't provide a sufficient visual example of the erratic spinning/ twitching of the windmill, sorry)

I have tried to recreate this issue with only embeddium 0.2.9 + create 0.5.1e installed with no success, so it could be another mod from my modpack causing this, so I will attempt to figure the culprit out in the meantime.

**Comment by embeddedt** [comment]
It definitely sounds like another mod is involved if it cannot be reproduced with Embeddium & Create alone, so figuring out which mod that is would be very helpful. Does F3+A fix it?

**Comment by KcDev09** [comment]
F3+A does seem to fix it temporarily, although the issue will return once I build mechanical belts. The same applies to the windmills issue.

Interestingly, the windmills only appear to spaz out whenever I move away far enough from them until they are hidden by the render distance fog and close in again until they are visible WHILE sitting in an immersive aircraft vehicle, and whenever I reenter the chunks with these vehicles, the windmills will appear glitched. 
Specifically, whenever I sit in either the biplane or the quadcopter, this issue occurs, but whenever I try with with any other vehicle provided by the mod, it does not happen.
I have tried this with normal creative flight as well as with an elytra and they do not seem to reproduce this issue, so when it comes to the windmill problem I guess there might be something off combining some immersive aircraft vehicles with create & embeddium.

**Comment by embeddedt** [comment]
Does your modpack use the ModernFix mod? There is a Forge bug with player tracking on vehicles which ModernFix fixes; if it's not installed, I would be curious to hear if it changes the behavior.

For future readers, this fix is applied on the server, so ModernFix only needs to be on the server for it to take effect in a multiplayer scenario.

**Comment by KcDev09** [comment]
I did not have it installed, but now after I did, it seemed to have fixed the windmill issue. Thank you for the suggestion.
I will continue to troubleshoot the mechanical belt problem and let you know of my findings.

**Comment by KcDev09** [comment]
So to my surprise, it appears that Sound Physics Remastered 1.2.1 seems to be causing this issue.

In the little instance I have created with only the latest version of Embeddium, ModernFix, FerriteCore & Create v0.5.1e, the addition of Sound Physics Remastered triggers the issue of mechanical belts not visually updating.
I have later removed it from my main modpack too and haven't noticed the issue as well for a while, so I guess it must be caused by that sound physics mod.

Do you think this is something that can be fixed on your end or is this solely on the Sound Physics mod?
Just asking out of curiosity as I don't mind keeping Sound Physics removed, as much as a bummer it may be.

**Comment by embeddedt** [comment]
Sometimes the "fancy effects" mods that add sound reverb or dynamic lights access the world on the wrong thread, which can cause corruption or weird crashes. I am not sure if Sound Physics Remastered is doing this; on a cursory glance of the code it looks like it might, but I will need to tinker with it myself to know for sure. If that is the case, there is often not a lot I can do from my end.

Thanks for your hard debugging work; it's much appreciated.

**Comment by embeddedt** [comment]
This indeed appears to be unsafe logic on the part of Sound Physics Remastered, and even if I work around it in Embeddium, it will probably cause other random issues with other mods. I would suggest avoiding the mod until they release an update that addresses this problem. I've made a report to them here: https://github.com/henkelmax/sound-physics-remastered/issues/172
