### ISSUE TITLE
[1.16.5] Startup crash with Better Foliage 

### ISSUE THREAD

**Issue by RyanIsAinmDom** [FiniteReality/embeddium#99]
This also happens with rubidium, but compatibility would be nice to have if possible.
Using embeddium 0.2.9 and Better Foliage 2.7.1

**Comment by embeddedt** [comment]
Better Foliage patches the vanilla renderer directly and won't function with Embeddium, even after fixing the startup crashes. Use [Better Foliage Renewed](https://legacy.curseforge.com/minecraft/mc-mods/better-foliage-renewed/files/3396105) instead.
